<script language="javascript" type="text/javascript">
 
   function toggle(source) {
       var strv3 = '';
       checkboxes = document.getElementsByName('chkXoa');
       for (var i = 0, n = checkboxes.length; i < n; i++) {
           checkboxes[i].checked = source.checked;
           if (source.checked == true) {
               strv3 = strv3 + checkboxes[i].value + ',';
           } else {
               strv3 = '';
           }

       }
       document.getElementById('hdIDInvitee').value = strv3;
   }
   function MaKHDel() {
       var strv3 = '';
       try{
           for (var i = 0; i < document.getElementsByName('chkXoa').length; i++) {
               if (document.getElementsByName('chkXoa')[i].checked == true) {
                   strvalue = document.getElementsByName('chkXoa')[i].value;
                   strv3 = strv3 + strvalue + ',';
               }
           }
       } catch (e) {
           strv3 = e.Message;
       }

       document.getElementById('hdIDInvitee').value = strv3;

   }


   function submitDetailsForm() {
        $("#formId").submit();
    }

   function fnSendMail(){
       if (CheckKH_EMAIL_All()){
           $('#sendemails').html("Đang trong quá trình gửi. Vui lòng chờ trong giây lát...");
           $.ajax({
               type: "POST",
               url: "http://qr.hoabinhtourist.com/admin/invitee/sendmail",
               data: "txtIDs=" + $("#hdIDInvitee").val()+"&tmp_email=" + $("#emailtmp").val(),
               dataType: "html",
               success: function(html){
                   if(html!='0'){
                       $('#sendemails').html('<button onclick="fnSendMail()" style="float: right;margin: 10px 0;" class="btn btn-primary" id="btnGui" name="btnGui"><i class="fa fa-paper-plane" aria-hidden="true"></i> Send</button><br/><span style="color:darkgreen;">Gửi thành công</span>');
                       //$('#sendemails').html(html);
                   }else {
                       $('#sendemails').html('<button onclick="fnSendMail()" style="float: right;margin: 10px 0;" class="btn btn-primary" id="btnGui" name="btnGui"><i class="fa fa-paper-plane" aria-hidden="true"></i> Send</button><br/><span style="color:red;">Đã xảy ra lỗi trong quá trình gửi. Vui lòng thử lại</span>');
                   }
               }
           });
       }
   }

   function CheckKH_EMAIL_All() {
       if ($("#hdIDInvitee").val() == "") {
           alert("Bạn phải chọn ít nhất một khách mời để gửi Email");
           return false;
       }
       return true
   };

</script>
<input type="hidden" id="hdIDInvitee" name="hdIDInvitee" value="" />
	<div class="row">


									<div class="col-xs-12">
										<h3 class="header smaller lighter blue">
                                            Khai báo danh mục » Danh mục khách mời</h3>
                                        <div class="row">
                                            <div class="col-md-2 col-sm-2 col-xs-12">
                                                <select id="ddlCusType" name="ddlCusType" class="form-control">
                                                    <option value="0">Lựa chọn loại khách mời</option>
                                                    <?php if (count($this->invitee_type) > 0) {?>
                                                        <?php
                                                        foreach($this->invitee_type as $val):
                                                            ?>
                                                            <option value="<?php echo $val['id']; ?>"><?php echo $val['name']; ?></option>
                                                        <?php endforeach; }?>
                                                </select>
                                            </div>
                                            <div class="col-md-4 col-sm-4 col-xs-12">
                                                <!--<form id="formId" name="formId" action="http://qr.hoabinhtourist.com/admin/invitee/">-->
                                                    <input type="text" style="float:left;width: 85%;" id="txtSearch" name="txtSearch" value="" class="form-control"/>
                                                    <button onclick="submitDetailsForm()" type="button" style="float:left;padding: 2px 8px;" class="btn"><i class="fa fa-search" aria-hidden="true"></i></button>
                                                <!--</form>-->

                                            </div>
                                            <div class="col-md-6 col-sm-6 col-xs-12">
                                                <p style="text-align: right;">

                                                    <!--
                                                    <a class="btn btn-info btn-sm" style="margin-right: 5px;" href="javascript:void(0);">Import Excel</a>
                                                    <a class="btn btn-info btn-sm" href="/admin/invitee/create">Thêm mới</a>
                                                    -->
                                                <div class="widget-toolbar no-border">
                                                    <a style="padding: 0 5px;" class="btn btn-info btn-sm" href="/admin/invitee/create">Thêm mới</a>
                                                    <a style="padding: 0 5px;" class="btn btn-info btn-sm" href="/admin/invitee/create"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Import</a>
                                                    <a style="padding: 0 5px;" class="btn btn-info btn-sm" href="/admin/invitee/create"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Export</a>
                                                    <button class="btn btn-xs btn-info2 dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
                                                        Thao tác
                                                        <i class="ace-icon fa fa-chevron-down icon-on-right"></i>
                                                    </button>

                                                    <ul class="dropdown-menu dropdown-yellow dropdown-menu-right dropdown-caret dropdown-close">
                                                        <!--<li>
                                                            <a href="#"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Import</a>
                                                        </li>-->

                                                        <!--
                                                        <li>
                                                            <a href="#"><i class="fa fa-file-excel-o" aria-hidden="true"></i> Export</a>
                                                        </li>
                                                        -->

                                                        <li>
                                                            <a href="javascript:void(0);" data-toggle="modal" data-target="#hanoi05day"><i class="fa fa-paper-plane" aria-hidden="true"></i> Gửi Email</a>
                                                        </li>

                                                        <li class="divider"></li>

                                                        <li>
                                                            <a href="#"><i class="ace-icon fa fa-trash-o bigger-120"></i> Xóa các dòng đã chọn</a>
                                                        </li>
                                                    </ul>

                                                </div>
                                                </p>
                                            </div>
                                        </div>
                                        <p style="margin-top: 1px;width: 100%;"></p>
                                        <?php if (count($this->data) > 0) {?>
                                            <div class="table-responsive">
                                                <table id="table_events" class="table table-striped table-bordered table-hover">
                                                    <thead>
                                                    <tr>
                                                        <th>Họ & tên</th>
                                                        <th>Địa chỉ</th>
                                                        <th>Di động</th>
                                                        <th>Email</th>
                                                        <th style="text-align: center;vertical-align: middle;">Checkin</th>
                                                        <th style="width: 8%;vertical-align: middle;text-align: center;">Thao tác</th>
                                                        <th style="text-align: center;vertical-align: middle;">
                                                            <label><input  onClick="toggle(this)" name="chkXoaAll" type="checkbox" class="ace" /><span class="lbl"></span></label>
                                                        </th>
                                                    </tr>
                                                    </thead>
                                                    <tbody>
                                                    <?php
                                                    foreach($this->data as $item)
                                                    {
                                                        $_checkin='';
                                                        if ($item['checkedIn']!='0'){
                                                            $_checkin='<label><input checked type="checkbox" class="ace" /><span class="lbl"></span></label>';
                                                        }else{
                                                            $_checkin='<label><input type="checkbox" class="ace" /><span class="lbl"></span></label>';
                                                        }

                                                        echo '<tr>
                                                <td width="15%"><b>
                                                <a class="green" href="/admin/invitee/edit/id/'.$item['id'].'">'.$item['fullname'].'</a>
                                                </b></td>
                                                <td>'.$item['address'].'</td>
                                                <td>'.$item['phone'].'</td>
                                                <td>'.$item['email'].'</td>
                                                <td style="text-align: center;vertical-align: middle;">'.$_checkin.'</td>
                                                <td style="text-align: center;vertical-align: middle;">
                                                    <a title="Xem" href="javascript:void(0);"><i style="font-size: large;" class="fa fa-eye" aria-hidden="true"></i></a>
                                                    <a title="Sửa" href="/admin/invitee/edit/id/'.$item['id'].'"><i style="font-size: large;margin: 0 5px;" class="fa fa-pencil" aria-hidden="true"></i></a>
                                                    <a title="Xóa" onclick="return confirm(\'Bạn có thật sự muốn xóa?\');" href="/admin/invitee/delete/id/'.$item['id'].'" ><i style="font-size: large;color: red;" class="fa fa-times" aria-hidden="true"></i></a>
                                                </td>
                                                <td class="center">                                                        
                                                        <label><input type="checkbox" class="ace"onclick="MaKHDel();" name="chkXoa" value="'.$item['id'].'" id="chkXoa_'.$item['id'].'" /><span class="lbl"></span></label>
                                                </td>
                                                </tr>';

                                                    }
                                                    ?>

                                                    </tbody>
                                                </table>

                                                <?php
                                                echo $this->paginationControl($this->data, 'Sliding' , 'pagination.phtml');
                                                ?>
                                            </div>
                                        <?php }else{ echo "Không có bản ghi nào"; }?>

									</div>
								</div>
	<br/>
<!-- Central Modal Large Info-->
<div class="modal fade" id="hanoi05day" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg modal-notify modal-info" role="document">
        <!--Content-->
        <div class="modal-content">
            <!--Header-->
            <div class="modal-header">
                <i class="fa fa-envelope" aria-hidden="true"></i> Send Email Template
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true" class="white-text">&times;</span>
                </button>
            </div>
            <!--Body-->
            <div class="modal-body">
                <select id="emailtmp" name="emailtmp" class="form-control">
                    <option value="0">Lựa chọn mẫu thư mời</option>
                    <?php if (count($this->items_email) > 0) {?>
                        <?php
                        foreach($this->items_email as $val):
                            ?>
                            <option value="<?php echo $val['id']; ?>"><?php echo $val['title']; ?></option>
                        <?php endforeach; }?>
                </select>
                <div id="sendemails">
                    <button onclick="fnSendMail()" style="float: right;margin: 10px 0;" class="btn btn-primary" id="btnGui" name="btnGui"><i class="fa fa-paper-plane" aria-hidden="true"></i> Send</button>
                </div>
            </div>


            <!--Footer-->
            <div class="modal-footer" style="clear: both;" id="register_process">
                <input type="button" value="Close" class="btn btn-outline-info waves-effect" data-dismiss="modal">
            </div>
        </div>
        <!--/.Content-->
    </div>
</div>
<!-- Central Modal Large Info-->


<script type="text/javascript">
			jQuery(function($) {
				var oTable1 = $('#table_events').dataTable( {
				"aoColumns": [
			      { "bSortable": false },
			      null, null
				] } );


			})
		</script>
