	<div class="row">
		

									<div class="col-xs-12">
										<h3 class="header smaller lighter blue">
                                            Khai báo danh mục » Danh mục khách mời</h3>
									

										<div class="table-responsive">
											<table id="table_events" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														
														<th>STT</th>
														<th>Họ & tên</th>
                                                        <th>Địa chỉ</th>
                                                        <th>Di động</th>
                                                        <th>Email</th>
                                                        <th>Checkin</th>
														<th>Action</th>	
													</tr>
												</thead>

												<tbody>
				<?php echo $this->partialLoop('_invitee-row.phtml', $this->products); ?>

												</tbody>
											</table>
											
										</div>
								
<br/>
<a class="btn btn-info btn-sm" href="/admin/invitee/create">Tạo mới</a>
										
									</div>
								</div>
	<br/>
	
	
						
<script type="text/javascript">
			jQuery(function($) {
				var oTable1 = $('#table_events').dataTable( {
				"aoColumns": [
			      { "bSortable": false },
			      null, null
				] } );
				
				
			})
		</script>									
