<tr>
	<td class="center">
			<label>
			<input type="checkbox" class="ace" />
		<span class="lbl"></span>
			</label>
	</td>
    
    <td><?php echo $this->name; ?></td>
    <td><?php echo number_format($this->price); ?>đ</td>
    <td><?php echo $this->String()->cut_string(strip_tags($this->shortDescription),'200','...'); ?></td>
    <td width="16%">
        <a class="green" href='/<?=ADMIN?>/product/edit/id/<?php echo $this->pid;?>'><i class="fa fa-pencil bigger-130"></i></a> |
        <a title="Quản lý ảnh sản phẩm" class="green" href='/<?=ADMIN?>/product/photo/id/<?php echo $this->pid;?>'><i class="fa fa-picture-o bigger-130"></i></a> | <?php if($this->status == 1){ ?>
         <a title="&#7848;n" class="orange" id="hide_<?php echo $this->pid;?>" href="javascript:void(0);" onclick="hide(this)"><i class="fa fa-eye  bigger-130"></i></a>
           <a title="Hi&#7879;n" style="color: #848484;display: none;" id="show_<?php echo $this->pid;?>" href="javascript:void(0);" onclick="show(this)"><i class="fa fa-eye-slash bigger-130"></i> </a> 
         <?php }else { ?>
	      <a title="&#7848;n" style="color: #848484;" id="show_<?php echo $this->pid;?>" href="javascript:void(0);" onclick="show(this)"><i class="fa fa-eye-slash  bigger-130"></i></a> 
	      <a title="&#7848;n" class="orange" style ="display: none;" id="hide_<?php echo $this->pid;?>" href="javascript:void(0);" onclick="hide(this)"><i class="fa fa-eye bigger-130"></i> </a>    
	         
     <?php    } ?>
     &nbsp;
|&nbsp;
        <?php if($this->featured == 1){ ?>
         <a title="Set unfeature" class="orange" id="unfeature_<?php echo $this->pid;?>" href="javascript:void(0);" onclick="unfeature(this)"><i class="fa fa-star bigger-130"></i></a>
           <a title="Set feature" style="color: #848484;display: none;" id="feature_<?php echo $this->pid;?>" href="javascript:void(0);" onclick="feature(this)"><i class="fa fa-star bigger-130"></i> </a> 
         <?php }else { ?>
	      <a title="Set feature" style="color: #848484;" id="feature_<?php echo $this->pid;?>" href="javascript:void(0);" onclick="feature(this)"><i class="fa fa-star bigger-130"></i></a> 
	      <a title="Set unfeature" class="orange" style ="display: none;" id="unfeature_<?php echo $this->pid;?>" href="javascript:void(0);" onclick="unfeature(this)"><i class="fa fa-star bigger-130"></i> </a>    
	         
     <?php    } ?>
     &nbsp;
        <a onclick="return confirm('Bạn muốn xóa?');"  class="red" href='/<?=ADMIN?>/product/delete/id/<?php echo $this->pid;?>'><i class="fa fa-trash bigger-130"></i></a>
    </td>
</tr>

<script type="text/javascript">
 
     
     function feature(o){
	var ID = $(o).attr("id");
	var sid=ID.split("_");
	var newID = sid[1];

	 $('#feature_' + newID).hide();
	var data = 'id=' + newID;
  
    $.ajax({
            type: "POST",
            url: "/admin/product/feature",
            data: data,
            dataType: 'json',
            success: function(data){
              console.log(data);
             

   $('#unfeature_' + newID).show();
        
                       
            }
         
        });
		
	 return false;
	 
     }
     
     
      
     function unfeature(o){
	var ID = $(o).attr("id");
	var sid=ID.split("_");
	var newID = sid[1];
	
	//alert(userID);
	
	var data = 'id=' + newID;
  $('#unfeature_' + newID).hide();

    
    $.ajax({
            type: "POST",
            url: "/admin/product/unfeature",
            data: data,
            dataType: 'json',
            success: function(data){
              console.log(data);

   $('#feature_' + newID).show();
         
              
            }
        });
		
	 return false;
	 
     }
    
     function show(o){
	var ID = $(o).attr("id");
	var sid=ID.split("_");
	var newID = sid[1];

	 $('#show_' + newID).hide();
	var data = 'id=' + newID;
    
    $.ajax({
            type: "POST",
            url: "/admin/product/show",
            data: data,
            dataType: 'json',
            success: function(data){
              console.log(data);
             

   $('#hide_' + newID).show();
        
            
           
            }
         
        });
		
	 return false;
	 
     }	
    
  function hide(o){
	var ID = $(o).attr("id");
	var sid=ID.split("_");
	var newID = sid[1];
	
	//alert(userID);
	
	var data = 'id=' + newID;
  $('#hide_' + newID).hide();

    
    $.ajax({
            type: "POST",
            url: "/admin/product/hide",
            data: data,
            dataType: 'json',
            success: function(data){
              console.log(data);

   $('#show_' + newID).show();
         
              
            }
        });
		
	 return false;
	 
     }


    </script>