<tr>
	<td class="center">
			<label>
			<input type="checkbox" class="ace" />
		<span class="lbl"></span>
			</label>
	</td>
    
    <td><a href="/admin/product/edit/id/<?=$this->id_product?>"><?php echo $this->name; ?></a></td>
    <td><?php echo $this->email; ?></td>
    <td><?php echo $this->mobile; ?></td>
    <td><?php echo $this->address; ?></td>
    <td width="10%">
        <a class="green" href='/<?=ADMIN?>/product/booktour/view/id/<?php echo $this->id;?>'><i class="icon-pencil bigger-130"></i></a> |
        <a class="red" href='/<?=ADMIN?>/product/booktour/delete/id/<?php echo $this->id;?>'><i class="icon-trash bigger-130"></i></a>
    </td>
</tr>

