<dt id="parentID-label">
<label class="required" for="parentID">Chọn Điểm đến:</label>
</dt>
<dd id="parentID-element">
<?php
	$mdlMenu = new Model_MenuItem();
        $parentVal = 0;
        $a = null;
$options = $this->element->getDecorator('ViewScript')->getOptions();
	if(!empty($options)){
		$optionString = $options['List'];	
		$parentVal =  $optionString;
	}   
	
        /*
        $parentId = $this->createElement('select', 'parentID');
        // element options
        $parentId->setLabel('Chọn danh mục: ');
        $parentId->setRequired(true);
*/
       
        $select = $mdlMenu->select();
       // $select->where('parent = ?', 0);
        $select->where('menu_id = ?', 6);
        $select->order('position asc');
        $menus = $mdlMenu->fetchAll($select);
         /*
        $parentId->addMultiOption(0, 'None');
        if($menus->count() > 0) {
            foreach ($menus as $menu) {
                $parentId->addMultiOption($menu->id, $menu->name);
				} 
			}
		$parentId->setValue($parentVal);	//set selected
			
		$this->addElement($parentId);
        */
		$recursive = new Louis_System_Recursive($menus->toArray());
        $newArr = $recursive->buildArray(72);
  
       $attribs = array('style' => 'width:250px');
        echo $mdlMenu->itemInSelectbox('end',$parentVal,$newArr,'Chọn điểm đến',$attribs);
       ?>
</dd>