<dt id="parentID-label">
<label class="required" for="parentID">Chọn danh mục:</label>
</dt>
<dd id="parentID-element">
<?php
	$mdlMenu = new Model_MenuItem();
        $parentVal = 0;
        $a = null;
        $db = Zend_Db_Table::getDefaultAdapter();
       $mID = Zend_Controller_Front::getInstance()->getRequest()->getParam('id');
       //echo $mID;
       $select = 'select category_id from product_relationships where object_id = "'.$mID.'"';
       $parentArray = array();
       $result = $db->fetchAll($select);
  //Zend_Debug::dump($mID); exit();
       foreach($result as $key=>$val):
       		$parentArray[] = $val['category_id'];
         
       endforeach;
       //Zend_Debug::dump($parentArray); exit();
  // $parentVal = array(49,55,56);
        /*
        $parentId = $this->createElement('select', 'parentID');
        // element options
        $parentId->setLabel('Chọn danh mục: ');
        $parentId->setRequired(true);
*/
       
        $select = $mdlMenu->select();
       // $select->where('parent = ?', 0);
        $select->where('menu_id = ?', 2);
        $select->where('lang = ?', 'vi');
        $select->order('position asc');
        $menus = $mdlMenu->fetchAll($select);
         /*
        $parentId->addMultiOption(0, 'None');
        if($menus->count() > 0) {
            foreach ($menus as $menu) {
                $parentId->addMultiOption($menu->id, $menu->name);
				} 
			}
		$parentId->setValue($parentVal);	//set selected
			
		$this->addElement($parentId);
        */
		$recursive = new Louis_System_Recursive($menus->toArray());
        $newArr = $recursive->buildArray(233);
  
        $attribs = array('size'=>5, 'style'=>'width:250px', 'multiple'=>true);
        echo $mdlMenu->editItemInSelectbox('parentID[]',$parentArray,$newArr,$attribs);
       ?>
       <br/>
       <span style="margin: 10px 20px;display: block;">Chú ý: Giữ phím CTRL để chọn nhiều danh mục</span>
</dd>