<div id="middlecol" class="span8 sidebar_left">
		<div class="inside">
		<div class="item-page">
			<div class="span12">
<h2>Kết quả tìm kiếm</h2>
<?php 

	if(is_array($this->results) && count($this->results) > 0) { 
	
	
?>
<p>Your search for <em><?php echo $this->keywords; ?></em> returned <?php echo count($this->results); ?> results.</p>
<?php foreach ($this->results as $result) {
	?>
<h3><a style="color: #02265C;" href='/tin-tuc.html'><?php echo $result->name; ?></a></h3>
     <p><?php //echo $result->shortDescription; ?></p>
     <?php }} else {?>
     <p>Your search did not return any results</p>
     <?php }?>
     
			</div>
		</div>
		</div>
</div>