<tr>
	<td class="center">
			<label>
			<input type="checkbox" class="ace" />
		<span class="lbl"></span>
			</label>
	</td>
    
    <td><?php echo $this->name; ?></td>
    <td><?php echo strip_tags($this->shortDescription); ?></td>
    <td width="16%">
        <a class="green" href='/<?=ADMIN?>/new/edit/id/<?php echo $this->id;?>'><i class="icon-pencil bigger-130"></i></a> |
        <a title="Quản lý ảnh tin tức" class="green" href='/<?=ADMIN?>/new/photo/id/<?php echo $this->id;?>'><i class="icon-th-list bigger-130"></i></a> | 
      <?php  if($this->status == 1){ ?>
         <a title="&#7848;n" class="orange" id="hide_<?php echo $this->id;?>" href="javascript:void(0);" onclick="hide(this)"><i class="icon-eye-open  bigger-130"></i></a>
           <a title="Hi&#7879;n" style="color: #848484;display: none;" id="show_<?php echo $this->id;?>" href="javascript:void(0);" onclick="show(this)"><i class="icon-eye-close bigger-130"></i> </a> 
         <?php }
	         else { ?>
	      <a title="&#7848;n" style="color: #848484;" id="show_<?php echo $this->id;?>" href="javascript:void(0);" onclick="show(this)"><i class="icon-eye-close  bigger-130"></i></a> 
	      <a title="&#7848;n" class="orange" style ="display: none;" id="hide_<?php echo $this->id;?>" href="javascript:void(0);" onclick="hide(this)"><i class="icon-eye-open bigger-130"></i> </a>    
	         
     <?php    } ?>
        &nbsp;
|&nbsp;
        <?php if($this->featured == 1){ ?>
         <a title="Set unfeature" class="orange" id="unfeature_<?php echo $this->id;?>" href="javascript:void(0);" onclick="unfeature(this)"><i class="icon-star bigger-130"></i></a>
           <a title="Set feature" style="color: #848484;display: none;" id="feature_<?php echo $this->id;?>" href="javascript:void(0);" onclick="feature(this)"><i class="icon-star bigger-130"></i> </a> 
         <?php }else { ?>
	      <a title="Set feature" style="color: #848484;" id="feature_<?php echo $this->id;?>" href="javascript:void(0);" onclick="feature(this)"><i class="icon-star bigger-130"></i></a> 
	      <a title="Set unfeature" class="orange" style ="display: none;" id="unfeature_<?php echo $this->id;?>" href="javascript:void(0);" onclick="unfeature(this)"><i class="icon-star bigger-130"></i> </a>    
	         
     <?php    } ?>
     
        <a onclick="return confirm('Bạn muốn xóa?');"  class="red" href='/<?=ADMIN?>/new/delete/id/<?php echo $this->id;?>'><i class="icon-trash bigger-130"></i></a>
    </td>
</tr>

<script type="text/javascript">
 
     var j = jQuery.noConflict();
     
     function feature(o){
	var ID = j(o).attr("id");
	var sid=ID.split("_");
	var newID = sid[1];

	 j('#feature_' + newID).hide();
	var data = 'id=' + newID;
  
    j.ajax({
            type: "POST",
            url: "/admin/new/feature",
            data: data,
            dataType: 'json',
            success: function(data){
              console.log(data);
             

   j('#unfeature_' + newID).show();
        
            
           
            }
         
        });
		
	 return false;
	 
     }
     
     
      
     function unfeature(o){
	var ID = j(o).attr("id");
	var sid=ID.split("_");
	var newID = sid[1];
	
	//alert(userID);
	
	var data = 'id=' + newID;
  j('#unfeature_' + newID).hide();

    
    j.ajax({
            type: "POST",
            url: "/admin/new/unfeature",
            data: data,
            dataType: 'json',
            success: function(data){
              console.log(data);

   j('#feature_' + newID).show();
         
              
            }
        });
		
	 return false;
	 
     }
    
     function show(o){
	var ID = j(o).attr("id");
	var sid=ID.split("_");
	var newID = sid[1];

	 j('#show_' + newID).hide();
	var data = 'id=' + newID;
  
    j.ajax({
            type: "POST",
            url: "/admin/new/show",
            data: data,
            dataType: 'json',
            success: function(data){
              console.log(data);
             

   j('#hide_' + newID).show();
        
            
           
            }
         
        });
		
	 return false;
	 
     }	
    
  function hide(o){
	var ID = j(o).attr("id");
	var sid=ID.split("_");
	var newID = sid[1];
	
	//alert(userID);
	
	var data = 'id=' + newID;
  j('#hide_' + newID).hide();

    
    j.ajax({
            type: "POST",
            url: "/admin/new/hide",
            data: data,
            dataType: 'json',
            success: function(data){
              console.log(data);

   j('#show_' + newID).show();
         
              
            }
        });
		
	 return false;
	 
     }


    </script>