<section class="container paddtb10">
		<div class="col-sm-3">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Tìm Tours</h3>
				</div>
				<div class="panel-body">
					<form action="" method="POST" role="form">
						<div class="form-group">
							<label>Bạn muốn đi du lịch ở đâu</label>
							<div class="input-group">
						      	<input type="text" class="form-control" id="exampleInputAmount" placeholder="Địa điểm">
						      	<div class="input-group-addon"><span class="glyphicon glyphicon-search"></span></div>
						    </div>
						</div>
					</form>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Bộ lọc</h3>
				</div>
				<div class="panel-body loc-tours">
					<div class="row">
						<h4 class="title-loc">Theo mức giá <span class="pull-right" data-toggle="collapse" data-target="#lt-gia" aria-expanded="false" aria-controls="lt-gia"><i class="fa fa-sort-asc" aria-hidden="true"></i></span></h4>
						<div class="collapse in" id="lt-gia">
						  	<div class="col-sm-12">
						    	<div class="checkbox">
						    		<label>
						    			<input type="checkbox" name="price[]" value="1" class="price">
						    			Dưới 2,000,000 VNĐ
						    		</label>
						    	</div>
						    	<div class="checkbox">
						    		<label>
						    			<input type="checkbox" name="price[]" value="2" class="price">
						    			2,000,000 - 4,000,000 VNĐ
						    		</label>
						    	</div>
						    	<div class="checkbox">
						    		<label>
						    			<input type="checkbox" name="price[]" value="3" class="price">
						    			4,000,000 - 6,000,000 VNĐ
						    		</label>
						    	</div>
						  	</div>
						</div>
					</div>

					<div class="row">
						<h4 class="title-loc">Theo loại tours <span class="pull-right" data-toggle="collapse" data-target="#lt-loai" aria-expanded="false" aria-controls="lt-loai"><i class="fa fa-sort-asc" aria-hidden="true"></i></span></h4>
						<div class="collapse in" id="lt-loai">
						  	<div class="col-sm-12">
						    	<div class="checkbox">
						    		<label>
						    			<input type="checkbox" name="tour[]" value="1" class="tour">
						    			Trọn gói
						    		</label>
						    	</div>
						    	<div class="checkbox">
						    		<label>
						    			<input type="checkbox" name="tour[]" value="2" class="tour">
						    			Chỉ vé máy bay và khách sạn
						    		</label>
						    	</div>
						    	<div class="checkbox">
						    		<label>
						    			<input type="checkbox" name="tour[]" value="3" class="tour">
						    			Không vé máy bay
						    		</label>
						    	</div>
						  	</div>
						</div>
					</div>

					<div class="row">
						<h4 class="title-loc">Theo chủ đề <span class="pull-right" data-toggle="collapse" data-target="#lt-chude" aria-expanded="false" aria-controls="lt-chude"><i class="fa fa-sort-asc" aria-hidden="true"></i></span></h4>
						<div class="collapse in" id="lt-chude">
						  	<div class="col-sm-12">
						    	<div class="checkbox">
						    		<label>
						    			<input type="checkbox" name="travel[]" value="1" class="travel">
						    			Du lịch khám phá
						    		</label>
						    	</div>
						    	<div class="checkbox">
						    		<label>
						    			<input type="checkbox" name="travel[]" value="2" class="travel">
						    			Du lịch biển đảo
						    		</label>
						    	</div>
						    	<div class="checkbox">
						    		<label>
						    			<input type="checkbox" name="travel[]" value="3" class="travel">
						    			Du lịch mua sắm, lễ hội
						    		</label>
						    	</div>
						  	</div>
						</div>
					</div>
				</div>
			</div>

			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Tour Khuyến mại</h3>
				</div>
				<div class="panel-body ds-content-left padd10">
					<div class="list-group margin00">
						<a href="#" class="list-group-item">
							<img src="images/dulich/du-lich01.jpg" class="pull-left">
							Siem Riep-Phnom Penh - Khách sạn 3* ( Siêu Tiết Kiệm)
							<span class="clearfix"></span>
						</a>
						<a class="list-group-item">
							<img src="images/dulich/du-lich02.jpg" class="pull-left">Siem Riep-Phnom Penh - Khách sạn 3* ( Siêu Tiết Kiệm)
							<span class="clearfix"></span>
						</a>
						<a class="list-group-item">
							<img src="images/dulich/du-lich03.jpg" class="pull-left">Siem Riep-Phnom Penh - Khách sạn 3* ( Siêu Tiết Kiệm)
							<span class="clearfix"></span>
						</a>
						<a class="list-group-item">
							<img src="images/dulich/du-lich04.jpg" class="pull-left">Siem Riep-Phnom Penh - Khách sạn 3* ( Siêu Tiết Kiệm)
							<span class="clearfix"></span>
						</a>
						<a class="list-group-item">
							<img src="images/dulich/du-lich05.jpg" class="pull-left">Siem Riep-Phnom Penh - Khách sạn 3* ( Siêu Tiết Kiệm)
							<span class="clearfix"></span>
						</a>
					</div>
				</div>
			</div>

		</div>
		<div class="col-sm-9 list-tour">
			<div class="fix-img100" id="list_tour_category">
				<h2>TOUR ĐI <?php echo strtoupper($this->title); ?> <span>(<?php echo $this->count_tour; ?> tour)</span>
					<div class="pull-right">
						<select onchange="location = this.value;" style="width:150px;background: #fff;border: 1px solid #e1e1e1;border-radius: 4px;">
                                <option value="/<?=$this->current?>" <?php echo ($this->uri == '/'.$this->current)?' selected="selected"':''; ?>>Sắp xếp hiển thị</option>                   
                    			<option value="/<?=$this->current?>/sort/price/order/asc" <?php echo ($this->uri == '/'.$this->current.'/sort/price/order/asc')?' selected="selected"':''; ?>>Giá tăng dần</option>
                    			<option value="/<?=$this->current?>/sort/price/order/desc" <?php echo ($this->uri == '/'.$this->current.'/sort/price/order/desc')?' selected="selected"':''; ?>>Giá giảm dần</option>
                    			<option value="/<?=$this->current?>/sort/time/order/asc" <?php echo ($this->uri == '/'.$this->current.'/sort/time/order/asc')?' selected="selected"':''; ?>>Lịch trình ngắn ngày</option>
                    			<option value="/<?=$this->current?>/sort/time/order/desc" <?php echo ($this->uri == '/'.$this->current.'/sort/time/order/desc')?' selected="selected"':''; ?>>Lịch trình dài ngày</option>
							</select>
					</div>
				</h2>
				<?php foreach($this->paginator as $key=>$obj):
					
					$time_travel = explode('.',$obj['time_travel']);
					if(!isset($time_travel[1])){
						$dem = '';
					}else{
						$dem = $time_travel[1]. ' đêm';
					}
					$full_img = PATH_TOURS . $obj['id']. '/' .$obj['full'];
					$com_arr = explode(',',$obj['communication']);
					$icon = '';
					foreach($com_arr as $val):
				    $icon.= ($val == 'car')?'<i class="fa fa-bus" aria-hidden="true"></i>':'';
				    $icon.= ($val == 'train')?' <i class="fa fa-train" aria-hidden="true"></i>':'';
				    $icon.= ($val == 'plane')?' <i class="fa fa-plane" aria-hidden="true"></i>':'';
				    $icon.= ($val == 'bike')?' <i class="fa fa-bicycle" aria-hidden="true"></i>':'';
				    $icon.= ($val == 'cruise')?' <i class="fa fa-ship" aria-hidden="true"></i>':'';
					endforeach;
					///public/images/tours/403/Bac-Kan.jpeg
					 ?>
			
				<div class="col-sm-6">
					<a href="#"><img class="img-rounded tnt" src="<?php echo $full_img; ?>"></a>
					<div class="tour-content">
						<h3><a href="#"> <?php echo $obj['name']; ?></a></h3>
						<p>
						<span class="pull-left"><i class="fa fa-clock-o" aria-hidden="true"></i> <?php echo $time_travel[0]; ?> ngày <?php echo $dem; ?></span> 
						<span class="pull-right"> <?php echo $icon; ?></span>
						</p>
						<span class="clearfix"></span>
						<p><i class="fa fa-map-marker" aria-hidden="true"></i> <?php echo $obj['schedule']; ?></p>
						<h4 class="text-danger"> <?php echo number_format($obj['price']); ?> VNĐ <a href="#" class="btn btn-info pull-right">Xem tour</a></h4>

						<span class="clearfix"></span>
					</div>
				</div>
				<?php endforeach; ?>

				<span class="clearfix"></span>
				<?php echo $this->paginationControl($this->menus,
                     'Sliding',
                     'pagination-control.phtml'); ?>

			</div>
		</div>
		</div>
</section>

<script>
	 $(document).ready(function() {
var mid = '<?php echo $this->id_menu; ?>';		 
		 
var checkprice = $("input[name='price[]']:checkbox");
var checktour = $("input[name='tour[]']:checkbox");
var checktravel= $("input[name='travel[]']:checkbox");

function callprice(){
   var classname = $(this).attr('class');
   	var values_price = [];
   	var values_tour = [];
   	var values_travel = [];
  
		checkprice.filter(':checked').map(function(){ 
			values_price.push($(this).attr('class') + '_' + $(this).val());
			
		    }).get();
		    
		  checktour.filter(':checked').map(function(){ 
			values_tour.push($(this).attr('class') + '_' + $(this).val());
			
		    }).get();
		    
		 checktravel.filter(':checked').map(function(){ 
			values_travel.push($(this).attr('class') + '_' + $(this).val());
			
		    }).get();
      
  //  console.log(valuesarr);
   obj_price = values_price.join(',');
   obj_tour = values_tour.join(',');
   obj_travel = values_travel.join(',');
  
   console.log(obj_price);
  console.log(obj_tour);
  console.log(obj_travel);

   $.ajax({
    type: "POST",
    url: '/admin/product/tour',
    data: {price: obj_price, tour: obj_tour, travel: obj_travel, mid: mid},
    success: function(response)
    {
	    
    
  var data = $.parseJSON(response);
      $.each( data, function( key, value ) {
  console.log(value);
      var item = '';
      item += '<div class="col-sm-6">';
      item += '<a href="#">';
      item += '<img class="img-rounded tnt" src="'+value.img+'">';
      item += '</a>';
      item += '<div class="tour-content">';
      item += '<h3><a href="#"> '+value.name+'</a></h3>';
      item += '<p>';
      item += '<span class="pull-left"><i class="fa fa-clock-o" aria-hidden="true"></i>'+value.time_travel+'</span>';
      item += '<span class="pull-right"> '+value.communication+'</span>';
      item += '</p>';
      item += '<span class="clearfix"></span>';
      item += '<p><i class="fa fa-map-marker" aria-hidden="true"></i>'+value.schedule+'</p>';
      item += '<h4 class="text-danger"> '+value.price+' VNĐ <a href="#" class="btn btn-info pull-right">Xem tour</a></h4>';
      item += '<span class="clearfix"></span>';
      item += '</div>';
      $('#list_tour_category').append(item);
});
     
    }
});
	
  
	    };

	    
     checkprice.on('click',callprice);
     checktour.on('click',callprice);
	 checktravel.on('click',callprice); 
    	
	 callprice();
	
	
});
</script>