	<div class="row">
		

									<div class="col-xs-12">
										<h3 class="header smaller lighter blue">Quản lý hệ thống » Cấu hình thông tin gửi email</h3>
									

										<div class="table-responsive">
											<table id="table_events" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														
														<th>STT</th>
														<th>Tên sự kiện</th>
                                                        <th>Ngày bắt đầu</th>
                                                        <th>Ngày kết thúc</th>
                                                        <th>Địa điểm tổ chức hội nghị</th>
														<th>Action</th>	
													</tr>
												</thead>

												<tbody>
				<?php /*echo $this->partialLoop('_events-row.phtml', $this->products);*/ ?>

												</tbody>
											</table>
											
										</div>
								
<br/>
<a class="btn btn-info btn-sm" href="/admin/smtpconfig/create">Tạo mới</a>
										
									</div>
								</div>
	<br/>
	
	
						
<script type="text/javascript">
			jQuery(function($) {
				var oTable1 = $('#table_events').dataTable( {
				"aoColumns": [
			      { "bSortable": false },
			      null, null
				] } );
				
				
			})
		</script>									
