<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title></title>
</head>
<body>	
	<table border="0" cellpadding="20" cellspacing="0" style="width:800px;border:solid 1px #1B2854;">
	<tbody>
		<tr>
			<td colspan="2" style="color:#1B2854; ">
			<p><strong>Xin chào <?=$this->name?>,</strong><br />
			<br />
            Cám ơn bạn đã quan tâm đến Du Lịch Hòa Bình. Chúng tôi sẽ liên lạc với bạn trong 24h tới. Nếu bạn cần bất kỳ sự trợ giúp, xin vui lòng gửi mail
			 <a href="mailto:ops@hoabinhtourist.com" style="text-decoration:none;color:#f58228" target="_blank">mice@hoabinhtourist.com</a> hoặc gọi điện đến <span style="color:#f58228">+8498 98 98 198.</span></p>
			</td>
		</tr>

		<tr>
			<td colspan="2" style="text-align:left; background: #1B2854;color: #fff; " >
			<p><strong>Thông tin đặt Tour</strong></p>
			</td>
		</tr>

		<tr>
			<td style="padding: 5px 0px 0px 20px;">
			<p style="color: #1B2854;">Tên đầy đủ:</p>
			</td>
			<td style="padding: 5px 0px 0px 20px;">
			<p><?=$this->name?></p>
			</td>
		</tr>
		<tr>
			<td style="padding: 5px 0px 0px 20px;">
			<p style="color: #1B2854;">Địa chỉ email:</p>
			</td>
			<td style="padding: 5px 0px 0px 20px;">
			<p><a href="mailto:<?=$this->email?>" target="_blank"><?=$this->email?></a></p>
			</td>
		</tr>
		<tr>
			<td style="padding: 5px 0px 0px 20px;">
			<p style="color: #1B2854;">Số điện thoại:</p>
			</td>
			<td style="padding: 5px 0px 0px 20px;">
			<p style="color: #1B2854;"><?=$this->mobi?></p>
			</td>
		</tr>
		<tr>
			<td style="padding: 5px 0px 0px 20px;">
			<p style="color: #1B2854;">Địa chỉ:</p>
			</td>
			<td style="padding: 5px 0px 0px 20px;">
			<p style="color: #1B2854;"><?=$this->address?></p>
			</td>
		</tr>
		<tr>
			<td style="padding: 5px 0px 0px 20px;">
			<p style="color: #1B2854;">Tên Tour:</p>
			</td>
			<td style="padding: 5px 0px 0px 20px;">
			<p><a href="http://timnhanh360.com/tour/<?=$this->ident?>.html" target="_blank"><?=$this->title?></a></p>
			</td>
		</tr>
		<tr>
			<td colspan="4" style="text-align:center; background: #1B2854;color: #fff;">
			<p><span style="font-size:14px">Thông tin liên Hệ:</span><br />
            CÔNG TY TỔ CHỨC SỰ KIỆN & DU LỊCH QT HÒA BÌNH
<br />
			Địa chỉ: 29 Đoàn Thị Điểm -Quốc Tử Giám - Đống Đa - Hà Nội  – Tel: <span>+84 98 98 98 198</span> - Fax: <span style="color: yellow">+84 91 33 11 911
</span> – Email: <a href="mailto:mice@hoabinhtourist.com" style="text-decoration:none;color:#00aeef" target="_blank">mice@hoabinhtourist.com</a></p>
			</td>
		</tr>
	</tbody>
</table>


</body>
</html>