
			<div class="top_title_holder add-bottom">
				
				<div class="top_title_border"></div>
				<div class="bottom_title_border"></div>
				
				<div class="container">
					
					<div class="nine columns">
						
						<h3>Ý kiến khách hàng</h3>	
						<p>Nhận xét của khách hàng</p>
					
					</div><!-- end nine -->
					
					<div class="seven columns">
					
						<ul>
							<li><a href="/">Trang chủ</a></li>
							<li>&#187;</li>
							<li><a href="#">Ý kiến khách hàng</a></li>
							
						</ul>
					
					</div><!-- end seven -->
				
				</div><!-- end container -->
			
			</div><!-- end .top_title_holder -->
			
			
			<div class="container">
			
					
				<div class="sixteen columns add-top add-bottom">
					
					<div class="title">
							
						<h2> <span class="bold"><?php echo $this->name; ?></span></h2>
						<div class="title_sep_container">
						<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
							
					</div><!-- end .title -->
				
				
				
					<div class="dropcap">
					<?php echo $this->description; ?>
						
					</div><!-- end .dropcap_v1 -->
				</div>
					
								
			</div><!-- end container -->
		