
			<div class="top_title_holder add-bottom">
				
				<div class="top_title_border"></div>
				<div class="bottom_title_border"></div>
				
				<div class="container">
					
					<div class="nine columns">
						
						<h3>Typography</h3>	
						<p>Typography styles</p>
					
					</div><!-- end nine -->
					
					<div class="seven columns">
					
						<ul>
							<li><a href="index.html">Home</a></li>
							<li>&#187;</li>
							<li><a href="#">Features</a></li>
							<li>&#187;</li>
							<li>Typography</li>
						</ul>
					
					</div><!-- end seven -->
				
				</div><!-- end container -->
			
			</div><!-- end .top_title_holder -->
			
			
			<div class="container">
			
					
				<div class="sixteen columns add-top add-bottom">
					
					<div class="title">
							
						<h2> <span class="bold">Dropcap</span></h2>
						<div class="title_sep_container">
						<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
							
					</div><!-- end .title -->
				
				
				
					<div class="dropcap_v1">
					
						<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis. Cumque
						nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis Cumque nihil
						impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis Cumque nihil impedit,
						quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. </p>
						
					</div><!-- end .dropcap_v1 -->
					
					<div class="dropcap_v2">
					
						<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis. Cumque
						nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis Cumque nihil
						impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis Cumque nihil impedit,
						quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. </p>
						
					</div><!-- end .dropcap_v2 -->
					
					<div class="dropcap_v3">
					
						<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis. Cumque
						nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis Cumque nihil
						impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis Cumque nihil impedit,
						quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. </p>
						
					</div><!-- end .dropcap_v3 -->
					
					<div class="dropcap_v4">
					
						<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis. Cumque
						nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis Cumque nihil
						impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis Cumque nihil impedit,
						quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. </p>
						
					</div><!-- end .dropcap_v4 -->
					
					
				</div><!-- end sixteen -->
				
				
				<div class="sixteen columns add-bottom">
				
					<div class="title">
							
						<h2> <span class="bold">Headings</span></h2>
						<div class="title_sep_container">
						<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
							
					</div><!-- end .title -->
				
				
					<h1>Heading 1</h1>
					<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut.</p>

					<h2>Heading 2</h2>
					<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut.</p>

					<h3>Heading 3</h3>
					<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut.</p>

					<h4>Heading 4</h4>
					<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut.</p>

					<h5>Heading 5</h5>
					<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut.</p>

					<h6>Heading 6</h6>
					<p>Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut.</p>
								
				</div><!-- end sixteen -->
				
				
				
				<div class="sixteen columns add-bottom">
				
					<div class="title">
							
						<h2> <span class="bold">Blockquote</span></h2>
						<div class="title_sep_container">
						<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
							
					</div><!-- end .title -->
					
					<blockquote class="bq">
						<p> "Cumque nihil impedit, quo minus id, quod maxime placeat, facere possimus, omnis voluptas assumenda est, 
						omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut." </p>
					</blockquote>
					
					
				</div><!-- end sixteen -->	
				
				
				
				<div class="sixteen columns">
				
					<div class="title">
							
						<h2> <span class="bold">Lists</span></h2>
						<div class="title_sep_container">
						<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
							
					</div><!-- end .title -->
					
					
					
					
					<div class="one-third column alpha add-bottom">
					
						<ul class="circle_list_2">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.circle_list_2 -->
										
					</div><!-- end .one-third -->
									
					<div class="one-third column add-bottom">
					
						<ul class="mark_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.mark_list -->
										
					</div><!-- end .one-third -->
									
					<div class="one-third column omega add-bottom">
					
						<ul class="minus_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.minus_list -->
										
					</div><!-- end .one-third -->
					
					
					
					
					<div class="one-third column alpha add-bottom">
					
						<ul class="plus_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.plus_list -->
										
					</div><!-- end .one-third -->
									
					<div class="one-third column add-bottom">
					
						<ul class="triangle_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.triangle_list -->
										
					</div><!-- end .one-third -->
									
					<div class="one-third column omega add-bottom">
					
						<ul class="arrow_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.arrow_list -->
										
					</div><!-- end .one-third -->
					
					
					
					
					<div class="one-third column alpha add-bottom">
					
						<ul class="arrow_list_thick">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.arrow_list_thick -->
										
					</div><!-- end .one-third -->
									
					<div class="one-third column add-bottom">
					
						<ul class="cart_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.cart_list -->
										
					</div><!-- end .one-third -->
									
					<div class="one-third column omega add-bottom">
					
						<ul class="star_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.star_list -->
										
					</div><!-- end .one-third -->
					
					
					
					<div class="one-third column alpha add-bottom">
					
						<ul class="heart_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.heart_list -->
										
					</div><!-- end .one-third -->
									
					<div class="one-third column add-bottom">
					
						<ul class="close_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.close_list -->
										
					</div><!-- end .one-third -->
					
					
					<div class="one-third column omega add-bottom">
					
						<ul class="circle_list">
						
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
							<li>Cumquesihil impedit, quo minus id,  quod maxime placea</li>
						
						</ul><!-- end ul.circle_list -->
										
					</div><!-- end .one-third -->
					
					
					
				</div><!-- end sixteen -->	
				
				
				
				
				<div class="sixteen columns add-bottom">
				
					<div class="title">
							
						<h2> <span class="bold">HTML</span> <span>Style</span></h2>
						<div class="title_sep_container">
						<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
							
					</div><!-- end .title -->
					
					
					<p><a href="#">This is link</a> , consectetur this <span class="oregano">nice font in case you need it for something special </span>is und serl sine, <u>underline style</u> this is <strong>strong style</strong> ut labore et <em>Emphasized style</em>
					dolore <del>Strikethrough style</del> magna aliqua. Ut enim ad minim veniam, nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in
					voluptate velit dolore eu fugiat nulla pariatur.</p>	
					
				</div><!-- end sixteen -->


				<div class="sixteen columns add-bottom">
				
					<div class="title">
							
						<h2> <span class="bold">Tables</span></h2>
						<div class="title_sep_container">
						<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
							
					</div><!-- end .title -->
					
					
					<table class="table_v1 add-bottom">
					
						<tr>
							<td>#</td>
							<td>First Name</td>
							<td>Last Name</td>
							<td>Username</td>
						</tr>
						
						
						<tr>
							<td>1</td>
							<td>John</td>
							<td>Doe</td>
							<td>john12</td>
						</tr>
						
						
						<tr>
							<td>2</td>
							<td>Jane</td>
							<td>Doe</td>
							<td>jahn12</td>
						</tr>
						
						<tr>
							<td>3</td>
							<td>Julia</td>
							<td>Doe</td>
							<td>julia22</td>
						</tr>
					
					
					</table><!-- end .table_v1 -->
					
					
					
					<table class="table_v2 add-top add-bottom">
					
						<tr>
							<td>#</td>
							<td>First Name</td>
							<td>Last Name</td>
							<td>Username</td>
						</tr>
						
						
						<tr>
							<td>1</td>
							<td>John</td>
							<td>Doe</td>
							<td>john12</td>
						</tr>
						
						
						<tr>
							<td>2</td>
							<td>Jane</td>
							<td>Doe</td>
							<td>jahn12</td>
						</tr>
						
						<tr>
							<td>3</td>
							<td>Julia</td>
							<td>Doe</td>
							<td>julia22</td>
						</tr>
					
					
					</table><!-- end .table_v2 -->
					
					
					
					<table class="table_v3 add-top add-bottom">
					
						<tr>
							<td>#</td>
							<td>First Name</td>
							<td>Last Name</td>
							<td>Username</td>
						</tr>
						
						
						<tr>
							<td>1</td>
							<td>John</td>
							<td>Doe</td>
							<td>john12</td>
						</tr>
						
						
						<tr>
							<td>2</td>
							<td>Jane</td>
							<td>Doe</td>
							<td>jahn12</td>
						</tr>
						
						<tr>
							<td>3</td>
							<td>Julia</td>
							<td>Doe</td>
							<td>julia22</td>
						</tr>
					
					
					</table><!-- end .table_v3 -->
					
					
					
				</div><!-- end sixteen -->
				
				
				<div class="sixteen columns add-bottom">
				
					<div class="title">
							
						<h2> <span class="bold">Columns</span></h2>
						<div class="title_sep_container">
						<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
							
					</div><!-- end .title -->
				</div><!-- end sixteen -->		
					
					
					<div class="eight columns add-bottom">
						<h5>1/2</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-half -->

					<div class="eight columns add-bottom">
						<h5>1/2</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-half -->

					<div class="one-third column add-bottom">
						<h5>1/3</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->

					<div class="one-third column add-bottom">
						<h5>1/3</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->

					<div class="one-third column add-bottom">
						<h5>1/3</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->
				
					
					<div class="one-third column add-bottom">
						<h5>1/3</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->
					
					
					<div class="two-thirds  column omega add-bottom">
						<h5>2/3</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates.Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptatesNique porro quisq ptates ptates est qui dolorem ipsumquia do sit</p>
					</div><!-- end one-third -->
					
					
					

					<div class="four columns add-bottom">
						<h5>1/4</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->

					<div class="four columns add-bottom">
						<h5>1/4</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->

					<div class="four columns add-bottom">
						<h5>1/4</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->

					<div class="four columns add-bottom">
						<h5>1/4</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->

					<div class="four columns add-bottom">
						<h5>1/4</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->

					<div class="twelve columns add-bottom">
						<h5>3/4</h5>

						<p>Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates Masagni dolores eoquie voluptates ptates ptates msequi nesciunt. Nique porro quisq ptates ptates est qui dolorem ipsumquia do sit ptates ptates consectet, adipisci unumquam eius.ptates
						ptates</p>
					</div><!-- end one-third -->	
					
								
			</div><!-- end container -->
		