<tr>
    <td class='links'>
      <a href='/<?=ADMIN?>/menuitem/hmove/direction/up/id/<?php echo $this->id;?>'>
          <i class="icon-arrow-up bigger-130 blue"></i></a> |
        <a href='/<?=ADMIN?>/menuitem/hmove/direction/down/id/<?php echo $this->id;?>'>
          <i class="icon-arrow-down bigger-130 blue"></i></a> |
         <i class="icon-camera bigger-130 orange"></i></a> 
          
       <div id="queue<?php echo $this->id;?>"></div>

		<input id="file_upload<?php echo $this->id;?>" name="file_upload<?php echo $this->id;?>" type="file" multiple="true">		
		 
</td>
	<td>
	<div id="preview<?php echo $this->id;?>"><img id="image<?php echo $this->id;?>" src="/public/images/menuitems/<?=$this->image;?>" width= "200px" /></div>
	
	</td>
    <td><?php echo $this->label ?></td>
    <td><?php echo $this->Hpos ?></td>
</tr>

<?php $timestamp = time();?>
<script type="text/javascript">

$(document).ready(function() { 
 //alert(33434);
 $('#file_upload' + <?php echo $this->id;?>).uploadifive({
			    'fileType'     : 'image',
			    'queueSizeLimit' : 1,
				'multi'			   : false,
				'auto'             : true,
				'fileSizeLimit' : 3500,
				'formData'         : {
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>',
				'catID' : '<?=$this->id?>',
				                     },
				'queueID'          : 'queue' + <?php echo $this->id;?>,
				'uploadScript'     : '/admin/menuitem/upload/',
				'onError'      : function(errorType) {
				switch(errorType) {
				case '404_FILE_NOT_FOUND':
					alert('Không tìm thấy tệp tin!');
					break;
				case 'FORBIDDEN_FILE_TYPE':
					alert('Chỉ hỗ trợ định dạng ảnh');
					break;
				case 'FILE_SIZE_LIMIT_EXCEEDED':
				alert('Vượt quá dung lượng cho phép');
				break;
				case 'QUEUE_LIMIT_EXCEEDED':
				alert('Xin vui lòng xóa file ảnh hiện tại trước khi chọn lại file khác!');
				//j('.stdelete').trigger('click');
				//j('#file_upload').uploadifive('clearQueue').trigger('click');
				break;
				default:
				alert(errorType);
				 //alert('Có lỗi, xin thử lại');
				break;
				   }
                } ,
                'onSelect' : function(queue) {
             
     
				} ,
                 'onCancel'     : function() {
           // alert('The file ' + file.name + ' was cancelled!');
                 } ,
             'onProgress': function(file, e) {
				 //  console.log(e);
            
			
				 },
      
        
                'onUpload'     : function(filesToUpload) {
          
					} ,
			'onUploadComplete' : function(file, data, response) {
				
				console.log(data);
				var obj = jQuery.parseJSON(data);
		        $('#image' + <?php echo $this->id;?>).hide();
				$('#preview'+ <?php echo $this->id;?>).append('<img src="/public/images/menuitems/'+ obj.tenfile +'" width="200px">');
				}
			});
	
	
	
}); 

</script>