<tr>
	<td style="text-align: center;vertical-align: middle;" class="center">
			<label>
			<input type="checkbox" class="ace" />
			<span class="lbl"></span>
			</label>
	</td>
    
    <td width="25%"><b>
	<a class="green" href='/<?=ADMIN?>/events/edit/id/<?php echo $this->id;?>'>
	<?php echo $this->eventname; ?>
	</a>
	</b></td>
    <td><?php echo $this->begindate; ?></td>
    <td><?php echo $this->end_date; ?></td>
    <td><?php echo $this->venue; ?></td>
	<td style="text-align: center;vertical-align: middle;">
	<a href="/<?=ADMIN?>/events/edit/id/<?php echo $this->id;?>"><i class="fa fa-cog" title="Sửa nội dung này" aria-hidden="true"></i> Sửa</a>
	<a onclick="return confirm('Bạn có thật sự muốn xóa?');"  href="/<?=ADMIN?>/events/delete/id/<?php echo $this->id;?>" ><i class="fa fa-trash-o" aria-hidden="true"></i> Xóa</a>
	</td>
</tr>
