<tr>
	<td class="center">
			<label>
			<input type="checkbox" class="ace" />
			<span class="lbl"></span>
			</label>
	</td>
    
    <td width="25%"><b>
	<a class="green" target="_blank" href='/<?=ADMIN?>/invitee/edit/id/<?php echo $this->id;?>'>
	<?php echo $this->fullname; ?>
	</a>
	</b></td>
    <td><?php echo $this->address; ?></td>
    <td><?php echo $this->phone; ?></td>
    <td><?php echo $this->email; ?></td>
    <td><?php
        echo $this->id;
        ?></td>
	<td style="text-align: center;vertical-align: middle;">

        <a title="Xem" href="javascript:void(0);"><i style="font-size: large;" class="fa fa-eye" aria-hidden="true"></i></a>
	<a title="Sửa" href="/<?=ADMIN?>/invitee/edit/id/<?php echo $this->id;?>"><i style="font-size: large;margin: 0 5px;" class="fa fa-pencil" aria-hidden="true"></i></a>
	<a title="Xóa" onclick="return confirm('Bạn muốn xóa?');"  href="/<?=ADMIN?>/invitee/delete/id/<?php echo $this->id;?>" ><i style="font-size: large;color: red;" class="fa fa-times" aria-hidden="true"></i></a>
	</td>
</tr>
