<tr>
	<td class="center">
			<label>
			<input type="checkbox" class="ace" />
			<span class="lbl"></span>
			</label>
	</td>
    
    <td width="25%"><b>
	<a class="green" target="_blank" href='/<?=ADMIN?>/invitee/edit/id/<?php echo $this->id;?>'>
	<?php echo $this->fullname; ?>
	</a>
	</b></td>
    <td><?php echo $this->address; ?></td>
    <td><?php echo $this->phone; ?></td>
    <td><?php echo $this->email; ?></td>
    <td><?php echo $this->checkedIn; ?></td>
	<td>
	<a href="/<?=ADMIN?>/invitee/edit/id/<?php echo $this->id;?>"><img src="/public/images/icon_edit.gif" alt="Sửa" title="Sửa nội dung này"></a>
	<a onclick="return confirm('Bạn muốn xóa?');"  href="/<?=ADMIN?>/invitee/delete/id/<?php echo $this->id;?>" ><img title="Xóa" alt="Xóa" src="/public/images/icon_delete.gif"></a>
	</td>
</tr>
