<tr>
    <td class='links'>
        <a href='/<?=ADMIN?>/menu/edit/id/<?php echo $this->id;?>'><i class="icon-pencil bigger-130 green"></i></a> |
        <a href='/<?=ADMIN?>/menuitem/index/menu/<?php echo $this->id;?>'>
            <i class="icon-th-list bigger-130 blue"></i> Quản lý Menu Items</a> |
        <a href='/<?=ADMIN?>/menu/delete/id/<?php echo $this->id;?>'><i class="icon-trash bigger-130 red"></i></a>
        
</td>
    <td><?php echo $this->name ?></td>
</tr>




															