<dt id="parentID-label">
<label class="required" for="parentID">Hạn tuyển dụng:</label>
</dt>
<?php
	$date = date('d/m/Y',time());
	$options = $this->element->getDecorator('ViewScript')->getOptions();
	$optionString = $options['List'];	
	if(!empty($optionString)){
		
		$date = date('d/m/Y', $optionString);
	} else{
		$date = '';
	}
	
	?>
<dd id="parentID-element">
	<div class="row">
		<div class="col-md-8 col-sm-8">
			<div class="input-group">
				<input id="id-date-picker-1" class="form-control date-picker" name="expired" type="text" data-date-format="dd/mm/yyyy" placeholder="Chọn thời gian" value="<?=$date?>">
				<span class="input-group-addon">
					<i class="fa fa-calendar bigger-110"></i>
				</span>
			</div>
		</div>
	</div>
</dd>