<?php 
	$img = '';
	$pid = '';
	$options = $this->element->getDecorator('ViewScript')->getOptions();
	$optionString = '';
	if(!empty($options)){
		if($options['List'] != ''){
		$optionString = '<img src= "'.$options['List'].'" />';	
		}else{
		$optionString ='';	
		}
		$pid = $options['pid']; 
	}   
	
	 ?>
<dt id="cover-label">
<label class="required" for="cover">Up ảnh bìa:</label>
</dt>	
<dd id="cover-element">	
	 <div class="slim" data-label="Thả ảnh bìa vào đây" style="width:200px;" data-will-remove="imageWillBeRemoved" <?php echo ($pid != '')?' data-did-remove="imageRemoved"':''; ?>>
        <input id="myCropper" type="file" name="slim[]"  <?php echo ($optionString == null)?' required':''; ?> />
        <?php echo $optionString; ?>
    </div>
</dd>  
<br/>
   <?php if($pid != null){ ?>
<script type="text/javascript">
	var pid = '<?php echo $pid; ?>';
</script>   
   <?php } ?>
<script type="text/javascript">
function imageWillBeRemoved(data, remove) {
    if (window.confirm("Bạn muốn xóa ảnh bìa?")) {
        remove();
    }
}

function imageRemoved(data)
{
	
	 	
  dataString = 'name=' + data.input.name + '&pid=' + pid;
	$.ajax({
            type: "POST",
            url: "/admin/new/delcover",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			
			  $('.slim').removeAttr('data-did-remove');
            }
        });
		
	 return false;
  

}
</script>