<tr>
	<td class="center">
			<label>
			<input type="checkbox" class="ace" />
		<span class="lbl"></span>
			</label>
	</td>
    <td width="6%">
        <a class="green" href='/<?=ADMIN?>/blog/edit/id/<?php echo $this->id;?>'><i class="icon-pencil bigger-130"></i></a> | 
        <a class="red" href='/<?=ADMIN?>/blog/delete/id/<?php echo $this->id;?>'><i class="icon-trash bigger-130"></i></a>
    </td>
    <td><?php echo $this->name ?></td>
    <td><?php echo $this->description ?></td>
</tr>

