		   			   			   			   			   			   			   	    	   			   			   		 	 <ul class="nav navbar-nav nav-first topmenu-header">
     <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">Giới thiệu <span class="caret"></span></a>
     	<ul class="dropdown-menu">
	     <li><a href="/ve-chung-toi">Về chúng tôi</a></li>
		 <li><a href="/nang-luc-tai-chinh">Năng lực tài chính</a></li>
		 <li><a href="/tam-nhin-su-menh">Tầm nhìn sứ mệnh, giá trị cốt lõi</a></li>
		 <li><a href="/dau-an-phat-trien">Những dấu ấn của sự phát triển</a></li>
		 <li><a href="/doi-ngu-lanh-dao">Đội ngũ lãnh đạo</a></li>
	 	</ul>
	 </li>
     <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/about-us/index">Lĩnh vực hoạt động <span class="caret"></span></a>
     	<ul class="dropdown-menu">
	     <li><a href="/linh-vuc/to-chuc-hoi-nghi-hoi-thao">Tổ chức hội nghị, hội thảo</a></li>
		 <li><a href="/linh-vuc/to-chuc-su-kien">Tổ chức sự kiện</a></li>
		 <li><a href="/linh-vuc/giai-phap-quang-cao-truyen-thong">Giải pháp Quảng cáo, Truyền thông</a></li>
		 <li><a href="/linh-vuc/to-chuc-tour-teambuilding">Tổ chức Tour, Team building</a></li>
		 <li><a href="/linh-vuc/cung-cap-thiet-bi-su-kien">Cung cấp Thiết bị sự kiện</a></li>
	 	</ul>
	 </li>
	 	<li class="dropdown">
	 <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/services">Tin tức <span class="caret"></span></a>
	   <ul class="dropdown-menu">
		   <li><a href="/tin-tuc/tin-khuyen-mai">Tin khuyến mại</a></li>
		   <li><a href="/tin-tuc/goc-bao-chi">Góc báo chí</a></li>
		  <!-- <li><a href="/tin-tuc/tin-noi-bo">Bản tin nội bộ</a></li>-->
		   <li><a href="/tin-tuc/hoi-nghi-su-kien-tieu-bieu">Hội nghị sự kiện tiêu biểu</a></li>
		   <li><a href="/tin-tuc/tin-tuc-mice">Tin tức MICE</a></li>
           <li><a href="/tin-tuc/cam-nang">Cẩm nang</a></li>
		</ul>
		</li>
		<li><a href="/ban-tin">Bản tin</a></li>
  
		<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/gallery-index">Thư viện <span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><a href="/gallery">Gallery</a></li>
				<li><a href="/video">Video</a></li>
			</ul>
		</li>
				
        <li><a target="_blank" href="http://membershipcard.hoabinh-group.com">Hội viên thân thiết</a></li> 
		<li><a href="/tuyen-dung">Tuyển dụng</a></li>
        <li><a href="/lien-he">Liên hệ</a></li>
		   </ul>			 			 			 			 			 			 			 			 		 			 			 			 			 			 