 <ul class="nav navbar-nav nav-first">
     <li><a href="/">Giới thiệu</a></li>
     <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/about-us/index">Lĩnh vực hoạt động <span class="caret"></span></a>
     	<ul class="dropdown-menu">
	     <li><a href="/about-us">About us</a></li>
		 <li><a href="/our-core-values">Our Core Values</a></li>
		 <li><a href="/mission-vision">Mission - Vision</a></li>
		 <li><a href="/achievements">Achievements</a></li>
	 	</ul>
	 </li>
	 <li class="dropdown">
	 <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/services">Tin tức <span class="caret"></span></a>
	   <ul class="dropdown-menu">
		   <li><a href="/tin-tuc/tin-khuyen-mai">Tin khuyến mại</a></li>
		   <li><a href="/tin-tuc/goc-bao-chi">Góc báo chí</a></li>
		   <li><a href="/tin-tuc/tin-noi-bo">Bản tin nội bộ</a></li>
		   <li><a href="/tin-tuc/hoi-nghi-su-kien-tieu-bieu">Hội nghị sự kiện tiêu biểu</a></li>
		   <li><a href="/tin-tuc/tin-tuc-mice">Tin tức MICE</a></li>
		</ul>
		</li>
		<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/gallery-index">Tuyển dụng <span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><a href="/gallery">Gallery</a></li>
				<li><a href="/video">Video</a></li>
			</ul>
		</li>
		
		<li class="logo" id="logo"><a class="navbar-brand" href="#"> <img width="220" src="<?=TEMPLATE_URL?>/default/img/logo-01.png" /></a></li>
		
		<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/gallery-index">Thư viện <span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><a href="/gallery">Gallery</a></li>
				<li><a href="/video">Video</a></li>
			</ul>
		</li>
		<li><a href="/clients-testimonials">Liên hệ</a></li>
		<li><a href="/contact">Hội viên thân thiết</a></li>  
		<li><a href="#"><i class="fa fa-search" aria-hidden="true"></i>&nbsp;Tìm kiếm</a></li> 

   </ul>
   
