<link rel="stylesheet" type="text/css" href="<?=TEMPLATE_URL?>/uploadifive/uploadifive.css">

<script src="<?=TEMPLATE_URL?>/uploadifive/jquery.uploadifive.min.js" type="text/javascript"></script>
<style>
	.uploadifive-button{
		background: transparent;
		width: 50px !important;
		border: 0px;
		position: relative !important;
		/*
		top:80px !important; 
		left: 72px !important;
	*/
	   margin-top: -336px;
	   margin-left: 50px;
	   opacity: 0;
		cursor: pointer !important;
	}
</style>
<div class="row">
<div class="col-sm-8">
<div class="widget-box transparent">
    <div class="widget-header widget-header-flat">
    	<h4 class="lighter">
    		<i class="icon-star orange"></i>
			Danh mục Category Home
    	</h4>

    	
    </div>


<?php if($this->result != null) { ?>
<div class="widget-body">
	<div class="widget-main no-padding">
	    <table class="table table-bordered table-striped">
	    	<thead class="thin-border-bottom">
	    		<tr>
	    			<th>
	    				<i class="icon-caret-right blue"></i>
	    				Thao tác
	    			</th>
	    			<th>
			    	<i class="icon-caret-right blue"></i>
			    			Image
			    	</th>

					<th>
			    	<i class="icon-caret-right blue"></i>
			    			Nhãn
			    	</th>
			    	<th>
			    	<i class="icon-caret-right blue"></i>
			    			Thứ tự
			    	</th>
			    </tr>
		  </thead>
		  <tbody>
  <?php echo $this->partialLoop('_cathome-item-row.phtml', $this->result); ?>
		  </tbody>
	    			</table>
	    		</div><!-- /widget-main -->
	    	</div><!-- /widget-body -->
	    </div><!-- /widget-box -->
	</div>
</div>

<?php }else{?>
<p>Bạn chưa có cat trang chủ.</p>
<?php }?>

    
<?php //ECHO $_SERVER['DOCUMENT_ROOT'] ?>