<link rel="stylesheet" type="text/css" href="<?=TEMPLATE_URL?>/uploadifive/uploadifive.css">

<script src="<?=TEMPLATE_URL?>/uploadifive/jquery.uploadifive.min.js" type="text/javascript"></script>
<style>
#photoUpload{

}
#photoUpload ul li{
	list-style-type: none;
	margin-bottom: 20px;
}
#photoUpload ul li img{
	float: left;
}
</style>

<h1> Thêm ảnh cho menu <?=$this->name?></h1>

	<div id="queue"></div>

		<input id="file_upload" name="file_upload" type="file" multiple="true">		
		
	<div id="preview"></div>	
	
	<br/>
	
	<div class="row">

 <div class="col-sm-4 widget-container-col">
   <div class="widget-box">
   ...
   </div>
 </div>

 <div class="col-sm-4 widget-container-col">
   <div class="widget-box">
   ...
   </div>
 </div>
 
  <div class="col-sm-4 widget-container-col">
   <div class="widget-box">
   ...
   </div>
 </div>

</div>

<?php
	
	$db = Zend_Db_Table::getDefaultAdapter();
	$select = "SELECT s.id as id,s.caption, s.url, i.imageId, i.full, i.isDefault FROM `productImage` as i inner join menu_item_images as s on s.id_product_image = i.imageId WHERE s.id_menu_item = ".$this->id;
	$result = $db->fetchAll($select);


	$count = count($result);
	?>	
	
	<div id="photoUpload">
	  	   <ul>
	  	  <?	if ($count > 0){
		  	  foreach ($result as $key=>$val):  ?>
	  		
	  		<li id="item_<?=$val['imageId']?>">
	  	<div class="row">
	  	<div class="col-xs-8">
		  	<div class="row">
	  		<img src="/public/images/backgrounds/<?=$val['full']?>" width= "330px" />
		  	</div>
		  	<div class="row">
			  	
	  		<textarea name="caption" cols="41" id="caption_<?=$val['id']?>" class="caption_image"><?=$val['caption']?></textarea>
		  	</div>
		  	
		  	<div class="row">
			  	
	  		<input name="url_image" class="url_image" id="url_<?=$val['id']?>" value="<?=$val['url']?>"></textarea>
		  	</div>
	  	</div>
	  	<div class="col-xs-4">	
	  		 <div class="col-sm-6"><div class="radio"> <label><input type="radio" name="default" class='ace CheckBoxClass' id="radio_<?=$val['imageId']?>" value="no" <?php echo ($val['isDefault'] == 'Yes')?' checked':''; ?>><span class="lbl"> set default </label></div></span></div>
	  		 
	  		<div class="col-sm-4" style="margin-top:8px"> | 
	  		 <span class="stdelete" onclick="deleteItem(this)" data="del_<?=$val['imageId']?>"> &nbsp;Xóa</span>
	  		 
	  		</div>
	  	</div>
	  		</div>	
	  		</li>
	  	<div style="clear:both"></div>	
	  	<?	endforeach;
		  	}
	  	?>
	  	</ul>
	  		</div>
	
	
<?php $timestamp = time();?>
<script type="text/javascript">

$(document).ready(function() { 
 //alert(33434);
 $('#file_upload').uploadifive({
			    'fileType'     : 'image',
			    'queueSizeLimit' : 50,
				'multi'			   : true,
				'auto'             : true,
				'fileSizeLimit' : 3500,
				'formData'         : {
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>',
				'productID' : '<?=$this->id?>',
				                     },
				'queueID'          : 'queue',
				'uploadScript'     : '/admin/menuitem/uploadimage/',
				'onError'      : function(errorType) {
				switch(errorType) {
				case '404_FILE_NOT_FOUND':
					alert('Không tìm thấy tệp tin!');
					break;
				case 'FORBIDDEN_FILE_TYPE':
					alert('Chỉ hỗ trợ định dạng ảnh');
					break;
				case 'FILE_SIZE_LIMIT_EXCEEDED':
				alert('Vượt quá dung lượng cho phép');
				break;
				case 'QUEUE_LIMIT_EXCEEDED':
				alert('Xin vui lòng xóa file ảnh hiện tại trước khi chọn lại file khác!');
				//j('.stdelete').trigger('click');
				//j('#file_upload').uploadifive('clearQueue').trigger('click');
				break;
				default:
				alert(errorType);
				alert('Có lỗi, xin thử lại');
				break;
				   }
                } ,
                'onSelect' : function(queue) {
             
     
				} ,
                 'onCancel'     : function() {
           // alert('The file ' + file.name + ' was cancelled!');
                 } ,
             'onProgress': function(file, e) {
				 //  console.log(e);
            
			
				 },
      
        
                'onUpload'     : function(filesToUpload) {
          
					} ,
			'onUploadComplete' : function(file, data, response) {
				
				console.log(data);
				var obj = jQuery.parseJSON(data);
		
				$('#photoUpload ul').append('<li><div class="row"><div class="col-xs-8"><img src="/public/images/backgrounds/'+ obj.tenfile +'" width="330px"></div><div class="col-xs-4"><div class="col-sm-6"><div class="radio"><label><input id="radio_' + obj.idfile+'" class="ace CheckBoxClass" type="radio" value="no" name="default"><span class="lbl"> set default </span></label></div></div><div class="col-sm-4" style="margin-top:8px"> | <span class="stdelete" data="del" onclick="deleteItem(this)">  Xóa</span></div></div></div></li><div style="clear:both"></div>');
				}
			});
	
	
	
}); 

function deleteItem(o){
		//alert($(o).attr('data'));
		var data =  $(o).attr('data');
		var item = data.split('_')[1];
		//alert(item);
		var productID = '<?=$this->id?>';
		$('#item_'+item).fadeOut();
		var dataString = 'itemDel=' + item + '&pID=' + productID;
		 $.ajax({
            type: "POST",
            url: "/admin/menuitem/delitem",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
	}
	
	//$('#radio_')
	
	//var input = $('input:radio[name="default"]');
	$(".CheckBoxClass").change(function(){
	var var_name = $(this).val(); 
	var itemId = $(this).attr('id');
	var new_itemID = itemId.split('_')[1];
	var productID = '<?=$this->id?>';
	//alert(new_itemID);
  dataString = 'itemDef=' + new_itemID + '&pID=' + productID;
	$.ajax({
            type: "POST",
            url: "/admin/menuitem/default",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
  
  	});
  	
  	$('.caption_image').blur(function(e){
	  	var id_caption = e.target.id.split('_');
	  	 var txtAval=$(this).val();
	  	 
	  	dataString = 'item=' + id_caption[1] + '&caption=' + txtAval;
	$.ajax({
            type: "POST",
            url: "/admin/menuitem/caption",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
	  	
  	});
  	
  	
  	$('.url_image').blur(function(e){
	  	var id_url = e.target.id.split('_');
	  	 var txtAval=$(this).val();
	  	 
	  	dataString = 'item=' + id_url[1] + '&url=' + txtAval;
	$.ajax({
            type: "POST",
            url: "/admin/menuitem/url",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
	  	
  	});
</script>