<div class="row">
<div class="col-sm-8">
<div class="widget-box transparent">
    <div class="widget-header widget-header-flat">
    	<h4 class="lighter">
    		<i class="icon-star orange"></i>
			Danh mục Menu Items
    	</h4>

    	
    </div>
<?php

	echo $this->select('menu',null,$this->items->toArray());
?>

<?php if($this->items != null) { ?>
<div class="widget-body">
	<div class="widget-main no-padding">
	    <table class="table table-bordered table-striped">
	    	<thead class="thin-border-bottom">
	    		<tr>
	    			<th>
	    				<i class="icon-caret-right blue"></i>
	    				Thao tác
	    			</th>

					<th>
			    	<i class="icon-caret-right blue"></i>
			    			Nhãn
			    	</th>
			    	<th>
			    	
			    			Page
			    	</th>
			    	<th>
			    	<i class="icon-caret-right blue"></i>
			    			Đường dẫn
			    	</th>
			    	<th>
			    	<i class="icon-caret-right blue"></i>
			    			Hiển trị ở trang chủ
			    	</th>
			    </tr>
		  </thead>
		  <tbody>
  <?php echo $this->partialLoop('_menu-item-row.phtml', $this->items); ?>
		  </tbody>
	    			</table>
	    		</div><!-- /widget-main -->
	    	</div><!-- /widget-body -->
	    </div><!-- /widget-box -->
	</div>
</div>

<?php }else{?>
<p>Bạn chưa có menu.</p>
<?php }?>

<a class="btn btn-info btn-sm" href='/<?=ADMIN?>/menuitem/add/menu/<?php echo $this->menu->id ?>'>Thêm menu mới</a>
<a class="btn btn-info btn-sm" href='/<?=ADMIN?>/menuitem/homecat'>Quản lý Category Home</a>
    
<?php //ECHO $_SERVER['DOCUMENT_ROOT'] ?>