<script src="/public/scripts/ckeditor/ckeditor.js" type="text/javascript"></script>
<script src="/public/js/jquery.simplyCountable.js" type="text/javascript"></script>
<h2>Cập nhật Menu Item</h2>
<p>Menu hiện tại: <?php echo $this->menu->name;?></p>

<style>
	#myTab{
		height: 34px;
	}
</style>

<div class="tabbable">
											<ul class="nav nav-tabs" id="myTab">
												<li class="active">
													<a data-toggle="tab" href="#home">
														<i class="green ace-icon fa fa-home bigger-120"></i>
														Cập nhật 
													</a>
												</li>

												<li>
													<a data-toggle="tab" href="#seo">
														SEO
														<span class="badge badge-danger"></span>
													</a>
												</li>
												

												
											</ul>

											<div class="tab-content">
												<div id="home" class="tab-pane fade in active">
	<?php echo $this->form; ?>
<?php echo $this->Ckeditor('description',150,550); ?> 
<div style="clear:both"></div>
												</div>

												<div id="seo" class="tab-pane fade">
		<form id="seo-form" method="post" action="/admin/menuitem/seo">		 									
		<dl class="zend_form">
			<input id="id" type="hidden" value="<?=$this->id?>" name="id">
			<input id="id_object" type="hidden" value="<?=$this->id_menuitem?>" name="id_object">
<dt id="seo_title-label">
         
	<label class="required" for="title">Title:</label>
</dt>

<dd id="seo_title-element">
<input id="seo_title" type="text" size="40" value="<?=$this->title?>" name="seo_title">
<p>Giới hạn <span id= "counter_seo_title"></span> kí tự</p>
</dd>


<dt id="seo_keyword-label">
	<label class="required" for="title">Keyword:</label>
</dt>

<dd id="seo_keyword-element">
<input id="seo_keyword" type="text" size="74" value="<?=$this->keyword?>" name="seo_keyword">
</dd>

<dt id="seo_description-label">
	<label class="required" for="title">Description:</label>
</dt>

<dd id="seo_description-element">
<textarea id="seo_description" name="seo_description" rows="5" cols="40"><?=$this->description?></textarea>
<p>Giới hạn <span id= "counter_seo_description"></span> kí tự</p>
</dd>


<dt id="submit-label"> </dt>
<dd id="submit-element">
<input id="submit-seo" class="btn btn-info" type="submit" value="Save" name="submit-seo">
</dd>
		</dl>
		</form>
												</div>

											
											</div>
										</div>
		 <script>
 var frm = $('#seo-form');
    frm.submit(function (ev) {
	     ev.preventDefault();
	     console.log(frm.serialize());
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                alert('Cập nhật seo thành công!');

            }
        });

       
    });	
    
      $('#seo_title').simplyCountable({
    counter: '#counter_seo_title',
    countable: 'characters',
    maxCount: 60,
    strictMax: true,
    countDirection: 'down',
    safeClass: 'safe',
    overClass: 'over',
    thousandSeparator: ','
});
    
    $('#seo_description').simplyCountable({
    counter: '#counter_seo_description',
    countable: 'characters',
    maxCount: 156,
    strictMax: true,
    countDirection: 'down',
    safeClass: 'safe',
    overClass: 'over',
    thousandSeparator: ','
});
</script>								
										
										