	<div class="row">
		

									<div class="col-xs-12">
                                        <h3 class="header smaller lighter blue"><a href="/<?=ADMIN?>/position">Khai báo danh mục</a> » <a href="/<?=ADMIN?>/position">Danh mục chức vụ</a></h3>
									

										<div class="table-responsive">
											<table id="table_events" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														<th style="width: 10%;text-align: center;vertical-align: middle;"><label>
                                                                <input type="checkbox" class="ace" />
                                                                <span class="lbl"></span>
                                                            </label></th>
														<th>Tên chức vụ</th>
                                                        <th>Ghi chú</th>
                                                        <th style="width: 10%;text-align: center;vertical-align: middle;">Thứ tự</th>
														<th style="width: 10%;text-align: center;vertical-align: middle;">Thao tác</th>
													</tr>
												</thead>

												<tbody>
				<?php echo $this->partialLoop('_position-row.phtml', $this->products); ?>
												</tbody>
											</table>
											
										</div>
								
<br/>
<a class="btn btn-info btn-sm" href="/admin/position/create">Thêm mới</a>
										
									</div>
								</div>
	<br/>
	
	
						
<script type="text/javascript">
			jQuery(function($) {
				var oTable1 = $('#table_events').dataTable( {
				"aoColumns": [
			      { "bSortable": false },
			      null, null
				] } );
				
				
			})
		</script>									
