<div id="intro">
		    	<div class="row">
			    	<div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
			    		<div class="col-md-5 title">
				    		<div data-aos="fade-right" data-aos-duration="2500">
				    		<span class="website"><span class="web-text"><img class="img-responsive" height="45" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span></span>
				    		<span style="height: 6px;width: 5px;display: block;">&nbsp;</span>
				    		<span class="des">Tầm nhìn & sứ mệnh</span>
				    		</div>
				    		</div>
						<div class="col-md-7 description" data-aos="fade-left" data-aos-duration="2500">Với phương châm “Chất lượng làm nên danh tiếng”, trải qua hơn 10 năm xây dựng và trưởng thành,​ tập đoàn ​HoaBinhGroup (Convention – Events – Travel) đã khẳng định uy tín của mình là một trong những tập đoàn hàng đầu trong lĩnh vực tổ chức Hội nghị, hội thảo, sự kiện và du lịch tại Việt Nam...
					  <span class="more">Xem tiếp >></span>		
						</div>
			        </div>
		    	</div>
	    	</div>
	    	<div class="row sv">
	    		<div id="service-tabs" data-aos="fade-up" data-aos-duration="3500">
		    	<div class="col-md-10 col-md-offset-1">
		    		<div class="title-louis center animated flipInX">
		    		<span class="web-text"><img height="30" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span> cung cấp các dịch vụ
					</div><!-- .title-louis-->
					<div class="content-louis">
						
						<div class="row">
		                   
                                   <div class="service">
                                    <ul id='services_tab' class="nav nav-tabs" role="tablist">
                                        <li role="presentation" class="active"><a href="#home" aria-controls="home" role="tab" data-toggle="tab">Tổ chức sự kiện, hội nghị</a></li>
                                        <li role="presentation"><a href="#travels" aria-controls="travels" role="tab" data-toggle="tab">Tổ chức Tour du lịch</a></li>
                                        <li role="presentation"><a href="#medias" aria-controls="medias" role="tab" data-toggle="tab">Giải pháp quảng cáo truyền thông</a></li>
                                        <li role="presentation"><a href="#equips" aria-controls="equips" role="tab" data-toggle="tab">Cung cấp thiết bị sự kiện</a></li>
                                          <li role="presentation"><a href="#others" aria-controls="others" role="tab" data-toggle="tab">Các dịch vụ khác</a></li>
                                    </ul>

                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane active" id="home">
	            <div class="hidden-sm">
	          <img src="<?=TEMPLATE_URL?>/default/img/services/map-sv-01.png" />     
	           <div id="hbg-center" data-aos="fade-left" data-aos-duration="2500"><img width="200" height="200" src="<?=TEMPLATE_URL?>/default/img/services/su%20kien.jpg" /> </div>        
	           <div id="hbg2" data-aos="fade-left" data-aos-duration="3500"><img width="120" height="120" src="<?=TEMPLATE_URL?>/default/img/services/cong-ty-to-chuc-su-kien-to-chuc-galadiner-tiec-tra-teabreak-buffet-5.jpg" /> </div> 
	           <div id="hbg3" data-aos="fade-right" data-aos-duration="2500"><img width="110" height="110" src="<?=TEMPLATE_URL?>/default/img/services/nhadatgiaodich_abc_xyx_3.20160307133241-6184.jpg" /> </div>  
	             <div id="hbg4" data-aos="fade-down" data-aos-duration="2500"><img width="150" height="150" src="<?=TEMPLATE_URL?>/default/img/services/wifi su kien.jpg" /> </div>  
	             <div id="hbg5"><img width="100" height="100" src="http://pm1.narvii.com/5973/ba22eaa67f32e263ddeba90c73f733747c33ab6d_hq.jpg" /> </div>    
	             
	             </div>                    
                                        </div>
                                        <div role="tabpanel" class="tab-pane" id="travels">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</div>
                                        <div role="tabpanel" class="tab-pane" id="medias">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>
                                        <div role="tabpanel" class="tab-pane" id="equips">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passage..</div>
                                                  <div role="tabpanel" class="tab-pane" id="others">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passage..</div>
                                    </div>
</div>
                                
	</div>

					</div><!-- .content-louis-->
		    	</div>
	    	</div>
	    	</div>
			<div class="row">
	    		<div id="numbers">
		    		<div class="col-md-12 description">
			    	<div class="title-louis center"><span class="web-text"><img height="30" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span> & những con số biết nói</div>
			    	<div class="underline"></div>
			    	<div class="content-louis col-md-10 col-md-offset-1 pt20">
				    	<div class="col-md-3" style="text-align: center">
					    	<span class="number-title">Trải qua hơn <br/><span class="pin count-title count-number timer" data-from="1" data-to="10" data-speed="1500">10</span> năm hoạt động</span>
				    	</div>
				    	<div class="col-md-3" style="text-align: center">
					    	<span class="number-title">Quy mô nhân lực <br/> trên <span class="pin count-title count-number timer" data-to="1000" data-speed="1500">1.000</span> người</span>
				    	</div>
				    	<div class="col-md-3" style="text-align: center">
					    	<span class="number-title">Tổ chức hơn <span class="pin count-title count-number timer" data-to="2000" data-speed="1500">2.000</span><br/> sự kiện mỗi năm</span></div>
				    	<div class="col-md-3 npr" style="text-align: center">
					    		<span class="number-title">Cung cấp giải pháp dịch vụ<br/> cho hơn <span class="pin count-title count-number timer" data-to="3000" data-speed="1500">3.000</span> tổ chức</span></div></div>
			    	</div>
		    		</div>
	    		
				</div>
				
			<div class="row">
		    	<div id="testimonials">
		    		<div class="col-md-12">
			    		<div class="title-louis center">Khách hàng nói gì về <span class="web-text"><img height="30" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span></div>
			    		<div class="underline"></div>
			    		<div class="content-louis">
				    		<div class="col-md-10 col-md-offset-1 col-lg-8 col-lg-offset-2">
 
			<div id="carousel-testimonials" class="carousel slide" data-ride="carousel"> 
				<div class="carousel-inner"> 
					 <div class="item active"> 
						 <div class="row"> 
							<?php $i = 0;
								 foreach($this->testimonial as $kt=>$vt): $i++; 
								 $splitname = explode('-', $vt['name']);
								 ?>
					    		<div class="col-md-4" data-aos="flip-right" data-aos-duration="1000">
						    		<div class="info-text">
							    		<div class="img-wrapper">
							    	  <img class="img-circle" width="110" height="110" src="<?=TEMPLATE_URL?>/default/img/h1289.jpg" />
							    	    </div>
							    	  <div class="info-title">
							    	 <span class="info-name"> <?php echo $splitname[0]; ?></span>
							    	 <span class="info-job"> <?php echo $splitname[1]; ?></span>
							    	  </div>
						    		</div>
						    		<div class="info-description">
							    		<div class="info-slogan">
								    		"Dịch vụ chuyên nghiệp"
							    		</div>
							    		<hr/>
							    		<div class="info-comment">
								    	<?php echo $vt['shortDescription']; ?>
							    		</div>
						    		</div>
					    		</div>
					    	<?php echo ($i%3 == 0)?'</div></div><div class="item"><div class="row">':''; ?>
					    	<?php endforeach; ?>	
					    	
						 </div>
					 </div><!--.item-->
				</div><!--.carousel-inner-->
				 <ol class="carousel-indicators" style="bottom: -10px;position: absolute;display: block;"> 
    <li data-target="#carousel-testimonials" data-slide-to="0" class="active"></li> 
    <li data-target="#carousel-testimonials" data-slide-to="1"></li> 
   </ol> 
			</div><!--#carousel-testimonials-->
				    		</div>
			    		</div>
		    		</div>
		    	</div>
	    	</div>
	    	
	    	<div class="row" data-aos="fade-up" data-aos-duration="2500">
		    	<div id="videos">
		    		<div class="col-md-12">
			    		<div class="title-louis center">Profile</div>
			    		<div class="underline"></div>
			    		<div class="content-louis">
				    		
				    		<div class="container">
 <div class="col-md-12"> 
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> 
   <div class="carousel-inner"> 
    <div class="item active"> 
     <div class="row"> 
      <div class="col-sm-4 col-md-4"> 
       <div class="thumbnail"> <a href="#"><img class="img-responsive img-thumbnail" src="<?=TEMPLATE_URL?>/default/img/demo web-10.png" alt=""><div class="video-bg"></div></a> 
       
        <p>Hội thảo quan trọng như Hội nghị APEC</p> 
         
       </div> 
      </div> 
      <div class="col-sm-4 col-md-4"> 
       <div class="thumbnail"> <a href="#"><img class="img-responsive img-thumbnail" src="<?=TEMPLATE_URL?>/default/img/demo web-12.png" alt=""> <div class="video-bg"></div></a> 
      
        <p>Hội nghị quốc tế về khoa học vật liệu tiên tiến và công nghệ Nano</p> 
       
       </div> 
      </div> 
       <div class="col-sm-4 col-md-4"> 
       <div class="thumbnail"> <a href="#"><img class="img-responsive img-thumbnail" src="<?=TEMPLATE_URL?>/default/img/demo web-11.png" alt=""><div class="video-bg"></div></a> 
       
        <p>Hội nghị quốc tế về Thống kê IAOS</p> 
     
       </div> 
      </div> 
     </div> 
    </div> 
   <div class="item"> 
     <div class="row"> 
      <div class="col-sm-4 col-md-4"> 
       <div class="thumbnail"> <a href="#"><img class="img-responsive img-thumbnail" src="<?=TEMPLATE_URL?>/default/img/demo web-10.png" alt=""><div class="video-bg"></div></a> 
       
        <p>Hội thảo quan trọng như Hội nghị APEC</p> 
         
       </div> 
      </div> 
      <div class="col-sm-4 col-md-4"> 
       <div class="thumbnail"> <a href="#"><img class="img-responsive img-thumbnail" src="<?=TEMPLATE_URL?>/default/img/demo web-11.png" alt=""> <div class="video-bg"></div></a> 
      
        <p>Hội nghị quốc tế về khoa học vật liệu tiên tiến và công nghệ Nano</p> 
       
       </div> 
      </div> 
       <div class="col-sm-4 col-md-4"> 
       <div class="thumbnail"> <a href="#"><img class="img-responsive img-thumbnail" src="<?=TEMPLATE_URL?>/default/img/demo web-12.png" alt=""><div class="video-bg"></div></a> 
       
        <p>Hội nghị quốc tế về Thống kê IAOS</p> 
     
       </div> 
      </div> 
     </div> 
    </div> 
    <div class="item"> 
     <div class="row"> 
      <div class="col-sm-4 col-md-4"> 
       <div class="thumbnail"> <a href="#"><img class="img-responsive img-thumbnail" src="<?=TEMPLATE_URL?>/default/img/demo web-12.png" alt=""><div class="video-bg"></div></a> 
       
        <p>Hội thảo quan trọng như Hội nghị APEC</p> 
         
       </div> 
      </div> 
      <div class="col-sm-4 col-md-4"> 
       <div class="thumbnail"> <a href="#"><img class="img-responsive img-thumbnail" src="<?=TEMPLATE_URL?>/default/img/demo web-12.png" alt=""> <div class="video-bg"></div></a> 
      
        <p>Hội nghị quốc tế về khoa học vật liệu tiên tiến và công nghệ Nano</p> 
       
       </div> 
      </div> 
       <div class="col-sm-4 col-md-4"> 
       <div class="thumbnail"> <a href="#"><img class="img-responsive img-thumbnail" src="<?=TEMPLATE_URL?>/default/img/demo web-10.png" alt=""><div class="video-bg"></div></a> 
       
        <p>Hội nghị quốc tế về Thống kê IAOS</p> 
     
       </div> 
      </div> 
     </div> 
    </div> 
   </div> 
   <a class="left carousel-control" href="http://hoabinh-group.com/#carousel-example-generic" data-slide="prev"> <img src="<?=TEMPLATE_URL?>/default/img/btn-l.png" /> </a> <a class="right carousel-control" href="http://hoabinh-group.com/#carousel-example-generic" data-slide="next"><img src="<?=TEMPLATE_URL?>/default/img/btn-r.png" />  </a> 
  
  </div>
 </div>
</div>
				    		
			    		</div>
		    		</div>
		    	</div>
	    	</div>
	    	
	    	<div class="container">
	    	<div class="row">
		    	<!-- tin tuc uu dai -->
		    	<div id="news">
			    	
		    		<div class="col-md-8">
			    		<div class="title-louis left">Tin tức</div>
			    		<div class="content-louis-news">
				    		<div class="row">
					    		<div class="col-md-12">
						    	<?php 
							    	$stt = 0;
							    	foreach($this->result as $knews=>$vnews): $stt++; ?>
					    		<div class="louis_news_hover col-md-6" data-aos="zoom-in" data-aos-duration="1500">
						    		<p><img class="img-responsive thumbnail-new" src="/public/images/news/<?=$vnews['id']?>/<?=$vnews['full']?>"/></p>
						    		<div class="caption">
							<div class="blur"></div>
							<div class="caption-text">
								<h4 style="border-top:2px solid white; border-bottom:2px solid white; padding:5px;line-height:30px;"><?php echo $vnews['name']; ?></h4>
								<p><?php echo $this->string()->cut_string(strip_tags($vnews['shortDescription']),'140','...'); ?></p>
								<a class=" btn btn-default" href="/tin-tuc/<?php echo $vnews['ident'] ?>.html"> Xem thêm</a>
							</div>
						</div>
						    		
					    		</div>
					    		<?php echo ($stt%2 == 0)?'</div></div><div class="row"><div class="col-md-12">':''; ?>
					    		<?php endforeach; ?>
					    		
						    	</div>
				    		</div>
			    		</div>
		    		</div>
		    		<div class="col-md-4">
			    		<div class="title-louis left">Ưu đãi</div>
			    		<div class="content-louis">
						
						<div class="row">
		                   
                                   <div class="new-promotions">
                                    <ul class="nav nav-tabs nav-tabs-promotion" role="tablist">
                                        <li role="presentation" class="active col-md-6 npr"><a href="#doing" aria-controls="doing" role="tab" data-toggle="tab">Đang diễn ra</a></li>
                                        <li class="col-md-6 npl" role="presentation"><a href="#futured" aria-controls="futured" role="tab" data-toggle="tab">Sắp diễn ra</a></li>
                                     
                                    </ul>

                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane active" id="doing">
	     <div class="row">
<div class="col-md-12">
<ul class="promotions" style="padding-left: 0px;margin-top: -20px;">
<li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a class="img-wrapper2" style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/solemn-anniversary-of-toto-vietnam.html"><img src="http://vietnamevents.com/public/images/news/103/food_secure2.jpg" height="80" /></a></td>
<td> <a class="title" href="/solemn-anniversary-of-toto-vietnam.html">Solemn Anniversary Of TOTO Vietnam</a><a class="readmore" href="/solemn-anniversary-of-toto-vietnam.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 <li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a class="img-wrapper2" style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/successful-vsem-conference-2017.html"><img src="http://vietnamevents.com/public/images/news/104/Apricot_1.jpg" height="80" /></a></td>
<td> <a class="title" href="/successful-vsem-conference-2017.html">Successful Vsem Conference 2017</a><a class="readmore" href="/successful-vsem-conference-2017.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 <li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a class="img-wrapper2" style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/exciting-gala-dinner-teambuilding-of-alv.html"><img src="http://vietnamevents.com/public/images/news/100/6Q2A4837(1).jpg" height="80" /></a></td>
<td> <a class="title" href="/exciting-gala-dinner-teambuilding-of-alv.html">Exciting Gala Dinner & Teambuilding of ALV</a><a class="readmore" href="/exciting-gala-dinner-teambuilding-of-alv.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 <li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a class="img-wrapper2" style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/discount-20-of-conference-and-event-equipments.html"><img src="http://vietnamevents.com/public/images/news/99/brotherwelcome2017.jpg" height="80" /></a></td>
<td> <a class="title" href="/discount-20-of-conference-and-event-equipments.html">Discount 20% of conference and event equipments</a><a class="readmore" href="/discount-20-of-conference-and-event-equipments.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 <li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a class="img-wrapper2" style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/impressive-apricot-technology-talkshow-2017.html"><img src="http://vietnamevents.com/public/images/news/117/toto6.jpg" height="80" /></a></td>
<td> <a class="title" href="/impressive-apricot-technology-talkshow-2017.html">Impressive Apricot Technology Talkshow 2017</a><a class="readmore" href="/impressive-apricot-technology-talkshow-2017.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 <li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/lets-get-to-work-buiding-a-food-secure-future.html"><img src="http://vietnamevents.com/public/images/news/102/Talkshow_Crowne%20Plaza1.jpg" height="80" /></a></td>
<td> <a class="title" href="/lets-get-to-work-buiding-a-food-secure-future.html">Let's get to work. Buiding a food secure future</a><a class="readmore" href="/lets-get-to-work-buiding-a-food-secure-future.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 <li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/talkshow-was-organized-at-crowne-plaza-hanoi-hotel.html"><img src="http://vietnamevents.com/public/images/news/105/km.jpg" height="80" /></a></td>
<td> <a class="title" href="/talkshow-was-organized-at-crowne-plaza-hanoi-hotel.html">Talkshow was organized at Crowne Plaza Hanoi Hotel</a><a class="readmore" href="/talkshow-was-organized-at-crowne-plaza-hanoi-hotel.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 <li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/the-upcoming-vsem-conference-2017.html"><img src="http://vietnamevents.com/public/images/news/104/Apricot_1.jpg" height="80" /></a></td>
<td> <a class="title" href="/the-upcoming-vsem-conference-2017.html">The Upcoming VSEM Conference 2017</a><a class="readmore" href="/the-upcoming-vsem-conference-2017.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 <li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/the-perfect-year-end-party-of-diebold-nixdorf-vietnam.html"><img src="http://vietnamevents.com/public/images/news/115/2ALV.jpg" height="80" /></a></td>
<td> <a class="title" href="/the-perfect-year-end-party-of-diebold-nixdorf-vietnam.html">The perfect year-end party of Diebold Nixdorf Vietnam</a><a class="readmore" href="/the-perfect-year-end-party-of-diebold-nixdorf-vietnam.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 <li class="promotions-item">
<table cellpadding="4">
<tr>
<td><a style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/welcome-2017-party-of-brother-company.html"><img src="http://vietnamevents.com/public/images/news/116/9vsem.jpg" height="80" /></a></td>
<td> <a class="title" href="/welcome-2017-party-of-brother-company.html">Welcome 2017 Party of Brother Company</a><a class="readmore" href="/welcome-2017-party-of-brother-company.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
 
</ul>
</div>
</div>                                   
	                                        
	                                                                                
                                        </div>
                                        <div role="tabpanel" class="tab-pane" id="futured">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</div>
                                     
                                    </div>
</div>
                                
	</div>

					</div><!-- .content-louis-->
		    		</div>
		    		
		    	</div>
	    	</div>
	    	</div>
	    	
	    	<div class="row" style="margin-top: -20px;">
		    	<div class="title-louis center"> Đối tác của <span class="web-text"><img height="30" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span></div>
		    	<div class="underline"></div>
		    	<div class="content-louis">
			    	
			    	<div class="container-fluid" style="margin-left:5px;">
    <div class="well" style="border:0px solid grey;background: transparent;">
	    <div id="owl-clients" class="owl-carousel owl-theme">	
			<?php for($i=1;$i<=50;$i++){ ?>		
	<div class="item"><li><a target="_blank" href=""> <img alt="" class="showTipsy" title="HoabinhGroup"  src="/public/images/logo/logo<?=$i?>.png" alt=""> </a></li></div>
			<? } ?>
		
					</div>
       
        <!--/myCarousel-->
    </div>
    <!--/well-->
</div>
		    	</div>
	    	</div>