<div id="intro">
			<div class="container">
		    	<div class="row">
			    
			    		<div class="col-md-5 title">
				    		<div data-aos="fade-right" data-aos-duration="2500">
				    		<span class="website"><span class="web-text"><img alt="logo Hòa Bình Group" class="img-responsive" height="45" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span></span>
				    		<span style="height: 6px;width: 5px;display: block;">&nbsp;</span>
				    		<span class="des">Tầm nhìn & sứ mệnh</span>
				    		</div>
				    		</div>
						<div class="col-md-7 description" data-aos="fade-left" data-aos-duration="2500">Với phương châm “Chất lượng làm nên danh tiếng”, trải qua hơn 10 năm xây dựng và trưởng thành,​ tập đoàn ​HoaBinhGroup (Convention – Events – Travel) đã khẳng định uy tín của mình là một trong những tập đoàn hàng đầu trong lĩnh vực tổ chức Hội nghị, hội thảo, sự kiện và du lịch tại Việt Nam...
					  <span class="more"><a title="Xem tiếp giới thiệu" href="/ve-chung-toi">Xem tiếp >></a></span>		
						</div>
			        
		    	</div>
		    </div>	
</div>
	    	<div class="row sv hidden-sm">
	    		<div id="service-tabs">
		    	<div class="col-md-10 col-md-offset-1">
		    		<div class="title-louis text-center animated flipInX">
		    		<span class="web-text"><img alt="Logo Hòa Bình Group" height="30" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span> cung cấp các dịch vụ
					</div><!-- .title-louis-->
					<div class="content-louis">
						
						<div class="row">
		                   
                                   <div class="service">
                                    <ul id='services_tab' class="nav nav-tabs" role="tablist">
                                        <li role="presentation" class="active"><a href="/">Tổ chức sự kiện, hội nghị</a></li>
                                        <li role="presentation"><a href="/">Tổ chức Tour du lịch</a></li>
                                        <li role="presentation"><a href="/">Giải pháp quảng cáo truyền thông</a></li>
                                        <li role="presentation"><a href="/">Cung cấp thiết bị sự kiện</a></li>
                                          <li role="presentation"><a href="/">Các dịch vụ khác</a></li>
                                    </ul>

                                    <!-- Tab panes -->
                                    <div class="tab-content">
                                        <div role="tabpanel" class="tab-pane active" id="home">
	            <div class="hidden-sm" style="margin-top: -50px;margin-left: -50px;">
	        <img alt="Bản đồ dịch vụ" src="<?=TEMPLATE_URL?>/default/img/services/map-sv-01.png" />  
	           <div data-toggle="tooltip" title="Tổ chức Hội nghị, sự kiện" data-placement="right" id="hbg-center" data-aos="fade-left" data-aos-duration="2500"><a  href="/linh-vuc/to-chuc-su-kien"><img alt="Tổ chức sự kiện" width="200" height="200" src="<?=TEMPLATE_URL?>/default/img/services/su%20kien.jpg" /></a> </div>        
	           <div data-toggle="tooltip" title="Tổ chức Hội nghị hội thảo" data-placement="left" id="hbg2" data-aos="fade-left" data-aos-duration="3500">
		           <a href="/linh-vuc/to-chuc-hoi-nghi-hoi-thao"><img alt="Tổ chức galadiner" width="120" height="120" src="<?=TEMPLATE_URL?>/default/img/services/cong-ty-to-chuc-su-kien-to-chuc-galadiner-tiec-tra-teabreak-buffet-5.jpg" /></a> </div> 
	           <div data-toggle="tooltip" title="Giải pháp quảng cáo truyền thông" data-placement="left" id="hbg3" data-aos="fade-right" data-aos-duration="2500">
		            <a href="/linh-vuc/giai-phap-quang-cao-truyen-thong"><img alt="Giải pháp quảng cáo truyền thông" width="110" height="110" src="<?=TEMPLATE_URL?>/default/img/services/nhadatgiaodich_abc_xyx_3.20160307133241-6184.jpg" /> </a></div>  
	             <div data-toggle="tooltip" title="Tổ chức Tour, Team building" data-placement="left" id="hbg4" data-aos="fade-down" data-aos-duration="2500">
		             <a href="/linh-vuc/to-chuc-tour-teambuilding"><img alt="Tổ chức Tour, Teambuilding" width="150" height="150" src="<?=TEMPLATE_URL?>/default/img/services/wifi su kien.jpg" /></a> </div>  
	             <div data-toggle="tooltip" title="Cung cấp thiết bị sự kiện" data-placement="left" id="hbg5">
		              <a href="/linh-vuc/cung-cap-thiet-bi-su-kien"><img alt="Cung cấp thiết bị sự kiện" width="100" height="100" src="http://pm1.narvii.com/5973/ba22eaa67f32e263ddeba90c73f733747c33ab6d_hq.jpg" /></a> </div>    
	             
	             </div>     
	            <script>
$(document).ready(function(){
    $('[data-toggle="tooltip"]').tooltip(); 
});
</script>               
                                        </div>
                                        <div role="tabpanel" class="tab-pane" id="travels">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.</div>
                                        <div role="tabpanel" class="tab-pane" id="medias">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</div>
                                        <div role="tabpanel" class="tab-pane" id="equips">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passage..</div>
                                                  <div role="tabpanel" class="tab-pane" id="others">Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passage..</div>
                                    </div>
</div>
                                
	</div>

					</div><!-- .content-louis-->
		    	</div>
	    	</div>
	    	</div>
			<div class="row">
	    		<div id="numbers">
		    		<div class="col-md-12 description">
			    	<div class="title-louis text-center"><span class="web-text"><img alt="Hòa Bình Group & những con số biết nói" height="30" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span> & những con số biết nói</div>
			    	<div class="underline"></div>
			    	<div class="content-louis col-md-10 col-md-offset-1 pt20">
				    	<div class="col-md-3 text-center">
					    	<span class="number-title">Trải qua hơn <br/><span class="pin count-title count-number timer" data-from="1" data-to="10" data-speed="1500">10</span> năm hoạt động</span>
				    	</div>
				    	<div class="col-md-3 text-center">
					    	<span class="number-title">Quy mô nhân lực <br/> trên <span class="pin count-title count-number timer" data-to="1000" data-speed="1500">1.000</span> người</span>
				    	</div>
				    	<div class="col-md-3 text-center">
					    	<span class="number-title">Tổ chức hơn <span class="pin count-title count-number timer" data-to="2000" data-speed="1500">2.000</span><br/> sự kiện mỗi năm</span></div>
				    	<div class="col-md-3 text-center">
					    		<span class="number-title">Cung cấp giải pháp dịch vụ<br/> cho hơn <span class="pin count-title count-number timer" data-to="3000" data-speed="1500">3.000</span> tổ chức</span></div></div>
			    	</div>
		    		</div>
	    		
				</div>
				
			<div class="row">
		    	<div id="testimonials">
		    		<div class="col-md-12">
			    		<div class="title-louis text-center">Khách hàng nói gì về <span class="web-text"><img alt="Logo Hòa Bình Group" height="30" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span></div>
			    		<div class="underline"></div>
			    		<div class="content-louis-testimonial">
				    		<div class="des-testimonial">
 
			<div id="carousel-testimonials" class="carousel slide" data-ride="carousel"> 
				<div class="carousel-inner"> 
					<?php if(count($this->testimonial) >0){ ?>
					<div class="item active">
						 <div class="row">
					<?php
						$sttt = 0;
						 foreach($this->testimonial as $kt=>$vt): $sttt++; 
						 $param = explode('-', $vt['name']);
						 ?>
					  
			<div class="col-md-4" data-aos="flip-right" data-aos-duration="1000">
						    		<div class="info-text">
							    		<div class="img-wrapper">
							    	  <img alt="<?=$vt['name']?>" class="img-circle" width="110" height="110" src="/public/images/testimonial/<?=$vt['id']?>/<?=$vt['full']?>" />
							    	    </div>
							    	  <div class="info-title">
							    	 <span class="info-name"> <?php echo $param[0]; ?></span>
							    	 <span class="info-job"> <?php echo $param[1]; ?></span>
							    	  </div>
						    		</div>
						    		<div class="info-description">
							    		<div class="info-slogan">
								    		<?php echo $vt['shortDescription']; ?>
							    		</div>
							    		<hr/>
							    		<div class="info-comment">
								    	<?php echo $vt['description']; ?>
							    		</div>
						    		</div>
					    		</div>
					   
						
			 <?php echo ($sttt%3==0)?'</div></div><div class="item"><div class="row">':''; ?>		 
					 <?php endforeach; ?>
					 
					  </div>
					</div><!--.item-->
					<?php } ?>
				</div><!--.carousel-inner-->
				 <ol class="carousel-indicators" style="bottom: -10px;position: absolute;display: block;"> 
    <li data-target="#carousel-testimonials" data-slide-to="0" class="active"></li> 
    <li data-target="#carousel-testimonials" data-slide-to="1"></li> 
   </ol> 
			</div><!--#carousel-testimonials-->
				    		</div>
			    		</div>
		    		</div>
		    	</div>
	    	</div>
	    	
	    	<?php if(count( $this->result_video) >0 ){ ?>
	    	<div class="row" data-aos="fade-up" data-aos-duration="2500">
		    	<div id="videos">
		    		<div class="col-md-12">
			    		<div class="title-louis text-center" style="padding-left: 22px;">Profile</div>
			    		<div class="underline"></div>
			    		<div class="content-louis">
				    		
				    		<div class="container">
 <div class="col-md-12"> 
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> 
   <div class="carousel-inner"> 
	    <div class="item active"> 
     <div class="row"> 
	    <?php
		    $sttv = 0;
		     foreach($this->result_video as $kv=>$vv): $sttv++;
		     $thumb = $this->Image()->get_youtube_thumb($vv['shortDescription']);
		    // echo $vv['shortDescription'];
		      ?>
   
	    
      <div class="col-sm-4 col-md-4 openSlickModal-1" data="<?php echo str_replace('watch?v=', 'embed/', $vv['shortDescription']) ?>" onClick="showContent(this);"> 
       <div class="thumbnail"> <a href="#"><img alt="<?=$vv['name']?>" class="img-responsive img-thumbnail" src="<?=$thumb?>" alt=""><div class="video-bg"></div></a> 
       
        <p><a href="#"><?php echo $vv['name']; ?></a></p> 
         
       </div> 
      </div> 
    <?php echo ($sttv%3==0)?'</div></div><div class="item"><div class="row">':''; ?>
     
    <?php endforeach; ?>
 
 
		</div> 
		</div> 
   </div> 
   <a class="left carousel-control" href="http://hoabinh-group.com/#carousel-example-generic" data-slide="prev"> <img src="<?=TEMPLATE_URL?>/default/img/btn-l.png" /> </a> <a class="right carousel-control" href="http://hoabinh-group.com/#carousel-example-generic" data-slide="next"><img src="<?=TEMPLATE_URL?>/default/img/btn-r.png" />  </a> 
  
  </div>
 </div>
</div>
				    		
			    		</div>
		    		</div>
		    	</div>
	    	</div>
	    	<?php  } ?>
	    	<div class="container">
	    	<div class="row">
		    	<!-- tin tuc uu dai -->
		    	<div id="news">
			    	
		    		<div class="col-md-8">
			    		<div class="title-louis-left text-uppercase">Tin tức</div>
			    		<div class="content-louis-news">
				    <div class="row">
					    <div class="col-md-12">		
				<?php 
			
					$i = 0;
					 foreach($this->news as $knew=>$vnew): $i++; ?>	
					 	    		
					    		<div class="louis_news_hover col-md-6" data-aos="zoom-in" data-aos-duration="1500">
						    		<p><img alt="Ảnh  <?php echo $vnew['name']; ?>" class="thumbnail-new" src="/public/images/news/<?=$vnew['id']?>/<?=$vnew['full']?>" /></p>
						    		<div class="caption">
							<div class="blur"></div>
							<div class="caption-text">
								<h4 style="border-top:2px solid white; border-bottom:2px solid white; padding:8px 10px;color: #fff;line-height: 28px;"><?php echo $vnew['name']; ?></h4>
								<p><?php echo $this->string()->cut_string(strip_tags($vnew['shortDescription']),'100','...'); ?></p>
								<a class=" btn btn-default" href="/tin-tuc/<?php echo $vnew['ident']; ?>.html"> Xem thêm</a>
							</div>
						</div>
						    		
					    		</div>
				<?php 
					echo ($i%2==0)?'</div></div><div class="row"><div class="col-md-12">':'';
					endforeach; ?>		    		
					    		
			    		</div>
		    		</div>
		    		
			    		</div></div>
		    		<div class="col-md-4">
			    		<div class="title-louis-left text-uppercase">Ưu đãi</div>
			    		<div class="content-louis">
						
						<div class="row">
		                   
                                   <div class="new-promotions">
                               <div class="row">
<div class="col-md-12">
<ul class="promotions" style="padding-left: 0px; height: auto;">
	<?php foreach($this->featured as $kf=>$vf): ?>
<li class="promotions-item">
<table cellpadding="5">
<tr>
<td><a class="img-wrapper2" style="width: 100px; overflow: hidden;display: block; margin-right: 15px;" href="/tin-tuc/<?php echo $vf['ident']; ?>.html"><img src="/public/images/news/<?php echo $vf['id']; ?>/<?php echo $vf['full']; ?>" height="80" /></a></td>
<td> <a class="title" href="/tin-tuc/<?php echo $vf['ident']; ?>.html"><?php echo $vf['name']; ?></a><br/><a class="readmore" href="/tin-tuc/<?php echo $vf['ident']; ?>.html"> Xem thêm...</a></td>
</tr>
</table>
</li>
	<?php endforeach; ?>
 
</ul>
</div>
</div>  
</div>
                                
	</div>

					</div><!-- .content-louis-->
		    		</div>
		    		
		    	</div>
	    	</div>
	    	</div>
	    	
	    	<div class="row" style="margin-top: -20px;">
		    	<div class="title-louis text-center"> Đối tác của <span class="web-text"><img height="30" src="<?=TEMPLATE_URL?>/default/img/logo 2-01.png"/></span></div>
		    	<div class="underline"></div>
		    	<div class="content-louis">
			    	
			    	<div class="container-fluid" style="margin-left:5px;">
    <div class="well" style="border:0px solid grey;background: transparent;">
	    <div id="owl-clients" class="owl-carousel owl-theme">	
			<?php for($i=1;$i<=50;$i++){ ?>		
	<div class="item"><li><a target="_blank" href=""> <img alt="Logo đối tác <?=$i?>" class="showTipsy grayscale" title="HoabinhGroup"  src="/public/images/logo/logo<?=$i?>.png" alt=""> </a></li></div>
			<?php } ?>
					
					</div>
       
        <!--/myCarousel-->
    </div>
    <!--/well-->
</div>
		    	</div>
	    	</div>
	    	
	    	
	    	<div id="popup-1" class="slickModal">

			<div class="slickWindow">
				<!-- Your popup content -->
		
				<!-- / Your popup content -->
			</div>
		</div>
		
		<script type="text/javascript">
			function showContent(o)
		{
		
		var url = $(o).attr('data');
		var title = $(o).attr('title');
		
		$(".slickWindow").html('<iframe width="1000" height="620" id="myVideo" src="'+url+'?&autoplay=1" allowfullscreen></iframe>');
		}
		
		
			$(document).ready(function() {
				
				

			    // Modal 1
			    $('#popup-1').slickModals({
			      
			        // Overlay styling
			        overlayBg: true,
			        overlayClosesModal: true,
			        overlayBgColor: 'rgba(0,0,0,0.85)',
			        overlayTransitionSpeed: '0.4',
			        // Background effects
			        pageEffect: 'none',
			        blurBgRadius: '1px',
			        scaleBgValue: '0.9',
			        // Popup styling
			        popupWidth: '80%',
			        popupHeight: '80%',
			        popupLocation: 'center',
			        popupAnimationDuration: '0.6',
			        popupAnimationEffect: 'slideBottom',
			        popupShadowOffsetX: '0',
			        popupShadowOffsetY: '0',
			        popupShadowBlurRadius: '40px',
			        popupShadowSpreadRadius: '0',
			        popupShadowColor: 'rgba(0,0,0,0.4)',
			        popupBackground: '#000',
			        popupRadius: '0',
			        popupMargin: '0',
			        popupPadding: '0',
			        // Responsive rules
			        responsive: true,
			        breakPoint: '480px',
			        mobileLocation: 'center',
			        mobileWidth: '480px',
			        mobileHeight: '280px',
			        mobileRadius: '0',
			        mobileMargin: '0',
			        mobilePadding: '20px',
			        // Animate content
			        contentAnimate: false,
			        contentAnimateEffect: 'zoomIn',
			        contentAnimateSpeed: '0.4',
			        contentAnimateDelay: '0.4',
			        // Youtube videos
			        videoSupport: true,
			        videoAutoPlay: true,
			        videoStopOnClose: true,
			        // Close and reopen button
			        addCloseButton: true,
			        buttonStyle: 'labeled',
			        enableESC: true,
			        reopenClass: 'openSlickModal-1',
			        // Additional events
			        onSlickLoad: function() {
			            console.log("Slick is visible");
			        },
			        onSlickClose: function() {
			            console.log("Slick is hidden");
					$('#myVideo').attr('src', '');
			        }
			    });
			});
		</script>