<div class="sixteen columns add-top"> 
			
					<div class="title">
						
						<h2> <span class="bold"><?php echo $this->translate('members'); ?></span> </h2>
						
						<div class="title_sep_container">
							<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
						
					</div><!-- end .title -->
					
					<ul class="rc_list">
					
					
						<li class="first"> 
						
							<div class="hover panel"> 
							
								<div class="front">
									  
									<img class="lazy" src="/public/images/dummy.png" data-original="/public/images/Hoabinhtourist-&-Convention.png"  alt="MEETINGS & CONFERENCES"/>
									<span style="color:#04245D">MEETINGS & CONFERENCES</span>
										
								</div><!-- end .front -->
									
								<div class="back" style="background: #fff;">
									
									<div class="pad">

				<span class="logo" style="margin: 0 auto;display: block;text-align: center;"><a target="_blank" title="Giới thiệu về cty HoabinhTouris & Convention" rel="dofollow" href="http://hoabinhtourist.com"><img alt="HoabinhTouris & Convention" class="lazy" src="/public/images/dummy.png" data-original="/public/images/logo_hoabinhtourist_chuan_nh1.png" height="120" /></a></span>	
									<p style="text-align: center;"><?php echo $this->translate('about'); ?>  HoabinhTouris & Convention </p>
			<a target="_blank" rel="dofollow" title="Giới thiệu về cty HoabinhTouris & Convention" style="text-align: center;display: block;" onmouseover="this.style.color='red';" onmouseout="this.style.color='';" href="http://hoabinhtourist.com" ><?php echo $this->translate('more'); ?></a>
									</div><!-- end .pad -->
										
								</div><!-- end .back -->
									
							</div><!-- end .panel -->
						
						</li>
						
						
						<li> 
						
							<div class="hover panel"> 
							
								<div class="front">
									  
									<img class="lazy" src="/public/images/dummy.png" data-original="/public/images/21689-mices.jpg"  alt="VIETNAMCONFERENCE"/>
									<span style="color:#04245D">CONFERENCE</span>
										
								</div><!-- end .front -->
									
								<div class="back" style="background: #0F161E;color: #fff;">
									
									<div class="pad">

				<span class="logo" style="margin: 0 auto;display: block;text-align: center;"><a target="_blank" title="Giới thiệu về cty VietnamConference" href="http://vietnamconference.com.vn"><img class="lazy" src="/public/images/dummy.png" data-original="/public/images/17523-logo.jpg" height="120" /></a></span>	
									<p style="text-align: center;"><?php echo $this->translate('about'); ?>  VietnamConference </p>
			<a target="_blank" rel="dofollow" title="Giới thiệu về VietnamConference" style="text-align: center;display: block;" onmouseover="this.style.color='red';" onmouseout="this.style.color='';" href="http://vietnamconference.com.vn" ><?php echo $this->translate('more'); ?></a>
									</div><!-- end .pad -->
										
								</div><!-- end .back -->
									
							</div><!-- end .panel -->
						
						</li>
						
						
						
						<li>
						
							<div class="hover panel">
							
								<div class="front">
									  
									<img class="lazy" src="/public/images/dummy.png" data-original="/public/images/non-nuoc-media.png"  alt="NONNUOCMEDIA"/>
									<span style="color:#04245D">MEDIA</span>
										
								</div><!-- end .front -->
									
								<div class="back" style="background: #222131;">
									
									<div class="pad">
								<span class="logo" style="margin: 0 auto;display: block;text-align: center;"><a target="_blank" rel="dofollow" href="http://nonnuocmedia.com"><img alt="NONNUOCMEDIA" class="lazy" src="/public/images/dummy.png" data-original="/public/images/17523-logo-non-nuoc-media.jpg" height="120" /></a></span>
									
			<p style="text-align: center;color: #fff;"><?php echo $this->translate('about'); ?> Non Nuoc Media </p>
			<a target="_blank" rel="dofollow" style="text-align: center;display: block;"  title="Giới thiệu về Non Nuoc Media" onmouseover="this.style.color='orange';" onmouseout="this.style.color='';" href="http://nonnuocmedia.com"><?php echo $this->translate('more'); ?></a>
									</div><!-- end .pad -->
										
								</div><!-- end .back -->
									
							</div><!-- end .panel -->
							
						</li>
						
						
			
						
				</ul><!-- end ul.rc_list -->
			
			
			</div><!-- end sixteen -->

<div class="sixteen columns"> 
		
		<ul class="rc_list">
					
						
						
						<li class="first">
						
							<div class="hover panel">
							
								<div class="front">
									  
									<img class="lazy" src="/public/images/dummy.png" data-original="/public/images/ha-long-bay.jpg"  alt="GLOBALMICETRAVEL"/>
									<span style="color:#04245D">MICE</span>
										
								</div><!-- end .front -->
									
								<div class="back" style="background: #1B2854;">
									
									<div class="pad">
									
					<span class="logo" style="margin: 0 auto;display: block;text-align: center;"><a target="_blank" href="http://globalmicetravel.com"><img class="lazy" src="/public/images/dummy.png" data-original="/public/images/logo_hoabinhgroup_xanh1.png" height="120" /></a></span>						
				<p style="text-align: center;color: #fff;"><?php echo $this->translate('about'); ?>  Global Mice Travel </p>
				<a target="_blank" rel="dofollow" title="Giới thiệu về Global Mice Travel" style="text-align: center;display: block;" onmouseover="this.style.color='orange';" onmouseout="this.style.color='';" href="http://globalmicetravel.com" ><?php echo $this->translate('more'); ?></a>
									</div><!-- end .pad -->
										
								</div><!-- end .back -->
									
							</div><!-- end .panel -->
							
						</li>
						
						
						<li>
						
							<div class="hover panel">
							
								<div class="front">
									  
									<img class="lazy" src="/public/images/dummy.png" data-original="/public/images/du-lich-hoa-binh.jpg"  alt="du lịch hòa bình"/>
									<span style="color:#04245D">TRAVEL</span>
										
								</div><!-- end .front -->
									
								<div class="back" style="background: #1B2854;">
									
									<div class="pad">
									
					<span class="logo" style="margin: 0 auto;display: block;text-align: center;"><a target="_blank" href="http://dulichhoabinh.com"><img class="lazy" src="/public/images/dummy.png" data-original="/public/images/logo_hoabinhgroup_xanh1.png" height="120" /></a></span>						
				<p style="text-align: center;color: #fff;"><?php echo $this->translate('about'); ?>  Du Lịch Hòa Bình </p>
				<a target="_blank" rel="dofollow" title="Giới thiệu về cty Du lịch hòa bình" style="text-align: center;display: block;" onmouseover="this.style.color='orange';" onmouseout="this.style.color='';" href="http://dulichhoabinh.com" ><?php echo $this->translate('more'); ?></a>
									</div><!-- end .pad -->
										
								</div><!-- end .back -->
									
							</div><!-- end .panel -->
							
						</li>
						
						
						<li>
						
							<div class="hover panel">
							
								<div class="front">
									  
									<img class="lazy" src="/public/images/dummy.png" data-original="/public/images/cover_solution.jpg"  alt=""/>
									<span style="color:#04245D">SOLUTIONS</span>
										
								</div><!-- end .front -->
									
								<div class="back" style="background: #fff;">
									
									<div class="pad">
								<span class="logo" style="margin: 0 auto;display: block;text-align: center;height: 110px"><a href="http://eventsolutions.vn"><img class="lazy" src="/public/images/dummy.png" data-original="/public/images/logo.png" width="200" /></a></span>
									
			<p style="text-align: center;"><?php echo $this->translate('about'); ?> EventSolutions </p>
			<a style="text-align: center;display: block;"  title="Giới thiệu về EventSolutions" onmouseover="this.style.color='orange';" onmouseout="this.style.color='';" href="http://eventsolutions.vn"><?php echo $this->translate('more'); ?></a>
									</div><!-- end .pad -->
										
								</div><!-- end .back -->
									
							</div><!-- end .panel -->
							
						</li>
					</ul><!-- end ul.rc_list -->
			
			
			</div><!-- end sixteen -->
			
		

		<div class="two-thirds column">
				<!-- gioi thieu cty-->
			<div class="add-top add-bottom">
				
					<div class="title">
								
						<h2> <span class="bold"><?php echo $this->translate('intro'); ?></span> </h2>
								
						<div class="title_sep_container">
								<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
								
					</div><!-- end .title -->
				
				<div style="text-align: justify;">
				<?php 
					if ($this->lang == 'vi'){
					echo $this->string()->cut_string(nl2br(strip_tags($this->description)),'1500','...');	
					}else {
				   echo $this->string()->cut_string($this->description,'1100','...');		
					}
					 ?>	
					
				</div>
			<?php  $identity = Zend_Auth::getInstance()->getIdentity();
				
				
				 ?>	
				
				<?php // } ?>
				</div><!-- end eight -->
				
			<!-- testimonial-->
			<?php if(count($this->testimonial) > 0){ ?>
			<div class="add-bottom"> 
					
						<div class="title">
									
							<h2> <span class="bold"><?php echo $this->translate('testimonials'); ?></span> </h2>
									
							<div class="title_sep_container">
									<div class="title_sep"></div>
							</div><!-- end .title_sep_container -->
									
						</div><!-- end .title -->
			<style>.testimonialList li blockquote{
				margin-left: 0px !important;
				}
			.testimonialHolder blockquote { 
  font: 18px normal Tahoma, sans-serif; 
  padding-top: 10px; 
  margin: 5px; 
  background: url('/public/img/comma1-left.gif') no-repeat top left; 
  text-indent: 65px; 
  } 
  .testimonialHolder blockquote p { 
    display: block; 
    background: url('/public/img/comma1-right.gif') no-repeat bottom right; 
padding-bottom:10px; 
}
.testimonialHolder blockquote p { 
margin: 0; 
padding-top:10px; 
}
			</style>			
						<ul class="testimonialList testimonials_slider">
							<?php foreach($this->testimonial as $kt=>$vt): ?>	
								<li>   
									<div class="testimonialHolder">
										<!--<img src="images/placeholders/50x50-gray.jpg" alt=""/> -->
										<blockquote class="bg"><p style="text-align: justify; font-size: 13px; "><?php echo $vt['shortDescription']; ?> <a href="/testimonial/<?php echo $vt['ident']; ?>">[...]</a></p></blockquote>
										
									</div>
									<div class="arrow-down"></div>
									<div class="testimonialAuthor"> <span class="bold"><?php echo $vt['name']; ?></span> <span class="testimonial_title"> </span> </div>
								</li>
							<?php endforeach; ?>	
																
								
								
						</ul><!-- end ul.testimonialList -->
						
								
					
					</div><!-- end six -->
			<?php } ?>
		</div> <!-- .two-thirds -->
				
				<style>
					.cart_list li::before{
						background-position: -32px 3px !important;
					}
				</style>

	     <div class="one-third column omega">
			
		 	<div class="add-top add-bottom">
			<div class="title">
								
						<h2> <span class="bold"><?php echo $this->translate('latest_new'); ?></span> <span></span> </h2>
								
						<div class="title_sep_container">
								<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
								
					</div><!-- end .title -->
					<ul id="latest_news" class="cart_list">
					<?php
						$i = 0;
						 foreach($this->result as $k=>$v): $i++; ?>
					<?php
						//$src = $this->Image()->getFirstImageContent($v['description']);
						   ?>
							<li style="top:6px;background: #F5F2F2;">
							
							<a style="margin-top: 2px;display: inline-block;padding: 3px; width: 278px;color: #04245D;" title="<?php echo $v['name']; ?>" href="/tin-tuc/<?php echo $v['ident']; ?>.html">[<?php echo date('d/m',$v['date']); ?>] <?php
								if($this->lang == 'vi'){
								 echo $this->string()->cut_string($v['name'],'80','...'); 
								 }else {
								 echo $this->string()->cut_string($v['name'],'80','...'); 	 
								 }
								 ?></a> </li>
						<div style="clear:both;"></div>
						
							
					<?php endforeach; ?>
						
					</ul>
				</div>
							
		 	<div class="add-bottom video_hb" style="margin-top: 0px;"> 
			 	<div class="title">
								
						<h2> <span class="bold"><?php echo $this->translate('video'); ?></span> <span></span> </h2>
								
						<div class="title_sep_container">
								<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
								
					</div><!-- end .title -->
					<ul id="latest_news" class="cart_list">
					<div id="imgvideo" onclick="showvideo();"><img width="300" src="/public/images/hoabinh_cover.jpg" style="cursor:pointer" /></div><div id="thevideo" style="display:none">									
<iframe width="340" height="210" src="https://www.youtube.com/embed/9JbtjnTD4Hk?&theme=light&autoplay=0" frameborder="0" allowfullscreen></iframe>
	</div>
						
					</ul>
				</div>		
		
			</div>
			
			<!-- end sixteen -->

		
				<div class="sixteen columns add-top add-bottom custommer">
						
					<div class="title">
								
						<h2> <span class="bold"><?php echo $this->translate('clients'); ?></span> </h2>
								
						<div class="title_sep_container">
								<div class="title_sep"></div>
						</div><!-- end .title_sep_container -->
								
					</div><!-- end .title -->
					<ul class="clients">
					<div id="owl-top-tours" class="owl-carousel owl-theme">	
						<?php for($i=1;$i<=50;$i++){ ?>
	<div class="item"><li><a target="_blank" href=""> <img alt="Hoabinhgroup_logo<?=$i?>" class="showTipsy lazy" title="HoabinhGroup"  src="/public/images/dummy.png" data-original="/public/images/logo/logo<?=$i?>.png" alt=""> </a></li></div>
						<? } ?>
					</div>			
					</ul><!-- end ul.clients -->
				
						
				</div><!-- end sixteen -->	
	 <script src="<?=TEMPLATE_URL?>/default/owl/owl.carousel.min.js" type="text/javascript"></script>		
	 	
<script>
	$('#latest_news').children('li').hover(function(){
		$(this).css('background','#F8D94A');
	},function(){
		$(this).css('background','#F5F2F2');
	});
	
	
 $("#owl-top-tours").owlCarousel({
    navigation : true,
     items : 6,
     navigationText: false,
      autoPlay :true,
stopOnHover :true
  });
 
  
   $("#owl-top-news").owlCarousel({
    navigation : false,
     navigationText: false,
      autoPlay :true,
stopOnHover :true,
  singleItem:true
  });
 

	    $('.owl-buttons').hide();
   $('.owl-pagination').hide();
	    
	    $('#thevideo').click(function(){
$('iframe').attr("src", $("iframe").attr("src").replace("autoplay=0", "autoplay=1"));
});

function showvideo(o){
	$('#imgvideo').hide();
	$('#thevideo').show();
	 $('#thevideo').children('iframe').attr("src", $('#thevideo').children('iframe').attr("src").replace("autoplay=0", "autoplay=1"));
}
</script>