<style>
	.product-block .product-zoom{
	right: 55%;
}
	.product-block a:hover{
	color: #fff;
}
</style>
<section class="pav-showcase" id="pavo-showcase">
<div class="container">
				<div class="row">	
		<div class="col-lg-12 col-md-12">

<div class=" box productcarousel orange nopadding">
	<div class="box-heading">
		<span class="title">Best Seller</span>
	</div>
	<div class="box-content">
		<div class="box-products slide" id="productcarousel30">			
						
						<div class="carousel-controls">
				<a class="carousel-control left" href="#productcarousel30" data-slide="prev">
					<i class="fa fa-angle-left"></i>
				</a>
				<a class="carousel-control right" href="#productcarousel30" data-slide="next">
					<i class="fa fa-angle-right"></i>
				</a>
			</div>
						
			<div class="carousel-inner">		
					
								<div class="item">
															<div class="row product-items last">
												<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5 first">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=53"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_12-215x238.jpg" title="Vivamus ultrices quam vitae nibh aliquets" alt="Vivamus ultrices quam vitae nibh aliquets"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_12.jpg" class="info-view colorbox product-zoom cboxElement" title="Vivamus ultrices quam vitae nibh aliquets"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=53"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=53">Vivamus ultrices quam vitae nibh aliquets</a></h3>	
												<div class="price">
															<span class="price-old">$58.00</span> 
								<span class="price-new">$20.00</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-3.png" alt="3"></div>
					    
						<p class="description">Lorem Ipsum has been the industry's 
standard dummy text ever since the 1500s, when an unknown printer took a
 galley of type and scrambled it to make a type specimen book.
...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('53');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('53');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('53');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=48"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_20-215x238.jpg" title="Duffle Bag  revival reigns supreme" alt="Duffle Bag  revival reigns supreme"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_20.jpg" class="info-view colorbox product-zoom cboxElement" title="Duffle Bag  revival reigns supreme"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=48"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=48">Duffle Bag  revival reigns supreme</a></h3>	
												<div class="price">
															<span class="price-old">$589.50</span> 
								<span class="price-new">$107.75</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-4.png" alt="4"></div>
					    
						<p class="description">Directional, exciting and diverse, the 
Bag&nbsp;makes and breaks the fashion rules. Scouring the globe for 
inspiration, our London based Design Team is inspired by fashion’s most 
covetable trends; providing you with a cu...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('48');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('48');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('48');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=31"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_04-215x238.jpg" title="Canon EOS 40D 10.1MP SLR Camera" alt="Canon EOS 40D 10.1MP SLR Camera"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_04.jpg" class="info-view colorbox product-zoom cboxElement" title="Canon EOS 40D 10.1MP SLR Camera"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=31"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=31">Canon EOS 40D 10.1MP SLR Camera</a></h3>	
												<div class="price">
															<span class="price-old">$96.00</span> 
								<span class="price-new">$10,577.00</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-4.png" alt="4"></div>
					    
						<p class="description">
Engineered with pro-level features and performance, the 
12.3-effective-megapixel D300 combines brand new technologies with 
advanced features inherited from Nikon's newly announced D3 professional
 digital SLR camera to ...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('31');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('31');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('31');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5">
							<div class="product-block">	
														<div class="image">
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=51"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_21-215x238.jpg" title="aculis suscipit sollicitudin dignissim nunc " alt="aculis suscipit sollicitudin dignissim nunc "></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_21.jpg" class="info-view colorbox product-zoom cboxElement" title="aculis suscipit sollicitudin dignissim nunc "><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=51"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=51">aculis suscipit sollicitudin dignissim nunc </a></h3>	
												<div class="price">
															<span class="special-price">$67.00</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-5.png" alt="5"></div>
					    
						<p class="description">Directional, exciting and diverse, the 
Bag&nbsp;makes and breaks the fashion rules. Scouring the globe for 
inspiration, our London based Design Team is inspired by fashion’s most 
covetable trends; providing you with a cu...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('51');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('51');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('51');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5 last">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=59"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_25-215x238.jpg" title="Citizen Women's EW and Men's EW" alt="Citizen Women's EW and Men's EW"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_25.jpg" class="info-view colorbox product-zoom cboxElement" title="Citizen Women's EW and Men's EW"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=59"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=59">Citizen Women's EW and Men's EW</a></h3>	
												<div class="price">
															<span class="price-old">$119.50</span> 
								<span class="price-new">$107.75</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-5.png" alt="5"></div>
					    
						<p class="description">Nineties revival reigns supreme with the spaghetti-strap&nbsp;slip dress&nbsp;stealing the what’s hot top spot.
...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('59');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('59');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('59');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

											</div>
					
									</div>
								<div class="item">
															<div class="row product-items last">
												<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5 first">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=47"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_18-215x238.jpg" title="Electrolux EL 6988D Oxygen Canister" alt="Electrolux EL 6988D Oxygen Canister"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_18.jpg" class="info-view colorbox product-zoom cboxElement" title="Electrolux EL 6988D Oxygen Canister"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=47"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=47">Electrolux EL 6988D Oxygen Canister</a></h3>	
												<div class="price">
															<span class="price-old">$119.50</span> 
								<span class="price-new">$107.75</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-3.png" alt="3"></div>
					    
						<p class="description">Stop your co-workers in their tracks with 
the stunning new 30-inch diagonal HP LP3065 Flat Panel Monitor. This 
flagship monitor features best-in-class performance and presentation 
features on a huge wide-aspect screen wh...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('47');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('47');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('47');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5">
							<div class="product-block">	
														<div class="image">
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=34"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_07-215x238.jpg" title="Dummy text of the printing and typesetting " alt="Dummy text of the printing and typesetting "></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_07.jpg" class="info-view colorbox product-zoom cboxElement" title="Dummy text of the printing and typesetting "><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=34"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=34">Dummy text of the printing and typesetting </a></h3>	
												<div class="price">
															<span class="special-price">$589.50</span>
													</div>
							
					</div>
			  
					<div class="right">		
										        <div class="norating"><img alt="0" src="/<?=SHARE?>/images/product/stars-0.png"></div>
				        
						<p class="description">Lorem Ipsum has been the industry's 
standard dummy text ever since the 1500s, when an unknown printer took a
 galley of type and scrambled it to make a type specimen book.
...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('34');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('34');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('34');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=42"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_15-215x238.jpg" title="Vans Authentic Shoes" alt="Vans Authentic Shoes"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_15.jpg" class="info-view colorbox product-zoom cboxElement" title="Vans Authentic Shoes"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=42"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=42">Vans Authentic Shoes</a></h3>	
												<div class="price">
															<span class="price-old">$119.50</span> 
								<span class="price-new">$107.75</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-5.png" alt="5"></div>
					    
						<p class="description">Since the Vans canvas deck shoe was 
released, they have remained a popular choice for anyone who wants style
 and comfort, all day long
...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('42');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('42');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('42');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5">
							<div class="product-block">	
														<div class="image">
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=33"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_06-215x238.jpg" title="Canon EOS 40D 10.1MP SLR Camera" alt="Canon EOS 40D 10.1MP SLR Camera"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_06.jpg" class="info-view colorbox product-zoom cboxElement" title="Canon EOS 40D 10.1MP SLR Camera"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=33"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=33">Canon EOS 40D 10.1MP SLR Camera</a></h3>	
												<div class="price">
															<span class="special-price">$237.00</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-5.png" alt="5"></div>
					    
						<p class="description">Imagine the advantages of going big without
 slowing down. The big 19" 941BW monitor combines wide aspect ratio with
 fast pixel response time, for bigger images, more room to work and 
crisp motion. In addition, the exclus...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('33');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('33');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('33');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5 last">
							<div class="product-block">	
														<div class="image">
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=32"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_05-215x238.jpg" title="Tiana B Women's Floral Printed Color... " alt="Tiana B Women's Floral Printed Color... "></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_05.jpg" class="info-view colorbox product-zoom cboxElement" title="Tiana B Women's Floral Printed Color... "><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=32"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=32">Tiana B Women's Floral Printed Color... </a></h3>	
												<div class="price">
															<span class="special-price">$119.50</span>
													</div>
							
					</div>
			  
					<div class="right">		
										        <div class="norating"><img alt="0" src="/<?=SHARE?>/images/product/stars-0.png"></div>
				        
						<p class="description">Proin gravida nibh vel velit auctor 
aliquet. Aenean sollicitudin, lorem quis bibendum auctor, nisi elit 
consequat ipsum, nec sagittis sem nibh id elit. Duis sed odio sit amet 
nibh vulputate cursus a sit amet mauris.
Mor...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('32');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('32');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('32');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

											</div>
					
									</div>
								<div class="item active">
															<div class="row product-items last">
												<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5 first">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=56"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_22-215x238.jpg" title="Raymond Weil Women's" alt="Raymond Weil Women's"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_22.jpg" class="info-view colorbox product-zoom cboxElement" title="Raymond Weil Women's"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=56"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=56">Raymond Weil Women's</a></h3>	
												<div class="price">
															<span class="price-old">$119.50</span> 
								<span class="price-new">$107.75</span>
													</div>
							
					</div>
			  
					<div class="right">		
										        <div class="norating"><img alt="0" src="/<?=SHARE?>/images/product/stars-0.png"></div>
				        
						<p class="description">Nineties revival reigns supreme with the spaghetti-strap&nbsp;slip dress&nbsp;stealing the what’s hot top spot.
...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('56');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('56');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('56');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=36"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_09-215x238.jpg" title="Body lotions Nineties revival" alt="Body lotions Nineties revival"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_09.jpg" class="info-view colorbox product-zoom cboxElement" title="Body lotions Nineties revival"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=36"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=36">Body lotions Nineties revival</a></h3>	
												<div class="price">
															<span class="price-old">$119.50</span> 
								<span class="price-new">$107.75</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-4.png" alt="4"></div>
					    
						<p class="description">America's #1 Body Lotion just got better! 
With 2 x the moisture and 3 x the Shea, our enhanced lotion contains 
more of what skin loves, leaving it feeling incredibly soft, smooth and 
nourished.
...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('36');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('36');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('36');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5">
							<div class="product-block">	
														<div class="image">
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=46"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_19-215x238.jpg" title="Shopper Bags Women's and Men's" alt="Shopper Bags Women's and Men's"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_19.jpg" class="info-view colorbox product-zoom cboxElement" title="Shopper Bags Women's and Men's"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=46"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=46">Shopper Bags Women's and Men's</a></h3>	
												<div class="price">
															<span class="special-price">$1,177.00</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-4.png" alt="4"></div>
					    
						<p class="description">Bag&nbsp;brings us an eclectic collection 
of fashion forward styles. Look out for vibrantly printed party dresses,
 feminine detailing,
...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('46');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('46');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('46');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=58"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_24-215x238.jpg" title="Dogeared Reminder" alt="Dogeared Reminder"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_24.jpg" class="info-view colorbox product-zoom cboxElement" title="Dogeared Reminder"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=58"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=58">Dogeared Reminder</a></h3>	
												<div class="price">
															<span class="price-old">$119.50</span> 
								<span class="price-new">$107.75</span>
													</div>
							
					</div>
			  
					<div class="right">		
											    <div class="rating"><img src="/<?=SHARE?>/images/product/stars-2.png" alt="2"></div>
					    
						<p class="description">Nineties revival reigns supreme with the spaghetti-strap&nbsp;slip dress&nbsp;stealing the what’s hot top spot.
...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('58');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('58');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('58');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

						
																<div class="col-sm-6 col-xs-12 product-cols pavcol-lg-5 last">
							<div class="product-block">	
														<div class="image">
												<span class="product-label product-label-special"><span>Sale</span></span>
												<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=57"><img class="img-responsive" src="/<?=SHARE?>/images/product/product_23-215x238.jpg" title="Citizen Women's EW and Men's EWs" alt="Citizen Women's EW and Men's EWs"></a>							
						<!-- zoom image-->
													<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_23.jpg" class="info-view colorbox product-zoom cboxElement" title="Citizen Women's EW and Men's EWs"><i class="fa fa-search-plus"></i></a>
						

						<!-- Show Swap -->
												<!-- Show Swap -->


																					<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=57"><em class="fa fa-eye"></em><span>Quick View</span></a>
													
					</div>
												 
				<div class="product-meta">		  
					<div class="left">
						<h3 class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=57">Citizen Women's EW and Men's EWs</a></h3>	
												<div class="price">
															<span class="price-old">$119.50</span> 
								<span class="price-new">$107.75</span>
													</div>
							
					</div>
			  
					<div class="right">		
										        <div class="norating"><img alt="0" src="/<?=SHARE?>/images/product/stars-0.png"></div>
				        
						<p class="description">Nineties revival reigns supreme with the spaghetti-strap&nbsp;slip dress&nbsp;stealing the what’s hot top spot.
...</p>

						<div class="action">							
							<div class="cart">						
        						
								<button onclick="addToCart('57');" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</button>
      						</div>
							
							<div class="button-group">
								<div class="wishlist">
									<a onclick="addToWishList('57');" title="Add to Wish List" class="fa fa-heart product-icon">
										<span>Add to Wish List</span>
									</a>	
								</div>
								<div class="compare">			
									<a onclick="addToCompare('57');" title="Add to Compare" class="fa fa-refresh product-icon">
										<span>Add to Compare</span>
									</a>	
								</div>
							</div>							
						</div>		 
					</div>	 
				</div>		 
			</div>
						</div>

											</div>
					
									</div>
							</div>  
		</div>
	</div> 
</div>

<script type="text/javascript">
$('#productcarousel30').carousel({interval:false,auto:false,pause:'hover'});
</script></div>
		</div>	
			
	</div>
</section>

<section id="columns">
	<div class="container">
<div class="row">

	<?php echo $this->LatestBlog(); ?>
		
<section class="col-lg-9 col-md-9 col-sm-12 col-xs-12">         
	<div id="content">
		<div class="content-top">
			<div class="box pav-custom  ">
		<div class="box-content">
		<div class="">
			<p><img alt="banner-3" class="img-responsive" src="/<?=SHARE?>/images/product/banner3.jpg"></p>
		</div>
	</div>
</div>			

  <?php foreach($this->result as $key): 
	   $product = new Product_Model_Product();
	  $items = $product->getProductsByCatId($key->id);
	?>
<div class="box nopadding pav-categoryproducts clearfix">
		<div class="box-wapper blue">
	<div class="tab-nav pull-left">
		<ul class="h-tabs" id="producttabs<?=$key->id?>">
								<li class="effect active first last">
						<a href="#" class="overlay">&nbsp;</a>
						<a href="" data-toggle="tab" class="category_name box-heading">
							<span><?=$key->label?></span>
						</a>
						<a class="hidden-xs hidden-sm" href="" data-toggle="tab">
							<img class="img-responsive" src="/<?=SHARE?>/images/menuitems/<?=$key->image?>" alt="">							
						</a>
							
					</li>
							</ul>
		</div>

			
			<div class="tab-content pull-left">  
									<div class="tab-pane  clearfix" id="tab-cattabs<?=$key->id?>">	
												<div class="carousel-controls">
							<a class="carousel-control left fa" href="#boxcats<?=$key->id?>" data-slide="prev">
								<em class="fa fa-angle-left"></em>
							</a>
							<a class="carousel-control right" href="#boxcats<?=$key->id?>" data-slide="next">
								<em class="fa fa-angle-right"></em>
							</a>
						</div>
												<div class="pavproducts<?=$key->id?> slide" id="boxcats<?=$key->id?>">
							<div class="carousel-inner">		
								<div class="item active">
									<div class="row product-items">
									  <?php
				$i = 0;
				 foreach($items as $item): 
				 $i++;
				$coverImage = $this->image()->getDefaultImageProduct($item->id);						   
										   ?>
						<div class="col-lg-3 col-md-3 col-sm-6 col-xs-12 product-cols">
							<div class="product-block">	
																																				<div class="image">
																												<a class="img" href="/<?=$item->ident?>.html"><img class="img-responsive" src="<?=$coverImage?>" title="<?=$item->name?>" alt="<?=$item->name?>"></a>							
														<!-- zoom image-->
																													<a href="<?=$coverImage?>" class="info-view colorbox product-zoom cboxElement" title="<?=$item->name?>"><i class="fa fa-search-plus"></i></a>
														
																													
													</div>
																												 
		<div class="product-meta">		  
			<div class="left">
				<h3 class="name"><a href="/<?=$item->ident?>.html"><?=$item->name?></a></h3>	
																															<div class="price">
																															<span class="special-price"><?=$this->string()->product_price('VND',$item->price);?></span>
																											
			</div>
															
		</div>
											  
			<div class="right">		

	<p class="description">Imagine the advantages of going big
 without slowing down. The big 19" 941BW monitor combines wide aspect 
ratio with fast pixel response time, for bigger images, more room to 
work and crisp motion. In addition, the exclus...</p>

														<div class="action">							
															<div class="cart">						
								        						
		<a type="submit" href="/cart/add/pid/<?php echo $item->id; ?>/qty/1" class="btn btn-shopping-cart">
									<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
								</a>
								      						</div>
															
															<div class="button-group">
																<div class="wishlist">
																	<a onclick="addToWishList('33');" title="Add to Wish List" class="fa fa-heart product-icon">
																		<span>Add to Wish List</span>
																	</a>	
																</div>
																<div class="compare">			
																	<a onclick="addToCompare('33');" title="Add to Compare" class="fa fa-refresh product-icon">
																		<span>Add to Compare</span>
																	</a>	
																</div>
															</div>							
														</div>		 
													</div>	 
												</div>		 
											</div>										
										</div>
										
										<?php
										if ($i%4==0){	
											?>
											</div></div><div class="item"><div class="row product-items">
											<? } ?>					
											<? endforeach; ?>	
									</div>
																										</div>
																
							</div>  
						</div>
					</div>		
						
				</div>
			</div>	
		</div>


		<script type="text/javascript">
			$(function () {
				$('.pavproducts'+ <?=$key->id?>).carousel({interval:99999999999999,auto:false,pause:'hover'});
				$('#producttabs' + <?=$key->id?> + ' a:first').tab('show');
			});
		</script>
			
<?php endforeach; ?>
	</div>
		<h1 style="display: none;">Pav StyleShop</h1>
			<div class="content-bottom"> 
					<div class="box pav-custom  ">
		<div class="box-content">
		<div class="">
			<p><img alt="banner-8" class="img-responsive" src="/<?=SHARE?>/images/product/banner8.jpg"></p>
		</div>
	</div>
</div>			</div>
	</div>
</section>
	
</div></div>
	
</section>