<?php echo $this->doctype(); ?> 
<html> 
<head> 
    <?php echo $this->headTitle(); ?> 
    <?php echo $this->headMeta(); ?>      
    <?php echo $this->headLink(); ?> 
    
</head> 

<body>
	<style type="text/css">
		body{
			height: 100%;
			width: 100%;
			background: #130B43;
			color: #fff;
		}
.snowflake {
  -webkit-animation: spin 4s linear infinite;
  -moz-animation: spin 4s linear infinite;
  animation: spin 4s linear infinite;
}
 @-moz-keyframes 
spin { 100% {
-moz-transform: rotate(360deg);
}
}
 @-webkit-keyframes 
spin { 100% {
-webkit-transform: rotate(360deg);
}
}
 @keyframes 
spin { 100% {
-webkit-transform: rotate(360deg);
transform:rotate(360deg);
}
}
</style>
<div class="test">Hello Zend Framework</div>
</body>
  <?php echo $this->headScript(); ?> 
<script>
			jQuery(function() {
				jQuery("body").snow({
					intensity: 40,
					sizeRange: [12, 30],
					opacityRange: [0.4, 1],
					driftRange: [10, 20],
					speedRange: [55, 120]
				});
			});
		</script>
</html>