<div id="footer">
<div class="panel-box footer">
	    <div class="row no-gutter">
	   	 	<div class="border-page-footer col-md-10 col-md-offset-1">
		  
		   	 	 <div class="row col-md-12 col-md-offset-0">
			   	 	 <div class="office-box col-md-4 npl">
			   	<span class="n2"> <img src="<?=TEMPLATE_URL?>/default/img/icon-01.png"/></span>
			   <div class="f11a1">
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>29 Doan Thi Diem., Dong Da., Hanoi., Vietnam</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>04.3682.29.29  - 04.3682.28.28</div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i>+84.98.98.98.198</div>
<div class="at1"><i class="fa fa-envelope iconvne" aria-hidden="true"></i>info@hoabinhtourist.com</div>

			   </div>
		   	 	</div>
			   	 	 <div class="office-box col-md-4 npl">
		  	<span class="n2"> <img src="<?=TEMPLATE_URL?>/default/img/icon-02.png"/></span>
			   <div class="f11a1">
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>61 Huynh Thuc Khang., Hai Chau., Da Nang., Vietnam</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>0236.399.61.16 </div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i>+84.905.388.666</div>
<div class="at1"><i class="fa fa-envelope iconvne" aria-hidden="true"></i>info@danangevents.com.vn</div>

			   </div>
			   	 <!--	<a href="#" />
			   	 		<img src="http://vietnamevents.com/images/memberof.png" />
			   	 	</a>-->
		   	 	</div>
		   	 	
			   	 	 <div class="office-box col-md-4 npl">
		<span class="n2"> <img src="<?=TEMPLATE_URL?>/default/img/icon-03.png"/></span>
<div class="f11a1">			   	 	
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>23 Dao Duy Anh str, Phu Nhuan dist., HCM city</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>08.3995.8162 - 08.3995.8163</div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i>+84.98.98.98.198</div>
<div class="at1"><i class="fa fa-envelope iconvne" aria-hidden="true"></i>info@hoabinh-group.com</div>
		   	 	</div>
		   	 	</div>
		   	 	 </div>
		   	 	<div class="row col-md-12 col-md-offset-0">
			   
		   	 	</div>
		   	 	 <div class="col-menu-footer col-md-12 col-md-offset-0">
			   	 	
		   	 	<div class="col-md-12 menu-footer">
			   	 	 <div class="row">

		   	 	<ul class="list-inline pull-left">
			   
    				<li><a href="/"><?php echo $this->translate('home'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('about'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('activity'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('news'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('rec'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('contact'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('membership'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('gallery'); ?></a></li>					
					
				</ul>
		   	 		</div>
		   	 	</div>	
		   	 		
		   	 	<div class="col-md-12 newsletter">
			   	 	<div class="row">
			   	 	<div class="col-md-2 col-sm-12 register">
				   	 	<div class="row">
				   	 	<img src="<?=TEMPLATE_URL?>/default/img/email.png" />
				   	 	<span><?php echo $this->translate('register_newsletter_from'); ?><br/> Hòa Bình Group</span>
				   	 
				   	 	</div></div>
				   	 	<div class="row">
			   	 	<div class="col-md-8 col-xs-12">
				   	 	
				   	 	<div class="register-info col-md-5">
				   	 	<span><?php echo $this->translate('update_fastest_promotion_infomation %s special_promotion', '<br/>'); ?>
				 </span>
				   	 	</div>
				   	 	<div style="margin-top: 5px;margin-left: -20px" class="form-newsletter col-md-7 col-xs-12">
					   	 	<input type="text" placeholder="<?php echo $this->translate('input_email_promotion'); ?>" />
					   	 	<input type ="submit" value="<?php echo $this->translate('register'); ?>" />
				   	 	</div>
				   	 	
				   	 	</div>
				   	 
			   	 	<div class="col-md-2 col-xs-12 social">
				   	 	<div class="row">
					 <ul class="social-list list-inline">
				   	 <li>	<a rel="nofollow" href="https://www.facebook.com/events.hoabinhgroup/"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>  </li>
				   	 <li>	<a rel="nofollow" href="https://plus.google.com/100126685922991503903"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
				   	 	<li><a rel="nofollow" href="https://www.youtube.com/watch?v=plps-87C-pY&list=PLWZR9jhepmax8F7QVxoVcWpG3qkdFmg4j"><i class="fa fa-youtube-square" aria-hidden="true"></i></a></li>
				   	 <li>	<a rel="nofollow" href="+84989898198"><i class="fa fa-whatsapp" aria-hidden="true"></i></a></li>
				   	 <li>	<a rel="nofollow" href="Jackiehan29"><i class="fa fa-weixin" aria-hidden="true"></i></a></li>
				   	 <li>	<a rel="nofollow" href="touroperator68"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
					   	 	</ul>
				   	 	
			   	 	
				   	 	</div>
				   	 </div>
				   	 	</div>
			   	 	</div>
		   	 	</div>
		   	 	
		   	 	
		   	
	   	 	</div>
	    </div>
      </div>
    
</div>
</div>

<div class="col-md-12 col-sm-12 copyright">
	    	 <div class="col-md-10 col-md-offset-1" style ="height: 70px; overflow: hidden;">
			   	 <div class="col-md-5 cl">Copyright 2015 Hòa Bình Group - All Right Reserved</div>	
			   	 	
			   	 <div class="col-md-7">
				   	 <ul class="bottom_links pull-right">
							<li><img width="70" height="30" src="http://hoabinh-group.com/public/images/pata_small.jpg"></li>
							<li> <img width="70" height="30" src="http://hoabinh-group.com/public/images/japan-circle.jpg"></li>
							<li><img width="70" height="30" src="http://hoabinhtourist.com/images/hanoi_vnesco_travel.png"></li>
							<li><img width="70" height="30" src="http://hoabinhtourist.com/images/vcci.png"></li>
							<li style="background: #fff;height: 40px"><img width="70" height="30" src="http://hoabinhtourist.com/images/VISTA2015.png"></li>
				
						</ul>
			   	 </div>	
			   </div>
		   </div>
		
       <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   <script type="text/javascript">
	
$(window).scroll(function() {
    if ($(this).scrollTop() > 180) {
	    
        $('#header-top').fadeIn(200);
        $('.navbar-brand').hide();
    } else {
       // $('#go_top').fadeOut(100);
       $('#header-top').hide();
       $('.navbar-brand').show();
        }
}); // ')' is missing here**      

	 </script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?=TEMPLATE_URL?>/default/js/bootstrap.min.js"></script>
    <script src="<?=TEMPLATE_URL?>/default/js/bootstrap-tabcollapse.js"></script>
    
    
    <?php echo $this->headScript() ?>
    <script type="text/javascript">
	    
	    if ($(window).width() < 600) {
   //alert('Less than 600');
}
else {
     $('ul.nav li.dropdown').hover(function() {
  $(this).find('.dropdown-menu').stop(true, true).delay(100).fadeIn('fast');
}, function() {
  $(this).find('.dropdown-menu').stop(true, true).delay(100).fadeOut('fast');
});
}


$('#services_tab').tabCollapse();
//$('#review_tab').tabCollapse();
$('#activity_tab').tabCollapse();
    </script>
    
  </body>
</html>