<div id="footer">
<div class="panel-box footer">
	    <div class="row no-gutter">
	   	 	<div class="border-page-footer col-md-10 col-md-offset-1">
		  
		   	 	 <div class="row col-md-12 col-md-offset-0">
			   	 	 <div class="office-box col-md-4 npl">
			   	<span class="n2"> <img src="<?=TEMPLATE_URL?>/default/img/icon-01.png"/></span>
			   <div class="f11a1">
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>29 Doan Thi Diem str, Dong Da dist.</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>024.3732.5976 - 024.3732.5978</div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i>+84.913.311.911</div>
<div class="at1"><i class="fa fa-envelope iconvne" aria-hidden="true"></i>info@hoabinhtourist.com</div>

			   </div>
		   	 	</div>
			   	 	 <div class="office-box col-md-4 npl">
		  	<span class="n2"> <img src="<?=TEMPLATE_URL?>/default/img/icon-02.png"/></span>
			   <div class="f11a1">
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>217 Tran Phu str, Hai Chau dist.</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>0236.399.6116 - 0236.399.6226 </div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i>+84.913.186.829</div>
<div class="at1"><i class="fa fa-envelope iconvne" aria-hidden="true"></i>info@danangevents.com.vn</div>

			   </div>
			   	 <!--	<a href="#" />
			   	 		<img src="http://vietnamevents.com/images/memberof.png" />
			   	 	</a>-->
		   	 	</div>
		   	 	
			   	 	 <div class="office-box col-md-4 npl">
		<span class="n2"> <img src="<?=TEMPLATE_URL?>/default/img/icon-03.png"/></span>
<div class="f11a1">			   	 	
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>05 Hoa Cau str, Phu Nhuan dist.</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>028.3517.8383 - 028.3527.1797 </div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i>+84.98.98.98.198</div>
<div class="at1"><i class="fa fa-envelope iconvne" aria-hidden="true"></i>info@hoabinh-group.com</div>
		   	 	</div>
		   	 	</div>
		   	 	 </div>
		   	 	<div class="row col-md-12 col-md-offset-0">
			   
		   	 	</div>
		   	 	 <div class="col-menu-footer col-md-12 col-md-offset-0">
			   	 	
		   	 	<div class="col-md-12 menu-footer">
			   	 	 <div class="row">

		   	 	<ul class="list-inline pull-left">
			   
    				<li><a href="/"><?php echo $this->translate('home'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('about'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('activity'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('news'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('rec'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('contact'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('membership'); ?></a></li>
					<li><a href="#"><?php echo $this->translate('gallery'); ?></a></li>					
					
				</ul>
		   	 		</div>
		   	 	</div>	
		   	 		
		   	 	<div class="col-md-12 newsletter">
			   	 	<div class="row">
			   	 	<div class="col-md-2 col-sm-12 register">
				   	 	<div class="row">
				   	 	<img src="/public/templates/news2017/default/img/email.png">
				   	 	<span>Đăng ký nhận tin từ<br> Hòa Bình Group</span>
				   	 
				   	 	</div></div>
				   	 	<div class="">
			   	 	<div class="col-md-7 col-xs-12">
				   	 	
				   	 	<div class="register-info col-md-5 npl npr">
				   	 	<span>Cập nhật tin khuyến mãi nhanh nhất <br> Hưởng quyền lợi giảm giá đặc biệt				 </span>
				   	 	</div>
				   	 	<div style="margin-top: 5px;" class="form-newsletter col-md-6 col-xs-12">
					<form action="http://send.timnhanh360.com/public/lists/59b95015681c8/embedded-form-subscribe-captcha" method="POST" class="">   	 	
					   	 	<div class="form-group">
				<input type="text" class="form-control" id="EMAIL" name="EMAIL" required pattern="[^@]+@[^@]+\.[a-zA-Z]{2,6}" placeholder="Nhập email hưởng ưu đãi">
				<input type="submit" class="btn" value="Đăng ký">

					   	 	</div>
					</form>   	 	
				   	 	</div>
				   	 	
				   	 	</div>
				   	 
			   	 	<div class="col-md-3 col-xs-12 social">
				   	 	<div class="row">
					 <ul class="social-list list-inline">
				   	 <li>	<a target="_blank" rel="nofollow" href="https://www.facebook.com/events.hoabinhgroup/"><i class="fa fa-facebook-square" aria-hidden="true"></i></a>  </li>
				   	 <li>	<a target="_blank" rel="nofollow" href="https://plus.google.com/100126685922991503903"><i class="fa fa-google-plus-square" aria-hidden="true"></i></a></li>
				   	 	<li><a target="_blank" rel="nofollow" href="https://www.youtube.com/watch?v=plps-87C-pY&amp;list=PLWZR9jhepmax8F7QVxoVcWpG3qkdFmg4j"><i class="fa fa-youtube-square" aria-hidden="true"></i></a></li>
				   	 <li>	<a rel="nofollow" href="+84989898198"><i class="fa fa-whatsapp" aria-hidden="true"></i></a></li>
				   	 <li>	<a rel="nofollow" href="Jackiehan29"><i class="fa fa-weixin" aria-hidden="true"></i></a></li>
				   	 <li>	<a rel="nofollow" href="touroperator68"><i class="fa fa-skype" aria-hidden="true"></i></a></li>
					   	 	</ul>
				   	 	
			   	 	
				   	 	</div>
				   	 </div>
				   	 	</div>
			   	 	</div>
		   	 	</div>
		   	 	
		   	 	
		   	
	   	 	</div>
	    </div>
      </div>
    
</div>
</div>
<div id="back-to-top" class="back-to-top" data-toggle="tooltip" data-placement="left" title="Trở lên đầu trang"><span class="glyphicon glyphicon-circle-arrow-up text-primary"></span></div>

<div class="col-md-12 col-sm-12 copyright">
	    	 <div class="col-md-10 col-md-offset-1" style ="height: 70px; overflow: hidden;">
			   	 <div class="col-md-5 cl">Copyright 2015 Hòa Bình Group - All Right Reserved</div>	
			   	 	
			   	 <div class="col-md-7">
				   	 <ul class="bottom_links pull-right">
							<li><img width="70" height="30" src="http://hoabinh-group.com/public/images/pata_small.jpg"></li>
							<li> <img width="70" height="30" src="http://hoabinh-group.com/public/images/japan-circle.jpg"></li>
							<li><img width="70" height="30" src="http://hoabinhtourist.com/images/hanoi_vnesco_travel.png"></li>
							<li><img width="70" height="30" src="http://hoabinhtourist.com/images/vcci.png"></li>
							<li style="background: #fff;height: 40px"><img width="70" height="30" src="http://hoabinhtourist.com/images/VISTA2015.png"></li>
				
						</ul>
			   	 </div>	
			   </div>
		   </div>
		
       <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
   <script type="text/javascript">
	
$(window).scroll(function() {
    if ($(this).scrollTop() > 180) {
	    
        $('#header-top').fadeIn(200);
        $('.navbar-brand').hide();
    } else {
       // $('#go_top').fadeOut(100);
       $('#header-top').hide();
       $('.navbar-brand').show();
        }
}); // ')' is missing here**      

	 </script>
	    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="<?=TEMPLATE_URL?>/default/js/bootstrap.min.js"></script>
    <script src="<?=TEMPLATE_URL?>/default/js/bootstrap-tabcollapse.js"></script>
    
    
    <?php echo $this->headScript() ?>
    <script type="text/javascript">
	    
	    if ($(window).width() < 600) {
   //alert('Less than 600');
}
else {
     $('ul.nav li.dropdown').hover(function() {
  $(this).find('.dropdown-menu').stop(true, true).delay(100).fadeIn('fast');
}, function() {
  $(this).find('.dropdown-menu').stop(true, true).delay(100).fadeOut('fast');
});
}


$('#services_tab').tabCollapse();
//$('#review_tab').tabCollapse();
$('#activity_tab').tabCollapse();

$("#back-to-top").click(function(){return $("body, html").animate({scrollTop:0},400),!1});
$(function(){$('[data-toggle="tooltip"]').tooltip()});
    </script>
    
    <script type='text/javascript'>window._sbzq||function(e){e._sbzq=[];var t=e._sbzq;t.push(["_setAccount",67985]);var n=e.location.protocol=="https:"?"https:":"http:";var r=document.createElement("script");r.type="text/javascript";r.async=true;r.src=n+"//static.subiz.com/public/js/loader.js";var i=document.getElementsByTagName("script")[0];i.parentNode.insertBefore(r,i)}(window);</script>
  </body>
</html>