
	    	<div id="menu">
		    	<div class="panel-box">

		    <nav class="navbar">
			    	<div class="hotline">					
                        <span class="pull-right">
                        <img height="24" src= '<?=TEMPLATE_URL?>/default/img/icon hotline.png'/> 
                        <b>+84.913.311.911</b>
                         <img height="24" src= '<?=TEMPLATE_URL?>/default/img/Vietnam_flat.png'/>	
                        <img height="24" src= '<?=TEMPLATE_URL?>/default/img/United-Kingdom_flat.png'/>
                        </span>
                       	
                    </div>
                   
                 
  
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    
    </div>
  

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <div class="hidden-phone" style="margin-top: 66px;">&nbsp;</div>
     <!-- <ul class="nav navbar-nav">
        <li class="current"><a href="#">Home <span class="sr-only">(current)</span></a></li>
        <li><a href="#">AboutUs</a></li>
        <li class="dropdown">
          <a href="/" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Services <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
        <li><a href="#">Gallery</a></li>
        <li><a href="#">Client & Testimonials</a></li>
        <li><a href="#">Join Us</a></li>
        <li><a href="#">Contact</a></li>
      </ul>-->
   <ul class="nav navbar-nav">
     <li><a href="/">Giới thiệu</a></li>
     <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/about-us/index">Lĩnh vực hoạt động <span class="caret"></span></a>
     	<ul class="dropdown-menu">
	     <li><a href="/about-us">About us</a></li>
		 <li><a href="/our-core-values">Our Core Values</a></li>
		 <li><a href="/mission-vision">Mission - Vision</a></li>
		 <li><a href="/achievements">Achievements</a></li>
	 	</ul>
	 </li>
	 <li class="dropdown">
	 <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/services">Tin tức <span class="caret"></span></a>
	   <ul class="dropdown-menu">
		   <li><a href="/events-management">Events Management</a></li>
		   <li><a href="/conference-management">Conference Management</a></li>
		   <li><a href="/event-staffing-services">Event Staffing Services</a></li>
		   <li><a href="/av-equipments-supply">AV equipments supply</a></li>
		   <li><a href="/other-event-equipments-supply">Other Event Equipments Supply</a></li><li><a href="/entertainment-services">Entertainment Services</a></li>
		   <li><a href="/product-launches">Product Launches</a></li>
		   <li><a href="/brand-activations">Brand Activations</a></li>
		   <li><a href="/teambuilding-and-outings">Teambuilding and Outings</a></li>
		   <li><a href="/incentive-travel">Incentive Travel</a></li>
		   <li><a href="/corporate-and-business-travel">Corporate and Business Travel</a></li>
		</ul></li>
		
   </ul>
   <div class="logo">
		   <a class="navbar-brand" href="/">
	       <img width="220" src="<?=TEMPLATE_URL?>/default/img/logo-01.png" />
		   </a>

   </div>
	<ul class="nav navbar-nav nav-after">
		<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/gallery-index">Tuyển dụng <span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><a href="/gallery">Gallery</a></li>
				<li><a href="/video">Video</a></li>
			</ul>
		</li>
		<li><a href="/clients-testimonials">Liên hệ</a></li>
		<li><a href="/contact">Membership Card</a></li>  
		   </ul>
    </div><!-- /.navbar-collapse -->
  
</nav>

    	 
	    
				   
		    	</div> 	 
	    	</div><!-- #menu-->
	    	<!-- #slider -->
	    	<div id="slider">
		     <div class="panel-box">
    <div class="row no-gutter">
		
		   
    <div id="myCarousel" class="carousel slide" data-interval="3000" data-ride="carousel">
    <!-- Carousel indicators -->
    <ol class="carousel-indicators">
	    	            <li data-target="#myCarousel" data-slide-to="0"  class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1" ></li>
                <li data-target="#myCarousel" data-slide-to="2" ></li>
                <li data-target="#myCarousel" data-slide-to="3" ></li>
       
         
            </ol>   
    <!-- Carousel items -->
    <div class="carousel-inner">
	            <div class="item active">
            <img class="img-responsive" src="http://timnhanh360.com/hbg/img/slide/slide-2.png" alt="01.jpg">
            
        </div>
                <div class="item ">
            <img class="img-responsive" src="http://timnhanh360.com/hbg/img/slide/slide-1.png" alt="02.jpg">
            
        </div>
                <div class="item ">
            <img class="img-responsive" src="http://timnhanh360.com/hbg/img/slide/slide-3.png" alt="03.jpg">
            
        </div>
           <div class="item ">
            <img  src="http://timnhanh360.com/hbg/img/slide/slide-4.png" alt="04.jpg">
            
        </div>
              
              
    </div>
    <style>
	    img.desaturate {
	
}
	  </style>

    <!-- Carousel nav -->
   <a class="left carousel-control slider-header" href="http://hoabinh-group.com/#myCarousel" data-slide="prev"> <img src="<?=TEMPLATE_URL?>/default/img/btn-l.png" /> </a> <a class="right carousel-control slider-header" href="http://hoabinh-group.com/#myCarousel" data-slide="next"><img src="<?=TEMPLATE_URL?>/default/img/btn-r.png" />  </a> 
</div>
		    
	    
    </div>
    </div>	
		    	
	    	</div><!-- #slider -->
			<!-- #end_slider -->

	    	
	    	
    	