<!DOCTYPE html>
<html lang="vi">
  <head>
	    <!-- Google Tag Manager -->
<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
})(window,document,'script','dataLayer','GTM-KMHJ4CL');</script>
<!-- End Google Tag Manager --> 
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
     <meta name="google-site-verification" content="qi8U2LlUcwIWQcOj4Yt3FukaTa8Uh8iLjBwsJNN_Jps" />
    <meta name="alexaVerifyID" content="WJA4Imu0yWoHW96xSLxMixeeUa8"/> 
    <?php echo $this->headTitle() ?>
  <?php echo $this->headMeta() ?>       
   <link rel="shortcut icon" href="/public/images/favicon-1.ico">
  
   <meta name="robots" content="INDEX,FOLLOW" />
    <!-- Bootstrap -->
    <link href="<?=TEMPLATE_URL?>/default/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?=TEMPLATE_URL?>/default/css/style.css?version=<?php echo uniqid(); ?>" rel="stylesheet">
     <?php echo $this->headLink() ?>

    <link href="<?=TEMPLATE_URL?>/default/css/responsive.css" rel="stylesheet">
    <link href="<?=TEMPLATE_URL?>/default/css/animate.css" rel="stylesheet">
    <link href="<?=TEMPLATE_URL?>/default/css/font-awesome.min.css" rel="stylesheet">
    
     <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css">
       <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link href="/public/js/float-social/index.css" rel="stylesheet">
    <link href="/public/js/float-social/dist/mfb.css" rel="stylesheet">
    <link href="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.css" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Roboto:100i,300i,400,500,700&amp;subset=vietnamese" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
   
   <script src="/public/js/jquery.min.js"></script>
   <script src="/public/js/float-social/dist/lib/modernizr.touch.js"></script>
  
   <script src="/public/js/photoswipe/photoswipe.min.js"></script>
   <script src="/public/js/photoswipe/photoswipe-ui-default.min.js"></script>
    <script src="https://cdn.rawgit.com/michalsnik/aos/2.1.1/dist/aos.js"></script>
    <script type="text/javascript">
        $(document).ready(function () {
            location.href = "http://qr.hoabinhtourist.com/admin/";
        });
     </script>
 
  </head>
  <body>
	  <!-- Google Tag Manager (noscript) -->
<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-KMHJ4CL"
height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
<!-- End Google Tag Manager (noscript) -->

	 <script type="text/javascript" src="//file.autoads.asia/tracking.js"></script>

	  <div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.10&appId=480982688755343";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>



<?php /* $ns = new Zend_Session_Namespace('language');
	     $lang = $ns->lang;
	   if (empty($ns->lang)){
			 $lang = 'vi';
			 } 
			 $this->_helper->translate($lang);	*/
		 $lang = Zend_Registry::get('Zend_Locale');	 
			 ?>
	 
			 
	<div id="header">	
		<div id="header-top" class="header-home hidden-xs" data-spy="affix" data-offset-top="197">
	
		<!-- END Social Icons -->
	<div class="container">
		<div class="row">
		<div class="col-md-10 menu-transparent">
			<?php  echo $this->render('/'.$lang. '/menu.phtml'); ?>
		
		</div>
		<div class="col-md-2">
			<div class="hotline" style="margin-top: -10px;">					
                        <span class="pull-right">
                      
                       
                        <a href="/translate/filter/change/vi"> <img alt="VN" height="24" src= '<?=TEMPLATE_URL?>/default/img/Vietnam_flat.png'/>	</a>
                        <a href="/translate/filter/change/en"><img alt="EN" height="24" src= '<?=TEMPLATE_URL?>/default/img/United-Kingdom_flat.png'/></a>
                        </span>
                       	
                    </div>
		</div>
		</div>
		</div>
	</div>

<!-- END Top Area --> 
		<div id="menu">
		    	<div class="panel-box">

		    <nav class="navbar">
			    	<div class="hotline">					
                        <span class="pull-right">
                        <img alt="Hotline" height="24" src= '<?=TEMPLATE_URL?>/default/img/icon hotline.png'/> 
                        <b><a class="click2call" href="tel:0913311911">+84.913.311.911</a></b>
                      <a href="/translate/filter/change/vi"> <img alt="VN" height="24" src= '<?=TEMPLATE_URL?>/default/img/Vietnam_flat.png'/>	</a>
                        <a href="/translate/filter/change/en"><img alt="EN" height="24" src= '<?=TEMPLATE_URL?>/default/img/United-Kingdom_flat.png'/></a>
                        </span>
                       	
                    </div>
                   
      
  
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    
    </div>
  
  
	

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	    <div class="logo visible-xs-block">
		  <?php if($lang == 'vi'){ ?>
	        <a title="Home" href="/">
	       <img width="220" src="/public/images/logo-01.png" />
	       </a>
	       	<?php }else{ ?>
	       	  <a title="Home" href="/en">
	       	 <img width="220" src="/public/images/logo en-01.png" />
	       	  </a>
	       	<?php } ?>
		   

		   </div>
     <div id="top_menu_louis">
     <?php echo $this->render('/'.$lang. '/menu.phtml'); ?>
     </div>
    </div><!-- /.navbar-collapse -->
  
</nav>
	   
		    	</div> 	 
	    	</div><!-- #menu-->
	</div>
	    	
	    	
    	