	<?php echo $this->render('header.phtml'); ?>
		<style>
			#contactForm{
				margin-left: 68px;
			}
			.top h3{
					font-size: 2.1em;
					margin: 20px 0px;
				}
			#contactForm input{
				margin-top: 5px;
				margin-bottom: 10px;
				border: 1px solid #979191;
				padding: 5px;
			}
			#contactForm textarea{
				margin-top: 5px;
				margin-bottom: 10px;
				border: 1px solid #979191;
				padding: 5px;
			}
			#submit_default button{
				padding: 10px;
			}
			#submit_default a{
				padding: 10px;
			}
		</style>
	
		<?php echo $this->layout()->content; ?>  

	
	 
				
		
	    	
	<?php echo $this->render('footer.phtml'); ?>