<html class='v2' dir='ltr' xmlns='http://www.w3.org/1999/xhtml' xmlns:b='http://www.google.com/2005/gml/b' xmlns:data='http://www.google.com/2005/gml/data' xmlns:expr='http://www.google.com/2005/gml/expr'>
<head>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1' name='viewport' />
    <meta content='text/html; charset=utf-8' http-equiv='Content-Type' />
    <meta content='blogger' name='generator' />
    <link href='/public/images/favicon-1.ico' rel='icon' type='image/x-icon' />

    <meta content='http://hoabinh-group.com/pages/8-3' property='og:url' />
    <meta content='Ưu đãi đặc biệt ngày quốc tế phụ nữ 8-3' property='og:title' />
    <meta content='' property='og:description' /><!--[if IE]> <script> (function() { var html5 = ("abbr,article,aside,audio,canvas,datalist,details," + "figure,footer,header,hgroup,mark,menu,meter,nav,output," + "progress,section,time,video").split(','); for (var i = 0; i < html5.length; i++) { document.createElement(html5[i]); } try { document.execCommand('BackgroundImageCache', false, true); } catch(e) {} })(); </script> <![endif]-->

    <title>Ưu đãi đặc biệt ngày quốc tế phụ nữ 8-3</title>
    <script type='text/javascript'>
//<![CDATA[
    //CSS Ready
    function loadCSS(e, t, n) { "use strict"; var i = window.document.createElement("link"); var o = t || window.document.getElementsByTagName("script")[0]; i.rel = "stylesheet"; i.href = e; i.media = "only x"; o.parentNode.insertBefore(i, o); setTimeout(function () { i.media = n || "all" }) }
    loadCSS("https://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400italic,500,500italic,700,700italic,900,900italic&amp;subset=latin,vietnamese,latin-ext");loadCSS("http://fonts.googleapis.com/css?family=Roboto+Condensed:400,700");loadCSS("https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css");
    //]]>
    </script>
    <script src='/page/8-3/js/jquery.min.js' type='text/javascript'>
</script>
    <script src='/page/8-3/js/bootstrap.min.js' type='text/javascript'>
</script>
	
    <script src='/page/8-3/js/jquery.parallax-1.1.3.js' type='text/javascript'>
</script>
    <script src='/page/8-3/js/owl.carousel.js' type='text/javascript'>
</script>
    <script src='/page/8-3/js/resize.js' type='text/javascript'>
</script>
    <script src='/page/8-3/js/off-canvas.js' type='text/javascript'>
</script>
    <script src='/page/8-3/js/jquery.isotope.min.js' type='text/javascript'>
</script>
    <script src='/page/8-3/js/jquery.flexslider.js' type='text/javascript'>
</script>


<!-- Add mousewheel plugin (this is optional) -->
	<script type="text/javascript" src="/page/8-3/lib/jquery.mousewheel.pack.js?v=3.1.3"></script>

	<!-- Add fancyBox main JS and CSS files -->
	<script type="text/javascript" src="/page/8-3/source/jquery.fancybox.pack.js?v=2.1.5"></script>
	<link rel="stylesheet" type="text/css" href="/page/8-3/source/jquery.fancybox.css?v=2.1.5" media="screen" />

	<!-- Add Button helper (this is optional) -->
	<link rel="stylesheet" type="text/css" href="/page/8-3/source/helpers/jquery.fancybox-buttons.css?v=1.0.5" />
	<script type="text/javascript" src="/page/8-3/source/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>

	<!-- Add Thumbnail helper (this is optional) -->
	<link rel="stylesheet" type="text/css" href="/page/8-3/source/helpers/jquery.fancybox-thumbs.css?v=1.0.7" />
	<script type="text/javascript" src="/page/8-3/source/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>

	<!-- Add Media helper (this is optional) -->
	<script type="text/javascript" src="/page/8-3/source/helpers/jquery.fancybox-media.js?v=1.0.6"></script>


    <script src='/page/8-3/js/custom.js' type='text/javascript'>
</script><!-- Styles -->
    <link rel="stylesheet" type="text/css" href="/page/8-3/css/style.css" />
    <link rel="stylesheet" type="text/css" href="/page/8-3/css/responsive.css" />

</script>
    <style type="text/css">
/*<![CDATA[*/
    div.jGrowl{z-index:9999;color:#fff;font-size:12px}
    div.ie6{position:absolute}
    div.ie6.top-right{right:auto;bottom:auto;left:expression((0 - jGrowl.offsetWidth+(document.documentElement.clientWidth ? document.documentElement.clientWidth:document.body.clientWidth)+(ignoreMe2 = document.documentElement.scrollLeft ? document.documentElement.scrollLeft:document.body.scrollLeft))+'px');top:expression((0+(ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop:document.body.scrollTop))+'px')}
    div.ie6.top-left{left:expression((0+(ignoreMe2 = document.documentElement.scrollLeft ? document.documentElement.scrollLeft:document.body.scrollLeft))+'px');top:expression((0+(ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop:document.body.scrollTop))+'px')}
    div.ie6.bottom-right{left:expression((0 - jGrowl.offsetWidth+(document.documentElement.clientWidth ? document.documentElement.clientWidth:document.body.clientWidth)+(ignoreMe2 = document.documentElement.scrollLeft ? document.documentElement.scrollLeft:document.body.scrollLeft))+'px');top:expression((0 - jGrowl.offsetHeight+(document.documentElement.clientHeight ? document.documentElement.clientHeight:document.body.clientHeight)+(ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop:document.body.scrollTop))+'px')}
    div.ie6.bottom-left{left:expression((0+(ignoreMe2 = document.documentElement.scrollLeft ? document.documentElement.scrollLeft:document.body.scrollLeft))+'px');top:expression((0 - jGrowl.offsetHeight+(document.documentElement.clientHeight ? document.documentElement.clientHeight:document.body.clientHeight)+(ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop:document.body.scrollTop))+'px')}
    div.ie6.center{left:expression((0+(ignoreMe2 = document.documentElement.scrollLeft ? document.documentElement.scrollLeft:document.body.scrollLeft))+'px');top:expression((0+(ignoreMe = document.documentElement.scrollTop ? document.documentElement.scrollTop:document.body.scrollTop))+'px');width:100%}
    div.jGrowl{position:absolute}
    body>div.jGrowl{position:fixed}
    div.jGrowl.top-left{left:0;top:0}
    div.jGrowl.top-right{right:0;top:0}
    div.jGrowl.bottom-left{left:0;bottom:0}
    div.jGrowl.bottom-right{right:0;bottom:0}
    div.jGrowl.center{top:0;width:50%;left:25%}
    div.center div.jGrowl-notification,div.center div.jGrowl-closer{margin-left:auto;margin-right:auto}
    div.jGrowl div.jGrowl-notification,div.jGrowl div.jGrowl-closer{background-color: #ffffff;color: #828282;zoom: 1;width: 300px;padding: 15px;margin-top: 5px;margin-bottom: 5px;font-size: 1em;text-align: left;display: none;-webkit-border-radius: 3px; -moz-border-radius: 3px; -o-border-radius: 3px;  border-radius: 3px; border: 1px solid #dadada;}
    div.jGrowl div.jGrowl-notification{min-height:40px;position:relative}
    div.jGrowl div.jGrowl-notification,div.jGrowl div.jGrowl-closer{margin:20px 40px;}
    div.jGrowl div.jGrowl-notification div.jGrowl-header{font-weight:bold;font-size:.85em}
    div.jGrowl div.jGrowl-notification div.jGrowl-close{z-index:99;position:absolute;top:10px;left:10px;font-size:14px;cursor:pointer;display:block;color:#ff4557;}
    div.jGrowl div.jGrowl-notification div.jGrowl-close:hover{color: #A43641;}
    div.jGrowl div.jGrowl-notification div.jGrowl-close .icon-remove-circle{display:block;}
    div.jGrowl div.jGrowl-notification div.jGrowl-message{display:inline-block}
    div.jGrowl div.jGrowl-notification div.jGrowl-message img{max-width:100%}
    div.jGrowl div.jGrowl-notification .jGrowl-title{margin:0;padding:0}
    div.jGrowl div.jGrowl-notification .jGrowl-note{margin-top:5px; text-transform:uppercase}
    div.jGrowl div.jGrowl-notification .jGrowl-note a{color: #828282;}
    div.jGrowl div.jGrowl-notification .jGrowl-note a:hover{color: #0186c8;}
    div.jGrowl div.jGrowl-closer{padding-top:4px;padding-bottom:4px;cursor:pointer;font-size:.9em;font-weight:bold;text-align:center;color: #1e1e1e;}
    div.jGrowl div.jGrowl-closer:hover{color: #828282;}
    @media print{div.jGrowl{display:none}}
    /*]]>*/
    </style>
    <style type="text/css">
/*<![CDATA[*/
    /* clear first in row in ie 8 or lower */
    .multi-columns-row .first-in-row {
    clear: left;
    }

    /* clear the first in row for any block that has the class "multi-columns-row" */
    .multi-columns-row .col-xs-6:nth-child(2n + 3) { clear: left; }
    .multi-columns-row .col-xs-4:nth-child(3n + 4) { clear: left; }
    .multi-columns-row .col-xs-3:nth-child(4n + 5) { clear: left; }
    .multi-columns-row .col-xs-2:nth-child(6n + 7) { clear: left; }
    .multi-columns-row .col-xs-1:nth-child(12n + 13) { clear: left; }

    @media (min-width: 768px) {
    /* reset previous grid */
    .multi-columns-row .col-xs-6:nth-child(2n + 3) { clear: none; }
    .multi-columns-row .col-xs-4:nth-child(3n + 4) { clear: none; }
    .multi-columns-row .col-xs-3:nth-child(4n + 5) { clear: none; }
    .multi-columns-row .col-xs-2:nth-child(6n + 7) { clear: none; }
    .multi-columns-row .col-xs-1:nth-child(12n + 13) { clear: none; }

    /* clear first in row for small columns */
    .multi-columns-row .col-sm-6:nth-child(2n + 3) { clear: left; }
    .multi-columns-row .col-sm-4:nth-child(3n + 4) { clear: left; }
    .multi-columns-row .col-sm-3:nth-child(4n + 5) { clear: left; }
    .multi-columns-row .col-sm-2:nth-child(6n + 7) { clear: left; }
    .multi-columns-row .col-sm-1:nth-child(12n + 13) { clear: left; }
    }
    @media (min-width: 992px) {
    /* reset previous grid */
    .multi-columns-row .col-sm-6:nth-child(2n + 3) { clear: none; }
    .multi-columns-row .col-sm-4:nth-child(3n + 4) { clear: none; }
    .multi-columns-row .col-sm-3:nth-child(4n + 5) { clear: none; }
    .multi-columns-row .col-sm-2:nth-child(6n + 7) { clear: none; }
    .multi-columns-row .col-sm-1:nth-child(12n + 13) { clear: none; }

    /* clear first in row for medium columns */
    .multi-columns-row .col-md-6:nth-child(2n + 3) { clear: left; }
    .multi-columns-row .col-md-4:nth-child(3n + 4) { clear: left; }
    .multi-columns-row .col-md-3:nth-child(4n + 5) { clear: left; }
    .multi-columns-row .col-md-2:nth-child(6n + 7) { clear: left; }
    .multi-columns-row .col-md-1:nth-child(12n + 13) { clear: left; }
    }
    @media (min-width: 1200px) {
    /* reset previous grid */
    .multi-columns-row .col-md-6:nth-child(2n + 3) { clear: none; }
    .multi-columns-row .col-md-4:nth-child(3n + 4) { clear: none; }
    .multi-columns-row .col-md-3:nth-child(4n + 5) { clear: none; }
    .multi-columns-row .col-md-2:nth-child(6n + 7) { clear: none; }
    .multi-columns-row .col-md-1:nth-child(12n + 13) { clear: none; }

    /* clear first in row for large columns */
    .multi-columns-row .col-lg-6:nth-child(2n + 3) { clear: left; }
    .multi-columns-row .col-lg-4:nth-child(3n + 4) { clear: left; }
    .multi-columns-row .col-lg-3:nth-child(4n + 5) { clear: left; }
    .multi-columns-row .col-lg-2:nth-child(6n + 7) { clear: left; }
    .multi-columns-row .col-lg-1:nth-child(12n + 13) { clear: left; }
    }
    /*]]>*/
    </style>
    <style type="text/css">
/*<![CDATA[*/
    /*
    *   Owl Carousel Owl Demo Theme 
    *   v1.3.3
    */

    .owl-theme .owl-controls{
    margin-top: 10px;
    text-align: center;
    }

    /* Styling Next and Prev buttons */

    .owl-theme .owl-controls .owl-buttons div{
    color: #FFF;
    display: inline-block;
    zoom: 1;
    *display: inline;/*IE7 life-saver */
    margin: 5px;
    padding: 3px 10px;
    font-size: 12px;
    -webkit-border-radius: 30px;
    -moz-border-radius: 30px;
    border-radius: 30px;
    background: #869791;
    filter: Alpha(Opacity=50);/*IE7 fix*/
    opacity: 0.5;
    }
    /* Clickable class fix problem with hover on touch devices */
    /* Use it for non-touch hover action */
    .owl-theme .owl-controls.clickable .owl-buttons div:hover{
    filter: Alpha(Opacity=100);/*IE7 fix*/
    opacity: 1;
    text-decoration: none;
    }

    /* Styling Pagination*/

    .owl-theme .owl-controls .owl-page{
    display: inline-block;
    zoom: 1;
    *display: inline;/*IE7 life-saver */
    }
    .owl-theme .owl-controls .owl-page span{
    display: block;
    width: 12px;
    height: 12px;
    margin: 5px 7px;
    filter: Alpha(Opacity=50);/*IE7 fix*/
    opacity: 0.5;
    -webkit-border-radius: 20px;
    -moz-border-radius: 20px;
    border-radius: 20px;
    background: #869791;
    }

    .owl-theme .owl-controls .owl-page.active span,
    .owl-theme .owl-controls.clickable .owl-page:hover span{
    filter: Alpha(Opacity=100);/*IE7 fix*/
    opacity: 1;
    }

    /* If PaginationNumbers is true */

    .owl-theme .owl-controls .owl-page span.owl-numbers{
    height: auto;
    width: auto;
    color: #FFF;
    padding: 2px 10px;
    font-size: 12px;
    -webkit-border-radius: 30px;
    -moz-border-radius: 30px;
    border-radius: 30px;
    }

    /* preloading images */
    .owl-item.loading{
    min-height: 150px;
    background: url("AjaxLoader.gif.html") no-repeat center center
    }
    /* clearfix */
    .owl-carousel .owl-wrapper:after {
    content: ".";
    display: block;
    clear: both;
    visibility: hidden;
    line-height: 0;
    height: 0;
    }
    /* display none until init */
    .owl-carousel{
    display: none;
    /*position: relative;*/
    width: 100%;
    -ms-touch-action: pan-y;
    }
    .owl-carousel .owl-wrapper{
    display: none;
    position: relative;
    -webkit-transform: translate3d(0px, 0px, 0px);
    }
    .owl-carousel .owl-wrapper-outer{
    overflow: hidden;
    position: relative;
    width: 100%;
    }
    .owl-carousel .owl-wrapper-outer.autoHeight{
    -webkit-transition: height 500ms ease-in-out;
    -moz-transition: height 500ms ease-in-out;
    -ms-transition: height 500ms ease-in-out;
    -o-transition: height 500ms ease-in-out;
    transition: height 500ms ease-in-out;
    }

    .owl-carousel .owl-item{
    float: left;
    }
    .owl-controls .owl-page,
    .owl-controls .owl-buttons div{
    cursor: pointer;
    }
    .owl-controls {
    -webkit-user-select: none;
    -khtml-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    user-select: none;
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0);
    }

    /* mouse grab icon */


    /* fix */
    .owl-carousel  .owl-wrapper,
    .owl-carousel  .owl-item{
    -webkit-backface-visibility: hidden;
    -moz-backface-visibility:    hidden;
    -ms-backface-visibility:     hidden;
    -webkit-transform: translate3d(0,0,0);
    -moz-transform: translate3d(0,0,0);
    -ms-transform: translate3d(0,0,0);
    }
    /*]]>*/
    </style>
   

</head>

<body>
    <!--<head>
<link href='https://www.blogger.com/static/v1/widgets/2437439463-css_bundle_v2.css' rel='stylesheet' type='text/css'/>
<link href='https://www.blogger.com/dyn-css/authorization.css?targetBlogID=2762938771676047571&amp;zx=720b984b-e857-4818-b3c1-c79f6e5d41f1' media='none' onload='if(media!=&#39;all&#39;)media=&#39;all&#39;' rel='stylesheet'/><noscript><link href='https://www.blogger.com/dyn-css/authorization.css?targetBlogID=2762938771676047571&amp;zx=720b984b-e857-4818-b3c1-c79f6e5d41f1' rel='stylesheet'/></noscript>
</head>-->

  <style>
	     
				#main-menu-mobile{
					display: none;
					position: relative;
				}
				#main-menu-mobile li{
					color: #000;
					
				}
				.icon-bar{
					background: #fff;
					display: block;
					width: 22px;
					height: 2px;
					border-radius: 1px;
					margin-bottom: 5px;
				}
			#menu-top{
				margin-top: 0px;
			}
			#menu-top li{
				padding: 10px;
			}
			#menu-top{
				background: #fff;
			}
			#menu-top li a{
				margin: 0px 15px;
				cursor: pointer;
			}
			.nav-collapse li a{
				cursor: pointer;
			}
			.laster-shop-item a.fancybox{
				height: 244px;
				overflow: hidden;
				display: block;
			}
			</style>
          

    <div class='fix_height_mobile' style='float:left;width:100%;'>
        <header class='tz-header tz-header2 '>
            <div class='overlay'></div>

            <div class='header-top-bar'>
                <div class='container no-pad-768'>
                    <div class='fvc'>
                        <div class='col-sm-4 col-xs-1 col-lg-9 col-md-9'>
                           
                        </div>

                        <div class='col-sm-8 col-xs-11 col-lg-3 col-md-3'>
                            <div class='search-cart-list'>
                       

                                <div class='cart-total'>
                                    <ul>
                                        <li>
                                        Hotline: 0903.259.328   
                                           
                                           
                                         </li>
                                         <li class="visible-xs" onclick="showMenu()" style="position: absolute;margin-top: 0px;width: 22px;right: 20px;bottom: 2px;top:20px;z-index: 9999">
          <span class="sr-only">Toggle navigation</span>                                
         <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        
          
        </li>
                                    </ul>
                    
                    
                                </div>
                                
                                
                            </div>
                            
                            
                        </div>
                        
                        
                    </div>
                </div>
            
            
            <ul id="main-menu-mobile" class="list-group">
	                        <li class="list-group-item menuS1">In ấn & thi công Backdrop</li>
	                        <li class="list-group-item menuS2">Cổng bóng 8/3</li>
	                        <li class="list-group-item menuS3">Thiết kế thi công decal</li>
							<li class="list-group-item menuS5">Tiệc mua chung</li>
							<li class="list-group-item menuS6">Tặng quà</li>
							 
                        </ul>
            </div>
            
			
			    <div style="display: none;top:0px;width: 100%" id="header-top" class="header-home hidden-xs" data-spy="affix" data-offset-top="197">
	
		<!-- END Social Icons -->
	
		<div class="row">
		<div class="col-md-12">
			  <ul id="menu-top" class='list-inline nav-collapse hidden-xs'>
	                   

                        <li><a class="menuS1">In ấn & thi công Backdrop</a></li>
						<li><a class="menuS2">Cổng bóng 8/3</a></li>
						<li><a class="menuS3">Thiết kế thi công decal</a></li>
						 <li><a class="menuS5">Tiệc mua chung</a></li>
						 <li><a class="menuS6">Tặng quà</a></li>
                    <li><strong style="color:red;"> Hotline: 0903.259.328 </strong> </li>
                    </ul>
		
		</div>
	
		</div>
		
	</div>
            <div class='container' id='open_menu_mobile'>
	        
	            
	            
                <h3 class='tz-logo pull-left hidden-xs hidden-sm' style="margin-top: 10px; margin-bottom: 10px"><a class='logo' href='/pages/8-3'><img width="210" alt='Logo' src='/page/8-3/images/Logo%20hoabinhevents-01.png' /></a></h3>

                <h3 class='tz-logo pull-left visible-xs visible-sm'><a class='logo' href='/pages/8-3'><img alt='Hòa Bình Group' src='/page/8-3/images/Logo%20hoabinhevents-01.png' /></a></h3><!--<button class='btn-navbar tz_icon_menu pull-right visible-xs visible-sm' data-target='.nav-collapse' type='button'> MENU</button>-->

                <nav class='pull-right'>
                    <ul class='nav-collapse'>
	                    

                        <li><a class="menuS1">Backdrop</a></li>
						<li><a class="menuS2">Cổng bóng 8/3</a></li>
						<li><a class="menuS3">Thiết kế thi công decal</a></li>
						 <li><a class="menuS5">Tiệc mua chung</a></li>
						 <li><a class="menuS6">Tặng quà</a></li>
                        
                    
                    </ul>
                </nav>
            </div><!--end class container-->
        </header><!--end class tz-header-->

        <div class='fvc' style='float:left;width:100%;'>
            <h1 style='display:none;'></h1><!-- Slider -->

            <section class='tz-award slider_cover'>
                <ul class='tz-award-slider'>
                    <li><a href='index.html#'><img alt='slider' src='/page/8-3/images/banner%201-1600x583.png' /></a></li>

                    <li><a  href='index.html#'><img alt='slider' src='/page/8-3/images/banner%202-1600x583.png' /></a></li>

                    <li><a href='index.html#'><img alt='slider' src='/page/8-3/images/banner%203-1600x583.png' /></a></li>
                </ul>
            </section><!--end class tz-award-->
            <!-- End SLider -->

           <!-- <section class='tz-why-choose' style='margin: 40px 0px 0px 0px;'>
                <div class='container'>
                    <div class='row'>
                        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-12 img_full'>
                            <a href='index.html#'><img alt='banner' src='/page/8-3https://3.bp.blogspot.com/-VATYgvi3m0g/WI_xRs5UnMI/AAAAAAAAARs/wKdL0_MYVOkN63bd0LVUHWHwbTRpbmezQCLcB/s1600/layer-46%255B1%255D.jpg' /></a>
                        </div>

                        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-12 img_full'>
                            <a href='index.html#'><img alt='banner' src='/page/8-3https://3.bp.blogspot.com/-U5SU00Agy8E/WI_xbmabIKI/AAAAAAAAAR0/1RXjFXKohAE0OKpv6m54d7Rn7JxETJFdgCLcB/s1600/layer-45%255B1%255D.jpg' /></a>
                        </div>

                        <div class='col-lg-4 col-md-4 col-sm-4 col-xs-12 img_full'>
                            <a href='index.html#'><img alt='banner' src='/page/8-3https://3.bp.blogspot.com/-U5SU00Agy8E/WI_xbmabIKI/AAAAAAAAAR0/1RXjFXKohAE0OKpv6m54d7Rn7JxETJFdgCLcB/s1600/layer-45%255B1%255D.jpg' /></a>
                        </div>
                    </div>
                </div>
            </section>--><!--end class tz-why-choose-->
   <style>
	   #slide1 .simpleCart_shelfItem{
		   display: none;
	   }
	    #slide2 .simpleCart_shelfItem{
		   display: none;
	   }
	     #slide3 .simpleCart_shelfItem{
		   display: none;
	   }
	   
	</style>         

            <section class='list_style_product s1'>
                <div class='new_title_color center'>
                    <h2>Trang trí in ấn và thi công Backdrop</h2>
  <div style="margin-bottom: 15px;" class="description col-md-10 col-md-offset-1">               
Backdrop được sử dụng để thu hút sự chú ý của đám đông và làm nền treo sau sân khấu trong các sự kiện như tiệc thôi nôi, tiệc sinh nhật, tiệc ăn hỏi, tiệc cưới, tiệc kỷ niệm... HoabinhEvents cung cấp backdrop đa dạng về kích thước, chất liệu và kiểu dáng:   

<ul>
<li style="list-style-type: none;">- Backdrop lụa mềm mại và sang trọng</li>

<li  style="list-style-type: none;">- Backdrop gỗ vintage phong cách cổ điển</li>

<li  style="list-style-type: none;">- Backdrop hoa giấy tinh tế đầy màu sắc</li>

<li  style="list-style-type: none;">- Backdrop in bạt sắc nét chân thực </li>
</ul></div>
                </div>

                <div class='container'>
                    <div class='row featured-buttons-sell'>
                        <div id="slide1" class="slider-items slider-width-col4 multi-columns-row">               

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                   
                      <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/1.png"><img src="/page/8-3/images/backdrop/1.png" alt="#" /></a>
                                           

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 01</a></h3>

                                            
                                                    </div>

                                                    <div class="right_cnt_product">
     <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                           
                                                   <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/2.png"><img class="itemthumb" src="/page/8-3/images/backdrop/2.png" alt="" /></a>

                                          
                                          

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 02</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                          <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/3.png"><img class="itemthumb" src="/page/8-3/images/backdrop/3.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 03</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                           <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/4.png"><img class="itemthumb" src="/page/8-3/images/backdrop/4.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 04</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                           <!-- <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                    <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/5.png"><img class="itemthumb" src="/page/8-3/images/backdrop/5.png" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 05</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>-->

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
           <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/6.png"><img class="itemthumb" src="/page/8-3/images/backdrop/6.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 06</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                             <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
         <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/7.png"><img class="itemthumb" src="/page/8-3/images/backdrop/7.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 07</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
     <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/8.png"><img class="itemthumb" src="/page/8-3/images/backdrop/8.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 08</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
     <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/9.png"><img class="itemthumb" src="/page/8-3/images/backdrop/9.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 09</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
           <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/10.png"><img class="itemthumb" src="/page/8-3/images/backdrop/10.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 10</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
         <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/11.png"><img class="itemthumb" src="/page/8-3/images/backdrop/11.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 11</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
           <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/12.png"><img class="itemthumb" src="/page/8-3/images/backdrop/12.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 12</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                         
                            <div class="row">
	                            &nbsp;
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
       <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/13.png"><img class="itemthumb" src="/page/8-3/images/backdrop/13.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                       <h3><a class="item_name" href="#">Mẫu số 13</a></h3>

                                            
                                                    </div>

                                                    <div class="right_cnt_product">
     <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
         <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/14.png"><img class="itemthumb" src="/page/8-3/images/backdrop/14.png" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 14</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
        <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/15.png"><img class="itemthumb" src="/page/8-3/images/backdrop/15.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 15</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
           <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/16.png"><img class="itemthumb" src="/page/8-3/images/backdrop/16.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 16</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
         <a class="fancybox" data-fancybox-group="gallery1" href="/page/8-3/images/backdrop/17.png"><img class="itemthumb" src="/page/8-3/images/backdrop/17.png" alt="" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 17</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <div style='text-align:center;float:left;width:100%;'>
                    <a style="cursor: pointer" id="loadMore1" class='tz-view-more2 tz-view-style2'><span>Xem thêm</span></a>
                  <a style="cursor: pointer"  id="showLess1" class='tz-view-more2 tz-view-style2'><span>Rút gọn</span></a>
                </div>
            </section>
     
     <script type="text/javascript">
	     $(document).ready(function () {
		    $('#slide1 .simpleCart_shelfItem:lt(6)').show();  
		     $('#showLess1').hide();
		      var items =  16;
			  var shown =  6;
			  $('#loadMore1').click(function () {
        $('#showLess1').show();
        shown = $('#slide1 .simpleCart_shelfItem:visible').size()+5;
        if(shown< items) {$('#slide1 .simpleCart_shelfItem:lt('+shown+')').slideDown();}
        else {$('#slide1 .simpleCart_shelfItem:lt('+items+')').slideDown();
            // $('#showLess1').hide();
             }
    });
    
     $('#showLess1').click(function () {
        $('#slide1 .simpleCart_shelfItem').not(':lt(6)').slideUp();
        $('#showLess1').hide();
    });
		     });
	  </script>       
            
            <section class='list_style_product s2'>
                <div class='new_title_color center'>
                    <h2>Trang trí cổng bóng 8/3</h2>
            <div style='margin-bottom:20px;' class="description col-md-10 col-md-offset-1">   HoabinhEvents cung cấp dịch vụ trang trí cổng bóng cho các buổi tiệc trong nhà và ngoài trời. Với đội ngũ nhân viên trang trí chuyên nghiệp, chắc chắn sẽ biến buổi tiệc của bạn trở nên thật sống động và không kém phần lung linh. Cùng HoabinhEvents tham khảo các mẫu bóng được yêu thích sau nhé: </div>
                </div>

                <div class='container'>
                    <div class='row featured-buttons-sell'>
                        <div id="slide2" class="slider-items slider-width-col4 multi-columns-row">               

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                 <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 3.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 3.jpg" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 01</a></h3>

                                            
                                                    </div>

                                                    <div class="right_cnt_product">
     <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
              <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 4.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 4.jpg" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 02</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
               <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 5.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 5.jpg" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 03</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
              <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 6.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 6.jpg" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 04</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                          <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
               <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 7.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 7.jpg" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 05</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
              <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 8.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 8.jpg" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 06</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                             <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 9.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 9.jpg" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 07</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
          <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 10.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 10.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 08</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
           <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 11.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 11.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 09</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="row"></div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                   <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 12.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 12.jpg" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 10</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
             <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 13.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 13.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 11</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
         <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 14.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 14.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 12</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                         
                            <div class="row">
	                            &nbsp;
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
            <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 15.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 15.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                       <h3><a class="item_name" href="#">Mẫu số 13</a></h3>

                                            
                                                    </div>

                                                    <div class="right_cnt_product">
     <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
          <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 16.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 16.jpg" alt="" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 14</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                  <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 17.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 17.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 15</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
   <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 18.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 18.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 16</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="laster-thumb row">
                                                    <div class="shop-icon-data">
                                                      
                                                    </div><a href="#"><img class="itemthumb" src="/page/8-3/images/bong/Group 19.jpg" alt="" /></a>

                                                    <div id="product-actions-1815300" enctype="multipart/form-data">
                                                        <span class="tz-shop-meta"><a href="#" class="tzshopping item_add" title="Mua ngay" id="s3">Mua ngay</a></span>
                                                    </div>
                                                </div>
                                            </div>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 17</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
          <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 20.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 20.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 18</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
        <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 21.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 21.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 19</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
         <a class="fancybox" data-fancybox-group="gallery2" href="/page/8-3/images/bong/Group 22.jpg"><img class="itemthumb" src="/page/8-3/images/bong/Group 22.jpg" alt="" /></a>
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 20</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                          
                            
                            
                            
                            
                            
                        </div>
                    </div>
                </div>

                 <div style='text-align:center;float:left;width:100%;'>
                    <a style="cursor: pointer" id="loadMore2" class='tz-view-more2 tz-view-style2'><span>Xem thêm</span></a>
                  <a style="cursor: pointer"  id="showLess2" class='tz-view-more2 tz-view-style2'><span>Rút gọn</span></a>
                </div>
            </section>
            <script type="text/javascript">
	     $(document).ready(function () {
		    $('#slide2 .simpleCart_shelfItem:lt(6)').show();  
		     $('#showLess2').hide();
		      var items =  20;
			  var shown =  6;
			  $('#loadMore2').click(function () {
        $('#showLess2').show();
        shown = $('#slide2 .simpleCart_shelfItem:visible').size()+5;
        if(shown< items) {$('#slide2 .simpleCart_shelfItem:lt('+shown+')').slideDown();}
        else {$('#slide2 .simpleCart_shelfItem:lt('+items+')').slideDown();
             $('#loadMore2').hide();
             }
    });
    
     $('#showLess2').click(function () {
        $('#slide2 .simpleCart_shelfItem').not(':lt(6)').slideUp();
         $('#showLess2').hide();
    });
		     });
	  </script>
            
             <section  class='list_style_product s3'>
                <div class='new_title_color center'>
                    <h2>Thiết kế thi công decal</h2>
                    <div style="margin-bottom: 20px;" class="description col-md-10 col-md-offset-1">HoabinhEvents chuyên thiết kế và thi công decal trang trí kính mặt tiền công sở, trung tâm thương mại, tòa nhà chung cư với hơn 1500 mẫu decal đa dạng. Rất nhiều mẫu trang trí dịp Quốc tế Phụ Nữ độc đáo cho bạn lựa chọn:</div>
                </div>

                <div class='container'>
                    <div class='row featured-buttons-sell'>
                        <div id="slide3" class="slider-items slider-width-col4 multi-columns-row">  
	                        
	                         <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            
                                                   <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 1a.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 1a.png" alt="#" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 01</a></h3>

                                            
                                                    </div>

                                                    <div class="right_cnt_product">
     <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                             <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            
                                                   <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 3a.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 3a.png" alt="#" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 02</a></h3>

                                            
                                                    </div>

                                                    <div class="right_cnt_product">
     <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                             <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            
                                                   <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 8a.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 8a.png" alt="#" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 03</a></h3>

                                            
                                                    </div>

                                                    <div class="right_cnt_product">
     <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>             

                        
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 5.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 5.png" alt="#" /></a>

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 05</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 6.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 6.png" alt="" /></a>

                                                   
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 06</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 7.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 7.png" alt="#" /></a>

                                                  
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 07</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                             <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 8.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 8.png" alt="#" /></a>


                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 08</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 9.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 9.png" alt="" /></a>

                                                 

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 09</a></h3>

                                                  
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 10.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 10.png" alt="#" /></a>

                                                

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 10</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                           <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 12.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 12.png" alt="#" /></a>

                                                 
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 12</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 13.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 13.png" alt="#" /></a>

                                              

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 13</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 15.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 15.png" alt="#" /></a>

                                               

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 15</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                         
                            <div class="row">
	                            &nbsp;
                            </div>
                            
                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 16.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 16.png" alt="#" /></a>

                                                  

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                       <h3><a class="item_name" href="#">Mẫu số 16</a></h3>

                                            
                                                    </div>

                                                    <div class="right_cnt_product">
     <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 17.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 17.png" alt="" /></a>

                                                 
                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 17</a></h3>

                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>

                            <div class="simpleCart_shelfItem">
                                <div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
                                    <div class="">
                                        <div class="laster-shop-item">
                                            <a class="fancybox" data-fancybox-group="gallery3" href="/page/8-3/images/decal/Group 18.png"><img class="itemthumb" src="/page/8-3/images/decal/Group 18.png" alt="" /></a>

                                                   

                                            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                <div class="row">
                                                    <div class="left_cnt_product">
                                                        <h3><a class="item_name" href="#">Mẫu số 18</a></h3>

                                                     
                                                    </div>

                                                    <div class="right_cnt_product">
                                                        <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                           
                        </div>
                    </div>
                </div>
                

                 <div style='text-align:center;float:left;width:100%;'>
                    <a style="cursor: pointer" id="loadMore3" class='tz-view-more2 tz-view-style2'><span>Xem thêm</span></a>
     <a style="cursor: pointer"  id="showLess3" class='tz-view-more2 tz-view-style2'><span>Rút gọn</span></a>
                 </div>
            </section>
             
              <script type="text/javascript">
	   //  $(document).ready(function () {
		    $('#slide3 .simpleCart_shelfItem:lt(6)').show();  
		     $('#showLess3').hide();
		      var items =  15;
			  var shown =  6;
			  $('#loadMore3').click(function () {
        $('#showLess3').show();
        shown = $('#slide3 .simpleCart_shelfItem:visible').size()+5;
        if(shown< items) {$('#slide3 .simpleCart_shelfItem:lt('+shown+')').slideDown();}
        else {$('#slide3 .simpleCart_shelfItem:lt('+items+')').slideDown();
             $('#loadMore3').hide();
             }
    });
    
     $('#showLess3').click(function () {
        $('#slide3 .simpleCart_shelfItem').not(':lt(6)').slideUp();
        $('#showLess3').hide();
    });
		   //  });
	  </script>
             
              <section class='list_style_product s4'>
                <div class='new_title_color center'>
                    <h2>Dịch vụ Teabreak</h2>
       
                </div>

                <div class='container'>
                    <div class='row featured-buttons-sell'>
                        <div class="slider-items slider-width-col4 multi-columns-row">               

                            <div class="simpleCart_shelfItem text-center" style="text-align: center;">
                                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-md-offset-1">
                                   <img style="margin-bottom: 15px;" class="itemthumb" src="/page/8-3/images/thucdon/1a.jpg" alt="#" />
                                </div>
                            </div>

							  <div class="simpleCart_shelfItem text-center">
                                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-md-offset-1">
                                   <img style="margin-bottom: 15px;" class="itemthumb" src="/page/8-3/images/thucdon/2a.jpg" alt="#" />
                                </div>
                            </div>
                            
                              <div class="simpleCart_shelfItem text-center">
                                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-md-offset-1">
                                   <img style="margin-bottom: 15px;" class="itemthumb" src="/page/8-3/images/thucdon/3a.jpg" alt="#" />
                                </div>
                            </div>
                            
                              <div class="simpleCart_shelfItem text-center">
                                <div class="col-lg-10 col-md-10 col-sm-10 col-xs-12 col-md-offset-1">
                                   <img style="margin-bottom: 15px;" class="itemthumb" src="/page/8-3/images/thucdon/4a.jpg" alt="#" />
                                </div>
                            </div>
                          
                  
                            
                           
                        </div>
                    </div>
                </div>

               
            </section>
            
    

            <section id="muachung" style="cursor: pointer;margin-bottom: 0px;margin-top: 30px;" class='tz-about theme-gray-bg s5'></section><!--end class tz-about-->
            
             <div style='text-align:center;float:left;width:100%;'>
                    <a style="cursor: pointer;margin-top: 20px;"  data-toggle="modal" data-target="#GSCCModal" id="loadMore" class='tz-view-more2 tz-view-style'><span>Xem thêm</span></a>
                    </div>
                 
            <div id="GSCCModal" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
 <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;  </button>
        <h4 class="modal-title" id="myModalLabel">Tiệc mua chung</h4>
      </div>
      <div class="modal-body">
	      <div class="description">   
			   <p></p><p style="text-align:justify"><span style="color:#0000CD"><strong>ĐIỂM NỔI BẬT TRONG CHƯƠNG TRÌNH </strong></span></p>

<p style="text-align:justify">-&nbsp;Tiệc buffet nướng cuối tuần và Chiêm ngưỡng Trình diễn thời trang Women In Love Fashion shows sẽ mang đến cho bạn cùng bạn bè và người thân những khoảnh khắc thật đáng nhớ.<br>
-&nbsp;Bạn sẽ có cơ hội được tham gia tiệc đứng finger food với gần 20 món ăn lạ miệng theo phong cách châu Âu đặc trưng.<br>
-&nbsp;Nhiều hoạt động nghệ thuật xung quanh không gian như: Fashion Shows, Next Top Model Junior, Lucky Money, DJ Mixer<br>
-&nbsp;Women In Love Party&nbsp;hứa hẹn sẽ là một buổi tiệc hoành tráng lung linh và tràn ngập màu sắc.</p>

<p style="text-align:justify"><span style="color:#0000CD"><strong>ĐIỀU KIỆN SỬ DỤNG </strong></span></p>

<p style="text-align:justify">- Thời hạn sử dụng:&nbsp;<strong>07/03/2018</strong><br>
- Áp dụng cho: Women in love party<br>
- Duy nhất ngày 07/03/2018 bao gồm các hoạt động nghệ thuật hấp dẫn như:<br>
+ Chụp ảnh + in ảnh miễn phí.<br>
+ Chiêm ngưỡng Trình diễn thời trang Women In Love&nbsp;Fashion shows.<br>
+ Thưởng thức tiết mục biểu diễn của Siêu người mẫu nhí đến từ cuộc thi Next top models juniors.<br>
+ Tham dự trò chơi Giải câu đố nhận ngay tiền mặt.<br>
+ Sôi động cùng DJ show.<br>
- Một khách hàng được mua nhiều vé.<br>
- Sử dụng 01 vé/ 01 người. Áp dụng nhiều vé/ hóa đơn.<br>
<br>
<strong>Quy định dành cho trẻ em:</strong><br>
+ Dưới 1m miễn phí. Một người lớn được đi kèm tối đa 01 trẻ em cao dưới 01m.<br>
+ Từ 1m-1,3m: 70,000 đ/ bé, nộp tiền trực tiếp tại địa điểm.<br>
+ Trên 1,3m tính phí như người lớn.<br>
<br>
- Giá chưa bao gồm VAT.<br>
- Không áp dụng đồng thời với các chương trình khuyến mãi khác.<br>
- Không áp dụng cho đồ uống và mua mang về.<br>
- Thời gian áp dụng: 18:00 - 22:00 tối 07/03/2018<br>
- Quý khách vui lòng gọi điện thoại trước khi đến để đăng ký địa điểm tham dự và đảm bảo có chỗ.<br>
- Địa điểm sử dụng: <strong>Women in love party</strong><br>
- Cơ sở 1: Sảnh Grand Ball tầng 2 – Trung tâm văn hóa quận Thanh Xuân (Dự kiến)<br>
- Cơ sở 2: Ballroom tầng 3 - Trung tâm văn hóa quận Thanh Xuân (Dự kiến)<br>
<br>
<strong>- Hotline đặt dịch vụ: 0903259328</strong></p>

<p style="text-align:justify"><span style="color:#0000CD"><strong>THÔNG TIN CHI TIẾT</strong></span></p>

<p style="text-align:justify">Bạn đang lên kế hoạch cùng bạn bè và người thân đi chơi vào dịp 8/3 này nhưng vẫn chưa tìm được địa điểm thích hợp để tụ tập gặp mặt cùng tán chuyện rôm rả? Hãy để HoabinhEvents gợi ý cho bạn một đêm tiệc đầy âm thanh và sắc màu:<span style="color:#FF0000">&nbsp;<strong>Women In Love Party</strong> </span>với các chương trình nghệ thuật, giải trí đặc sắc gồm có: Tiệc đứng phục vụ dưới dạng Finger foods, Fashion shows đầy màu sắc và sáng tạo của các nhà thiết kế trẻ Women In Love Fashion shows, Tiết mục Trình diễn Next top model junior của các models nhí... Một bữa tiệc sống động đang chờ bạn khám phá, hãy tham gia ngay thôi bạn ơi!</p>

<p style="text-align:justify">Không chỉ được thưởng thức các món ăn ngon, bữa tiệc còn có<strong> </strong>các hoạt động hấp dẫn như:<br>
- Chụp ảnh + in ảnh miễn phí.<br>
- Chiêm ngưỡng Trình diễn thời trang Women In Love&nbsp;Fashion shows.<br>
- Thưởng thức tiết mục biểu diễn của Siêu người mẫu nhí đến từ cuộc thi Next top models juniors.<br>
- Tham dự trò chơi Giải câu đố nhận ngay tiền mặt.<br>
- Sôi động cùng DJ show.<br>
&nbsp;</p>

<p style="text-align:justify"><strong>+ Tiệc đứng Finger Foods:</strong></p>

<p style="text-align:justify">Bạn sẽ được thưởng thức tiệc đứng Finger Food với nhiều món ăn đặc sắc gần 20 món ăn lạ miệng theo phong cách châu Âu đặc trưng, hương vị hoàn toàn mới lạ rất phù hợp với khẩu vị của người Việt như:&nbsp;<strong>Cà tím nướng với sốt chua ngọt, Bò nướng với khoai tây và cà chua bi, Tôm sú nướng với sốt cam, Chả mọc nướng với nho, Táo tây nướng với sốt kem, Trứng cút nướng Hàng Châu, Gà ướp hương mùi nướng với cà chua bi,&nbsp; Thăn lợn tẩm sốt mật ong nướng với sắn, Cá bò nướng với sốt cay, Nấm hương nướng với hành tây và khoai Lệ Phố, Cá trứng nướng mọi, Ngô nếp nướng với bí bao tử, Sushi Nutella, Dưa hấu với kẹo dẻo marshmallow, Bánh mỳ nướng với mứt cam</strong>… sẽ mang đến cho bạn một trải nghiệm thú vị.</p>

<p style="text-align:center"><span style="color:#0000CD"><strong>MENU FINGER FOOD </strong></span></p>

<table align="center" border="1" cellpadding="1" cellspacing="1" style="width:500px">
	<tbody>
		<tr>
			<td>
			<p style="text-align:center"><strong>Cà tím nướng với sốt chua ngọt</strong></p>

			<p style="text-align:center"><strong><img alt="Women in love party menu" src="http://hoabinh-group.com/source/menu8march/Untitled-2.jpg" style="height:162px; width:250px"></strong></p>
			</td>
			<td style="text-align:center">
			<p><strong>Tôm sú nướng với sốt cam</strong></p>

			<p><img alt="Tôm sú nướng với sốt cam" src="http://hoabinh-group.com/source/menu8march/Untitled-1.jpg" style="height:162px; width:250px"></p>
			</td>
		</tr>
		<tr>
			<td>
			<p style="text-align:center"><strong>Chả mọc nướng với nho</strong></p>

			<p style="text-align:center"><strong><img alt="Chả mọc nướng với nho" src="http://hoabinh-group.com/source/menu8march/45.jpg" style="height:162px; width:132px"></strong></p>
			</td>
			<td style="text-align:center">
			<p><strong>Táo tây nướng với sốt kem</strong></p>

			<p><img alt="Táo tây nướng với sốt kem" src="http://hoabinh-group.com/source/menu8march/3.jpg" style="height:162px; width:250px"></p>
			</td>
		</tr>
		<tr>
			<td style="text-align:center">
			<p><strong>Trứng cút nướng Hàng Châu</strong><br>
			&nbsp;</p>

			<p><img alt="Trứng cút nướng Hàng Châu" src="http://hoabinh-group.com/source/menu8march/ffq.jpg" style="height:162px; width:250px"></p>
			</td>
			<td>
			<p style="text-align:center"><strong>Gà ướp hương mùi nướng<br>
			với cà chua bi</strong></p>

			<p style="text-align:center"><strong><img alt="Gà ướp hương mùi nướng với cà chua bi" src="http://hoabinh-group.com/source/menu8march/234.jpg" style="height:162px; width:250px"></strong></p>
			</td>
		</tr>
		<tr>
			<td>
			<p style="text-align:center"><strong>Thăn lợn tẩm sốt mật ong<br>
			nướng với sắn</strong></p>

			<p style="text-align:center"><strong><img alt="Thăn lợn tẩm sốt mật ong nướng với sắn" src="http://hoabinh-group.com/source/menu8march/sh.jpg" style="height:162px; width:250px"></strong></p>
			</td>
			<td>
			<p style="text-align:center"><strong>Cá bò nướng với sốt cay</strong><br>
			&nbsp;</p>

			<p style="text-align:center"><strong><img alt="Cá bò nướng với sốt cay" src="http://hoabinh-group.com/source/menu8march/erfd.jpg" style="height:162px; width:146px"></strong></p>
			</td>
		</tr>
		<tr>
			<td>
			<p style="text-align:center"><strong>Nấm hương nướng với hành tây<br>
			và khoai Lệ Phố</strong></p>

			<p style="text-align:center"><strong><img alt="Nấm hương nướng với hành tây và khoai Lệ Phố" src="http://hoabinh-group.com/source/menu8march/weewwe.jpg" style="height:150px; width:248px"></strong></p>
			</td>
			<td>
			<p style="text-align:center"><strong>Cá trứng nướng mọi</strong><br>
			&nbsp;</p>

			<p style="text-align:center"><strong><img alt="Cá trứng nướng mọi" src="http://hoabinh-group.com/source/menu8march/jrr.jpg" style="height:150px; width:232px"></strong></p>
			</td>
		</tr>
		<tr>
			<td>
			<p style="text-align:center"><strong>Ngô nếp nướng với bí bao tử</strong></p>

			<p style="text-align:center"><strong><img alt="Ngô nếp nướng với bí bao tử" src="http://hoabinh-group.com/source/menu8march/wee.jpg" style="height:145px; width:224px"></strong></p>
			</td>
			<td>
			<p style="text-align:center"><strong>Sushi Nutella</strong></p>

			<p style="text-align:center"><strong><img alt="Sushi Nutella" src="http://hoabinh-group.com/source/menu8march/eee.jpg" style="height:145px; width:250px"></strong></p>
			</td>
		</tr>
		<tr>
			<td>
			<p style="text-align:center"><strong>Dưa hấu với kẹo dẻo marshmallow</strong></p>

			<p style="text-align:center"><strong><img alt="Dưa hấu với kẹo dẻo marshmallow" src="http://hoabinh-group.com/source/menu8march/jrw.jpg" style="height:162px; width:250px"></strong></p>
			</td>
			<td>
			<p style="text-align:center"><strong>Bánh mỳ nướng với mứt cam</strong></p>

			<p style="text-align:center"><strong><img alt="Bánh mỳ nướng với mứt cam" src="http://hoabinh-group.com/source/menu8march/sdg.jpg" style="height:162px; width:250px"></strong></p>
			</td>
		</tr>
	</tbody>
</table>

<p style="text-align:justify"><strong>+&nbsp; Chiêm ngưỡng trình diễn thời trang Fashion shows&nbsp;</strong></p>

<p style="text-align:justify">Lần đầu tiên xuất hiện tại Women In Love Party các nhà thiết kế trẻ tài năng vô cùng xinh đẹp và cực kỳ cá tính. Vậy bạn đã đăng ký mua vé tham dự chương trình để gặp gỡ các cô ấy chưa?</p>

<p style="text-align:center"><img alt="Women In Love Party " src="http://hoabinh-group.com/source/menu8march/show.jpg" style="height:292px; width:550px"></p>

<p style="text-align:justify"><strong>+&nbsp; Next top model junior</strong></p>

<p style="text-align:justify">Next top model junior là 1 tiết mục ngẫu hứng mô phỏng theo chương trình truyền hình nổi tiếng Next top model. Nhân vật chính ở đây không phải là các cô gái chân dài xinh đẹp mà là các baby kids dễ thương và vô cùng đáng yêu.</p>

<p style="text-align:center"><img alt="Women In Love Party " src="http://hoabinh-group.com/source/menu8march/show2.jpg" style="height:314px; width:550px"></p>

<p style="text-align:justify">Ngoài ra khách tham dự chương trình còn có cơ hội nhận ngay phần thưởng tiền mặt với việc:<br>
+&nbsp; Trả lời câu đố siêu dễ của MC và nhận ngay tiền mặt với màn giải câu đố nổi tiếng đến từ chương trình Paris By Night – Trò Lucky money.</p>

<p style="text-align:justify"><strong>+ </strong>Sôi động; Cuồng nhiệt; Dance, Fire &amp; Crazy cùng DJ Mixer</p>

<p style="text-align: center;"><img alt="Women In Love Party " src="http://hoabinh-group.com/source/menu8march/gwr.jpg" style="height:356px; width:550px"></p>

<p style="text-align:justify">Hãy cùng hòa mình vào những tiết tấu âm nhạc từ dòng nhạc techno, house, EDM, và electro vốn đòi hỏi gu thưởng thức âm nhạc rất cao và đang trở thành trào lưu chung cho tín đồ âm nhạc thế giới, đến dòng âm nhạc phổ biến ở Việt Nam hiện nay như dubstep, electro, drum &amp; bass, hip hop và một số loại khác cũng đang thu hút được rất đông người hâm mộ cùng các DJ để thưởng thức bữa tiệc đầy sống động này nhé.</p>

<p style="text-align:justify"><strong>+ Thiết kế sân khấu và không gian buổi tiệc với quy mô 2 tầng, không gian mở, hình tròn với ý tưởng từ mặt trống đồng. Một không gian sống động có 1 không 2 mà bạn từng trải nghiệm.</strong></p>

<p style="text-align: center;"><strong><img alt="Women In Love Party " src="http://hoabinh-group.com/source/menu8march/hhre.jpg" style="height:330px; width:550px"></strong></p>

<p style="text-align:justify"><span style="color:#0000CD"><strong>Gọi 0903.259.328 để đăng ký tham gia ngay bạn nhé!</strong></span></p>
<p></p>
		
			</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
      </div>
    </div>
  </div>
</div>
            

            <section class='main-container col1-layout home-content-container s6'>
                <div class='new_title_color center'>
                    <h2>Dịch vụ tặng quà</h2>
                    <div class="description">
	                    Chỉ còn vài ngày nữa thôi là đến 8/3 rồi, ngày dành cho các chị, em, vợ hay người yêu và cả các mẹ. Nếu bạn còn băn khoăn chưa biết chọn món quà nào dành cho họ, hãy để HoabinhEvents giúp bạn với các set quà ngọt ngào và trang trọng sau: 

                    </div>
                </div>

                <div class='container'>
                    <div class='std row'>
                        <div class='col-lg-4 col-md-4 col-sm-12 col-xs-12 pad_fix_right'>
                            <div class='box_collection_pr visible-lg visible-md'>
                                <div class='list_item show1 __MB_NEWS_TAB3'>
                                    <ul>
                                        <li class='li_lv1 active'><a href='javascript:void(0)' id='1'>
	                                        <i style="font-size: 2em;margin-right: 15px;" class="fa fa-gift"></i><span style="top: -2px;display: inline-block;position: relative">Rượu vang và sô cô la</span></a></li>

                                        <li class='li_lv2'><a href='javascript:void(0)' id='2'><i style="font-size: 2em;margin-right: 15px;" class="fa fa-gift"></i><span style="top: -2px;display: inline-block;position: relative">Nước hoa chính hãng</span></a></li>

                                        <li class='li_lv3'><a href='javascript:void(0)' id='3'><i style="font-size: 2em;margin-right: 15px;" class="fa fa-gift"></i><span style="top: -2px;display: inline-block;position: relative">Set quà 8/3</span></a></li>
										<li class='li_lv4'><a href='javascript:void(0)' id='4'><i style="font-size: 2em;margin-right: 15px;" class="fa fa-gift"></i><span style="top: -2px;display: inline-block;position: relative">Hoa 8/3</span></a></li>

                              

                                    </ul>
                                </div>
                            </div>

                            <div class='box_collection_mobile __MB_NEWS_TAB3  visible-sm visible-xs'>
                                <ul>
                                    <li class='li_lv1 active'><a href='javascript:void(0)' id='1'>Rượu vang và sô cô la</a></li>

                                    <li class='li_lv2'><a href='javascript:void(0)' id='2'>Nước hoa chính hãng</a></li>

                                    <li class='li_lv3'><a href='javascript:void(0)' id='3'>Set quà 8/3</a></li>

                                    <li class='li_lv4'><a href='javascript:void(0)' id='4'>Hoa 8/3</a></li>

                               
                                </ul>
                            </div>
                        </div>

                        <div class="col-lg-8 col-md-8 col-sm-12 col-xs-12 pad_fix_left">
                            <div class="best-seller-pro active __MB_CONTAINER_READ3 __MB_CONTAINER_READ3_1">
                                <div class="slider-items-products row visible-xs">
                                    <div class=" multi-columns-row owl-demo-grid">
                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                              
                                                        <a data-fancybox-group="gallery4" class="fancybox item_thumb" href="/page/8-3/images/ruou/1.jpg"><img src="/page/8-3/images/ruou/1.jpg" alt="Mẫu số 01" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                            <h3><a class="item_name" href="#">Mẫu số 01</a></h3>

                                                          
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <a data-fancybox-group="gallery4" class="fancybox item_thumb" href="/page/8-3/images/ruou/2.jpg"><img src="/page/8-3/images/ruou/2.jpg" alt="Mẫu số 02" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                            <h3><a class="item_name" href="#">Mẫu số 02</a></h3>

                                                        
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <a data-fancybox-group="gallery4" class="fancybox item_thumb" href="/page/8-3/images/ruou/3.jpg"><img src="/page/8-3/images/ruou/3.jpg" alt="Mẫu số 03" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                            <h3><a class="item_name" href="#">Mẫu số 03</a></h3>

                                                       
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                        <a data-fancybox-group="gallery4" class="fancybox item_thumb" href="/page/8-3/images/ruou/4.jpg"><img src="/page/8-3/images/ruou/4.jpg" alt="Mẫu số 04" /></a>
                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                            <h3><a class="item_name" href="#">Mẫu số 04</a></h3>

                                                      
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                 <object class="hidden-xs" data="http://hoabinh-group.com/page/8-3/images/pdf/Gifts%20for%20Holiday.%20Food%20and%20Drink.pdf#view=Fit" type="application/pdf" width="100%" height="550">
    <p>
        Nếu trình duyệt của bạn không hỗ trợ hiển thị pdf. Bạn chỉ cần <a href="http://hoabinh-group.com/page/8-3/images/pdf/Gifts%20for%20Holiday.%20Food%20and%20Drink.pdf">ấn vào đây để tải tệp pdf về.</a>
    </p>
</object>          
                            </div>

                            <div class="best-seller-pro __MB_CONTAINER_READ3 __MB_CONTAINER_READ3_2" style="display:none;">
                               <div class="slider-items-products row visible-xs">
                                    <div class=" multi-columns-row owl-demo-grid">
                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                              
                                                        <a data-fancybox-group="gallery5" class="fancybox item_thumb" href="/page/8-3/images/nuochoa/1.jpg"><img src="/page/8-3/images/nuochoa/1.jpg" alt="" /></a>

                                               

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                 <a data-fancybox-group="gallery5" class="fancybox item_thumb" href="/page/8-3/images/nuochoa/2.jpg"><img src="/page/8-3/images/nuochoa/2.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                         <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                  <a data-fancybox-group="gallery5" class="fancybox item_thumb" href="/page/8-3/images/nuochoa/3.jpg"><img src="/page/8-3/images/nuochoa/3.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                         <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                  <a data-fancybox-group="gallery5" class="fancybox item_thumb" href="/page/8-3/images/nuochoa/4.jpg"><img src="/page/8-3/images/nuochoa/4.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                         <object class="hidden-xs" data="http://hoabinh-group.com/page/8-3/images/pdf/1Gifts%20for%20Holiday.%20Beauty.pdf#view=Fit" type="application/pdf" width="100%" height="100%">
<iframe src="http://hoabinh-group.com/page/8-3/images/pdf/1Gifts%20for%20Holiday.%20Beauty.pdf" width="100%" height="100%" style="border: none;">
This browser does not support PDFs. Please download the PDF to view it: <a href="http://hoabinh-group.com/page/8-3/images/pdf/1Gifts%20for%20Holiday.%20Beauty.pdf">Download PDF</a>
</iframe>
</object>
                                                              </div>

                            <div class="best-seller-pro __MB_CONTAINER_READ3 __MB_CONTAINER_READ3_3" style="display:none;">
                                <div class="slider-items-products row">
                                    <div class=" multi-columns-row owl-demo-grid">
                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                 <a data-fancybox-group="gallery6" class="fancybox item_thumb" href="/page/8-3/images/qua/1.jpg"><img src="/page/8-3/images/qua/1.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                 <a data-fancybox-group="gallery6" class="fancybox item_thumb" href="/page/8-3/images/qua/2.jpg"><img src="/page/8-3/images/qua/2.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a href="tel:0903259328"><a class="contactForm" ><small>Liên hệ</small></a></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                         <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                 <a data-fancybox-group="gallery6" class="fancybox item_thumb" href="/page/8-3/images/qua/3.jpg"><img src="/page/8-3/images/qua/3.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                         <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                 <a data-fancybox-group="gallery6" class="fancybox item_thumb" href="/page/8-3/images/qua/4.jpg"><img src="/page/8-3/images/qua/4.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            
                              <div class="best-seller-pro __MB_CONTAINER_READ3 __MB_CONTAINER_READ3_4" style="display:none;">
                                <div class="slider-items-products row visible-xs">
                                    <div class=" multi-columns-row owl-demo-grid">
                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                 <a data-fancybox-group="gallery6" class="fancybox item_thumb" href="/page/8-3/images/qua/1.jpg"><img src="/page/8-3/images/hoa/1.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                 <a data-fancybox-group="gallery6" class="fancybox item_thumb" href="/page/8-3/images/qua/2.jpg"><img src="/page/8-3/images/hoa/2.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                         <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                 <a data-fancybox-group="gallery6" class="fancybox item_thumb" href="/page/8-3/images/qua/3.jpg"><img src="/page/8-3/images/hoa/3.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                         <div class="simpleCart_shelfItem">
                                            <div class="laster-shop-item col-lg-6 col-md-6 col-sm-6 col-xs-12">
                                                 <a data-fancybox-group="gallery6" class="fancybox item_thumb" href="/page/8-3/images/qua/4.jpg"><img src="/page/8-3/images/hoa/4.jpg" alt="" /></a>

                                                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12 stl_full_width">
                                                    <div class="row">
                                                        <div class="left_cnt_product">
                                                           
                                                        </div>

                                                        <div class="right_cnt_product">
                                                            <p class="item_price"><a class="contactForm" ><small>Liên hệ</small></a></p>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            
                              
                              <object class="hidden-xs" data="http://hoabinh-group.com/page/8-3/images/pdf/Gifts%20for%20Holiday.%20Flower.pdf#view=Fit" type="application/pdf" width="100%" height="550">
    <p>
        Nếu trình duyệt của bạn không hỗ trợ hiển thị pdf. Bạn chỉ cần <a href="http://hoabinh-group.com/page/8-3/images/pdf/Gifts%20for%20Holiday.%20Flower.pdf">ấn vào đây để tải tệp pdf về.</a>
    </p>
</object>
                              </div>

                        </div>
                    </div>
                </div>
            </section>
            
            

            <section id="testimonial" class='tz-award tz-award-sell'>
                <div class='slider-items-products container'>
                    <div class='featured-buttons' id='author-slider'>
                        <div class='slider-items'>
                            <div class='content_tip'>
                                <a><img alt='PHẠM NHẬT THÀNH' src='https://scontent.fhan2-1.fna.fbcdn.net/v/t1.0-1/p160x160/18342696_1966431393408678_3084511844217013088_n.jpg?oh=3027c06f0ac8027e43e5c961c4f81dc4&oe=5B11189A' /></a>

                                <p class='decs_author'>Tôi rất hài lòng với dịch vụ chuyên nghiệp và chất lượng sản phẩm cũng như thái độ phục vụ của Hòa Bình Group. Chắc chắn rằng tôi sẽ quay lại đây nhiều lần nữa để mua hàng.</p>

                                <p class='name_author'>PHẠM NHẬT THÀNH</p>

                                <p class='company_author'>Web Designer</p>
                            </div>

                            <div class='content_tip'>
                                <a><img alt='Nguyễn Long Thành' src='https://2.bp.blogspot.com/-l6TbGOEbruY/WI_xvrLufJI/AAAAAAAAASA/8i6Fszja4LsfV6xXUB9Xg1tTEjg_J04PACLcB/s1600/layer_author2%255B1%255D.png' /></a>

                                <p class='decs_author'>Chất lượng sản phẩm của các bạn rất tốt. Tôi thật sự hài lòng.</p>

                                <p class='name_author'>Nguyễn Long Thành</p>

                                <p class='company_author'>Luật sư</p>
                            </div>

                            <div class='content_tip'>
                                <a><img alt='Lê Đức Anh' src='https://2.bp.blogspot.com/-JlOC3c2KXxM/WI_x37rvsQI/AAAAAAAAASI/f_x9BreHTOQ-GvVEQaFxmmlfXLW708LFACLcB/s1600/layer_author3%255B1%255D.png' /></a>

                                <p class='decs_author'>Các sản phẩm rất đẹp, dịch vụ và thái độ phục vụ chuyên nghiệp. Tôi sẽ đánh dấu lại trang này để lần sau quay lại mua hàng!</p>

                                <p class='name_author'>Lê Đức Anh</p>

                                <p class='company_author'>Bác sỹ</p>
                            </div>
                        </div>
                    </div>
                </div>
            </section><!--end class tz-award-->
          
  
            
        </div>
        

        
        <section id="contact" class="tz-award-sell" style="background: #fff;">
  <div class="container">

	
	<div class="row" id="contact">
	  <div class="col-md-7 google-maps">
       <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3724.157928468158!2d105.83007931458731!3d21.02636598599969!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3135ab9c2bcea369%3A0x601713babedb164b!2zMjkgxJBvw6BuIFRo4buLIMSQaeG7g20sIFF14buRYyBU4butIEdpw6FtLCDEkOG7kW5nIMSQYSwgSMOgIE7hu5lpLCBWaeG7h3QgTmFt!5e0!3m2!1svi!2s!4v1517825174758" width="600" height="300" frameborder="0" style="border:0" allowfullscreen></iframe>
      </div>

      <div class="col-md-5">
          <h4><strong style="margin-bottom: 20px;display: block" class="">NHẬP THÔNG TIN BÁO GIÁ</strong></h4>
        <form id="contactForm" action="/default/pages/submit2" method="POST">
          <div class="form-group">
            <input type="text" class="form-control" id="name" name="name" value="" placeholder="Tên">
          </div>
         <!-- <div class="form-group">
            <input type="email" class="form-control" id="email" name="email" value="" placeholder="E-mail">
          </div>-->
          <div class="form-group">
            <input type="tel" class="form-control" id="mobile" name="mobile" value="" placeholder="Điện thoại">
          </div>
          <div class="form-group">
            <textarea class="form-control" id="message" name="message" rows="3" placeholder="Thông tin"></textarea>
          </div>
          <button class="btn btn-default" type="submit" name="button">
              <i class="fa fa-paper-plane-o" aria-hidden="true"></i> Gửi báo giá
          </button>
        </form>
      </div>
    </div>
  </div>
</section>
        

        <footer>
            <!-- FOOTER-MIDDLE-AREA START-->

         

            <div class='footer-bottum-area'>
                <div class='container'>
                    <div class='row'>
                        <div class='col-sm-12 col-xs-12 col-md-7 col-lg-6'>
                            <div class='copyright-info'>
                                &#169; Bản quyền thuộc về Hòa Bình Group | Thiết kế bởi <a href='' target='_blank' title=''>Louis</a>
                            </div>
                        </div>

                        <div class='col-sm-12 col-xs-12 col-lg-6 col-md-5 company-links'>
                            <ul class='links'>
                                <li><a href='#'>Quay lên trên</a></li>

                            </ul>
                        </div>
                    </div>
                </div>
            </div><!-- FOOTER-BOTTUM-AREA END-->
        </footer>
    </div>
   
     <script type="text/javascript">
	
	function showMenu()
	{
		$("#main-menu-mobile").slideToggle();
	}
	
		$(".menuS1").click(function() {
    $('html, body').animate({
        scrollTop: $(".s1").offset().top
    }, 2000);
});

		$(".menuS2").click(function() {
    $('html, body').animate({
        scrollTop: $(".s2").offset().top
    }, 2000);
});

$(".menuS3").click(function() {
    $('html, body').animate({
        scrollTop: $(".s3").offset().top
    }, 2000);
});

$(".menuS4").click(function() {
    $('html, body').animate({
        scrollTop: $(".s4").offset().top
    }, 2000);
});

$(".menuS5").click(function() {
    $('html, body').animate({
        scrollTop: $(".s5").offset().top
    }, 2000);
});

$(".menuS6").click(function() {
    $('html, body').animate({
        scrollTop: $(".s6").offset().top
    }, 2000);
});
	
		$(".contactForm").click(function() {
    $('html, body').animate({
        scrollTop: $("#contact").offset().top
    }, 2000);
});

	$(".menuTestimonial").click(function() {
    $('html, body').animate({
        scrollTop: $("#testimonial").offset().top
    }, 2000);
});
	
$(window).scroll(function() {
    if ($(this).scrollTop() > 180) {
	    
        $('#header-top').fadeIn(200);
        //$('.navbar-brand').hide();
    } else {
       // $('#go_top').fadeOut(100);
       $('#header-top').hide();
      // $('.navbar-brand').show();
        }
}); // ')' is missing here**      

	 </script>

    <script type="text/javascript">
	

	    $(document).ready(function() {
			/*
			*   Examples - images
			*/

		$('.fancybox').fancybox();
			
			});
			
		 var frmContact = $('#contactForm');
    frmContact.submit(function (ev) {
	
	    ev.preventDefault();	   
	    var  nameContact = $('#name').val();
	    if ((nameContact == '') || (nameContact == null)){
		    alert('Xin vui lòng nhập tên!');
		    return false;
	    }
	    
	   /* var  email = $('#email').val();
	    if ((email == '') || (email == null)){
		    alert('Xin vui lòng nhập email!');
		    return false;
	    }
	    */
	    
	    var  mobile = $('#mobile').val();
	    if ((mobile == '') || (mobile == null)){
		    alert('Xin vui lòng nhập điện thoại!');
		    return false;
	    }
	    			
 
        $.ajax({
            type: frmContact.attr('method'),
            url: frmContact.attr('action'),
            data: frmContact.serialize(),
            success: function (data) {
                  console.log(data);
				   alert('Yêu cầu đã được gửi thành công. Cám ơn Quý khách đã gửi yêu cầu.');
				  // $(this).fadeOut('fast');
		
                
              
            }
        });

        
    });	
			

//<![CDATA[
    $(document).ready(function() {jQuery( ".click_show" ).click(function() {$(this).toggleClass('change_icon');$( ".click_hiden" ).toggle( "slow", function() {});});$( ".show_nav_bar1" ).click(function() {$( ".show1" ).toggle( "slow", function() {});});$(".sub_minus").click(function(){$(this).next('.level0_415').toggle(); });$('.plazart-mainnav').css({'height':(($('.fix_height_mobile').height()))+'px'});$('.header-search button').click(function(){$( ".hiden_search" ).toggle( "slow", function() {});});});
    //]]>
    </script>

    
    
</body>
</html>
