<style>
	h4 {
  font-family: "Caviar Dreams Regular", "Helvetica Neue", Helvetica, Arial, sans-serif;
  font-weight: normal;
}
</style>
<div id="middlecol" class="span8 sidebar_left">
		<div class="inside">
		<div class="item-page">
			<div class="span12">
					<ul class="breadcrumb"><li class="active"><span class=""></span></li><li><a href="/">Home</a><span class="divider">/</span></li> </ul>


<?php echo $this->description; ?>

<?php echo $this->content; ?>



<div style="clear:both;"></div>
	
</div>
				</div>

		</div>
		
		</div>


	