<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    
    <title>Khuyến mãi giảm giá phòng Sheraton lên tới 30%</title>
	<link rel="shortcut icon" href="http://hoabinh-group.com/public/images/favicon-1.ico">
    <!-- Bootstrap -->
    <link href="http://hoabinh-group.com/page/sheraton/css/bootstrap.min.css" rel="stylesheet">
    <link href="http://hoabinh-group.com/page/sheraton/css/style.css" rel="stylesheet">
    <link href="http://hoabinh-group.com/page/sheraton/css/responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="http://sheratonnhatrang.com/assets/v2/css/skin/sheraton.css?v=master-5.02.154">
 <link rel="stylesheet" href="http://www.sheratonnhatrang.com/core/contentblocks/_guest-reviews.scss">
 <link rel="stylesheet" href="http://www.sheratonnhatrang.com/core/_global.scss">

	<link href="/page/sheraton/css/font-awesome.min.css" rel="stylesheet">
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
	  <script type="text/javascript">
/* <![CDATA[ */
var google_conversion_id = 858399483;
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
/* ]]> */
</script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">
</script>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-65825580-1', 'auto');
  ga('send', 'pageview');

</script>
<div style="display:inline;">
<img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/858399483/?guid=ON&amp;script=0"/>
</div>
</noscript>
<style>
.guest-review-details{
    float: none !important;
    margin: 0 auto;
    position: relative;
    top: 80px;
    width: 800px !important;
} 
.truncatorLess{
	color: #fff;
    padding-left: 20px;
    margin-bottom: 20px;
}

</style>
    <div id="header">
	    <div class="col-md-12 col-md-offset-0 col-xs-12">
		    <div class="col-md-1"></div>
		    <div class="logo col-md-7 col-xs-7">
			    <a target="_blank" href="http://hoabinh-group.com"><img class="img-responsive"  src="/page/sheraton/img/web sheraton-01.png" /></a>
		    </div>
		    <div class="col-md-4 col-xs-4">
			     <img class="img-responsive" src="/page/sheraton/img/web sheraton-02.png" />
		    </div>
	    </div>
	    <div class="img-header col-md-12 col-xs-12"> </div>
    </div>
    
    <div id="content">
	    <div id="review">
		   <div class="louis-title">Giới thiệu Sheraton</div> 
		   <div id="video">
	  	
	  		<div id="imgvideo">
		  		<img width="482" height="263" src="/page/sheraton/img/web sheraton-04.png" style="cursor:pointer" /></div>
		  		<img onclick="showvideo();" id="play-video" style="position: relative; margin-top: -1057px; z-index: 100; margin-left: 124px; cursor: pointer;" src="/page/sheraton/img/web sheraton-07.png" />
		  	
	  		<div id="thevideo" style="display:none">									
<iframe width="482" height="263" src="https://www.youtube.com/embed/WoMKioBEi8g?&theme=light&autoplay=0" frameborder="0" allowfullscreen></iframe>
			</div>
			
			
	  		</div>
	  		<div id="video-slider">
	  				   <div class="container">
 <div class="col-md-6" style="position: absolute;margin-left: 0px;left: 50%;width: 578px;"> 
  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel"> 
   <div class="carousel-inner"> 
    <div class="item active"> 
	    
     <div class="row"> 
	
      <div class="col-sm-4 col-md-4"> 
	       <div class="video-title">Sheraton Saigon Hotel & Tower</div>
       <div class="thumbnail"> 
       
   <p>Là khách sạn 5 sao đẳng cấp quốc tế từng đoạt nhiều giải thưởng, nằm ở quận trung tâm và cũng tọa lạc ngay khu kinh doanh sôi động và khu giải trí sầm uất của thành phố Hồ Chí Minh, trên tuyến đường Đồng Khởi nổi tiếng.</p>

<p>Khách sạn có tổng cộng 485 phòng sang trọng được thiết kế rộng rãi với công nghệ hiện đại bậc nhất. </p>

<p>Tất cả các phòng đều có hướng nhìn ra sông Sài Gòn, hướng hồ bơi hoặc hướng nhìn toàn cảnh thành phố đem lại không gian nghỉ ngơi thoáng đãng và thật sự thoải mái. </p>
         
       </div> 
      </div> 
     </div> 
    </div> 
   <div class="item"> 
     <div class="row"> 
      <div class="col-sm-4 col-md-4"> 
	       <div class="video-title">Sheraton Nha Trang Hotel & Spa</div>
       <div class="thumbnail">
       
    - Là khách sạn 5 sao tiêu chuẩn quốc tế.<br/>

- Với 280 phòng nghỉ hướng biển và đều có ban công. <br/>

- Tầm nhìn bao quát vịnh biển Nha Trang. <br/>

- Có 6 nhà hàng và quầy bar hiện đại, bao gồm Altitude – quầy bar cao nhất tại Nha Trang tại tầng 28. <br/>

- Tổng cộng 1.600 m2 phòng hội nghị, trong đó có 2 phòng tiệc lớn và 7 phòng họp nhỏ. <br/>

- Hồ bơi ngoài trời với thiết kế tràn bờ độc đáo.<br/>
         
         
       </div> 
      </div> 
     </div> 
    </div> 

   </div> 
   <a style="margin-left: -44px;background-image: none;margin-top: 108px;" class="left carousel-control" href="http://sheraton/#carousel-example-generic" data-slide="prev"> <img src="/page/sheraton/img/web sheraton-05.png" /> </a> <a class="right carousel-control" href="http://sheraton/#carousel-example-generic" data-slide="next"><img src="/page/sheraton/img/web sheraton-06.png" />  </a> 
  
  </div>
 </div>
</div>
	  		</div>
	


	    </div>
	    <div id="promotion">
		    <div class="container guest-reviews">
			    
	    	<div class="guest-review-details">
            <div class="guest-review-details-col1">
                <h3><span>90<sup>%</sup></span>khách hàng<br> đánh giá tốt về khách sạn này</h3>
                <p class="guest-name">Hà Phương <span class="stars-wrapper"><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></span></p>
                <p class="guest-quote" lang="en"><div class="truncatorLess">
                    <q>Tôi rất hài lòng với phòng ở và các dịch vụ tại sheraton. Nếu có cơ hội tôi sẽ quay lại!</q>
                </div></p>
                <p class="callout"><a href="#" rel="external" target="_blank">Xem thêm các đánh giá khác</a></p>
            </div>
            <div class="guest-review-details-col2">
                <h3>
                    <span>4.5<sup> /5</sup></span> 
                </h3>
                <span class="stars-wrapper" style="color:#fff;"><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i><i class="fa fa-star-o" aria-hidden="true"></i></span>                <ul class="ratings">
                    <li>
                        <p>Tiện nghi phòng</p>
                        <div class="rating-bar">
                            <div class="chunk-1"></div>
                            <div class="chunk-2"></div>
                            <div class="chunk-3"></div>
                            <div class="chunk-4"></div>
                            <div class="active-rating" style="width: 91.938%"></div>
                        </div>
                    </li>
                    <li>
                        <p>Thái độ phục vụ</p>
                        <div class="rating-bar">
                            <div class="chunk-1"></div>
                            <div class="chunk-2"></div>
                            <div class="chunk-3"></div>
                            <div class="chunk-4"></div>
                            <div class="active-rating" style="width: 89.694%"></div>
                        </div>
                    </li>
                    <li>
                        <p>Chất lượng giấc ngủ</p>
                        <div class="rating-bar">
                            <div class="chunk-1"></div>
                            <div class="chunk-2"></div>
                            <div class="chunk-3"></div>
                            <div class="chunk-4"></div>
                            <div class="active-rating" style="width: 91.578%"></div>
                        </div>
                    </li>
                    <li>
                        <p>Cơ sở vật chất</p>
                        <div class="rating-bar">
                            <div class="chunk-1"></div>
                            <div class="chunk-2"></div>
                            <div class="chunk-3"></div>
                            <div class="chunk-4"></div>
                            <div class="active-rating" style="width: 88.616%"></div>
                        </div>
                    </li>
                    <li>
                        <p>Đánh giá của SPG</p>
                        <div class="rating-bar">
                            <div class="chunk-1"></div>
                            <div class="chunk-2"></div>
                            <div class="chunk-3"></div>
                            <div class="chunk-4"></div>
                            <div class="active-rating" style="width: 86.114%"></div>
                        </div>
                    </li>
                    <li>
                        <p>Đồ ăn & thức uống</p>
                        <div class="rating-bar">
                            <div class="chunk-1"></div>
                            <div class="chunk-2"></div>
                            <div class="chunk-3"></div>
                            <div class="chunk-4"></div>
                            <div class="active-rating" style="width: 88.422%"></div>
                        </div>
                    </li>
                </ul>
            </div>
            <div class="review-shadow"></div>
        </div>
	    	</div>
	    	
	    </div>
	    <div class="louis-title" style="margin-top: 10px;margin-bottom: 10px;">Tiếp nhận phản hồi</div>
	    <div class="form_register">
		    <p><b>Hòa Bình Group</b> sẵn sàng đáp ứng mọi yêu cầu mới của Quý khách. Vui lòng
			    điền thông tin vào các mục bên dưới.
		    </p>
		    <hr>
		    <form id="contactForm" action="/default/pages/submit" method="POST" class="">
		    <input id="FULL_NAME" type="text" placeholder="Tên khách hàng" name="FULL_NAME">
		    <input id="PHONE" type="text" placeholder="Số điện thoại" name="PHONE" >
		    <input required pattern="[^@]+@[^@]+\.[a-zA-Z]{2,6}" type="text" placeholder="Email" name="EMAIL">
		    <textarea id="DESCRIPTION" placeholder="Nội dung yêu cầu của bạn" name="DESCRIPTION"></textarea>
		    <button style="background: #8c0d29;color: #fff;padding-top: 5px;">GỬI YÊU CẦU NGAY</button>
		    </form>
	    </div>
	    <div class="bg_form_register"></div>
	    <div id="register-newsletter">
		     
	    	<div id="form-register">
	    		<div class="label-register">HOTLINE TƯ VẤN</div>
	    		<div class="col-md-9" style="margin-top: 16px; font-size: 26px; float: left; display: block; padding-right: 0px; color: #fff;text-align: center;">
		    <!--	Ms. Huyền: 0898.552.338  &nbsp;&nbsp;&nbsp;&nbsp; 	Ms. Hường: 0903.248.618    -->	
		    Ms. Thu: 0919.136.829  &nbsp;&nbsp;&nbsp;&nbsp; 	Ms. Lan: 0913.311.911
	    		</div>
	    	</div>
	    </div>
	    <div class="line-yellow"></div>
    </div>
    
     <div id="footer">
    		<div class="panel-box footer">
	    <div class="row no-gutter">
	   	 	<div class="border-page-footer col-md-10 col-md-offset-1">
		  
		   	 	 <div class="row col-md-12 col-md-offset-0 col-xs-12">
			   	 	 <div class="office-box col-md-4 npl col-xs-4">
			   	<span class="n2"> <img src="/page/sheraton/img/icon-01.png"/></span>
			   <div class="f11a1">
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>29 Doan Thi Diem Str., Dong Da Dist.</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>024.3682.29.29  - 024.3682.28.28</div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i>0913.311.911</div>
<div class="at1"><i class="fa fa-envelope iconvne" aria-hidden="true"></i>info@hoabinhtourist.com</div>

			   </div>
		   	 	</div>
			   	 	 <div class="office-box col-md-4 npl col-xs-4">
		  	<span class="n2"> <img src="/page/sheraton/img/icon-02.png"/></span>
			   <div class="f11a1">
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>217 Tran Phu Str., Hai Chau Dist.</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>0236.399.61.16 </div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i>0903.248.618 - 0903.255.884</div>
<div class="at1"><i class="fa fa-envelope iconvne" aria-hidden="true"></i>info@danangevents.com.vn</div>

			   </div>
			   	 <!--	<a href="#" />
			   	 		<img src="http://vietnamevents.com/images/memberof.png" />
			   	 	</a>-->
		   	 	</div>
		   	 	
			   	 	 <div class="office-box col-md-4 npl col-xs-4">
		<span class="n2"> <img src="/page/sheraton/img/icon-03.png"/></span>
<div class="f11a1">			   	 	
<div class="at1"><i class="fa fa-map-marker iconvne" aria-hidden="true"></i>05 Hoa Cau Str., Phu Nhuan Dist.</div>
<div class="at1"><i class="fa fa-phone iconvne" aria-hidden="true"></i>028.3995.8162 - 028.3995.8163</div>
<div class="at1"><i class="fa fa-mobile iconvne icon-big" aria-hidden="true"></i>0903.248.618 - 0903.255.884</div>
<div class="at1"><i class="fa fa-envelope iconvne" aria-hidden="true"></i>info@hoabinh-group.com</div>
		   	 	</div>
		   	 	</div>
		   	 	 </div>
		   	 	<div class="row col-md-12 col-md-offset-0">
			   
		   	 	</div>
		   	 	 <div class="col-menu-footer row col-md-12 col-md-offset-0">
			   	 	 
		  
		   	 	
		   	 	
		   	
	   	 	</div>
	    </div>
      </div>
    
</div>
    		
    	</div>
   
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="http://hoabinh-group.com/page/sheraton/js/bootstrap.min.js"></script>
    
   
    <script type="text/javascript">
	    function showvideo(o){
	$('#imgvideo').hide();
	$('#thevideo').show();
	 $('#thevideo').children('iframe').attr("src", $('#thevideo').children('iframe').attr("src").replace("autoplay=0", "autoplay=1"));
	  $('#play-video').hide();
}
	   </script>
	   
	   <script type="text/javascript">
	
	
	 var frmContact = $('#contactForm');
    frmContact.submit(function (ev) {
	    ev.preventDefault();	   
	    var  nameContact = $('#FULL_NAME').val();
	    if ((nameContact == '') || (nameContact == null)){
		    alert('Xin vui lòng nhập tên!');
		    return false;
	    }
	    			
 
        $.ajax({
            type: frmContact.attr('method'),
            url: frmContact.attr('action'),
            data: frmContact.serialize(),
            success: function (data) {
                  console.log(data);
				   alert('Yêu cầu đã được gửi thành công. Cám ơn Quý khách đã gửi yêu cầu.');
				  // $(this).fadeOut('fast');
		
                
              
            }
        });

        
    });
</script>

<script type='text/javascript'>window._sbzq||function(e){e._sbzq=[];var t=e._sbzq;t.push(["_setAccount",67985]);var n=e.location.protocol=="https:"?"https:":"http:";var r=document.createElement("script");r.type="text/javascript";r.async=true;r.src=n+"//static.subiz.com/public/js/loader.js";var i=document.getElementsByTagName("script")[0];i.parentNode.insertBefore(r,i)}(window);</script>	
  </body>
</html>