	<div class="row">
		

									<div class="col-xs-12">
										<h3 class="header smaller lighter blue">Khai báo danh mục » Danh mục sự kiện</h3>
									

										<div class="table-responsive">
											<table id="table_events" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														
														<th style="text-align: center;vertical-align: middle;">STT</th>
														<th style="text-align: center;vertical-align: middle;">Tên sự kiện</th>
                                                        <th style="text-align: center;vertical-align: middle;">Ngày bắt đầu</th>
                                                        <th style="text-align: center;vertical-align: middle;">Ngày kết thúc</th>
                                                        <th style="text-align: center;vertical-align: middle;">Địa điểm tổ chức hội nghị</th>
														<th style="text-align: center;vertical-align: middle;">Action</th>
													</tr>
												</thead>

												<tbody>
				<?php echo $this->partialLoop('_events-row.phtml', $this->products); ?>																						

												</tbody>
											</table>
											
										</div>
								
<br/>
<a class="btn btn-info btn-sm" href="/admin/events/create">Tạo mới</a>
										
									</div>
								</div>
	<br/>
	
	
						
<script type="text/javascript">
			jQuery(function($) {
				var oTable1 = $('#table_events').dataTable( {
				"aoColumns": [
			      { "bSortable": false },
			      null, null
				] } );
				
				
			})
		</script>									
