<?php echo $this->doctype() ?>  
<html>
    <head>  
     <meta http-equiv="content-type" content="text/html; charset=UTF-8"> 
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />   
    <?php echo $this->headTitle() ?>  
    <?php echo $this->headMeta() ?>       

		<link href="/<?=SHARE?>/assets/css/bootstrap.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/font-awesome.min.css" />

		<!--[if IE 7]>
		  <link rel="stylesheet" href="/<?=SHARE?>assets/css/font-awesome-ie7.min.css" />
		<![endif]-->

		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace-fonts.css" />
      <link rel="stylesheet" href="/<?=SHARE?>/assets/css/chosen.min.css" />
      <link rel="stylesheet" href="/<?=SHARE?>/assets/css/jquery-ui-1.10.3.custom.min.css" />
		<!-- ace styles -->

		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace.min.css" />
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace-rtl.min.css" />
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace-skins.min.css" />

		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace-ie.min.css" />
		<![endif]-->
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/datepicker.css" />
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/bootstrap-timepicker.css" />
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/style.css" />
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/custom_style.css" />
	
		<script src="/<?=SHARE?>/assets/js/ace-extra.min.js"></script>
		
		
		<link rel="stylesheet" href="../assets/css/bootstrap.css" />
		<link rel="stylesheet" href="../assets/css/font-awesome.css" />

		<!-- page specific plugin styles -->
		<link rel="stylesheet" href="../assets/css/jquery-ui.custom.css" />
		<link rel="stylesheet" href="../assets/css/chosen.css" />
		<link rel="stylesheet" href="../assets/css/datepicker.css" />
		<link rel="stylesheet" href="../assets/css/bootstrap-timepicker.css" />
		<link rel="stylesheet" href="../assets/css/daterangepicker.css" />
		<link rel="stylesheet" href="../assets/css/bootstrap-datetimepicker.css" />
		<link rel="stylesheet" href="../assets/css/colorpicker.css" />

		<!-- text fonts -->
		<link rel="stylesheet" href="../assets/css/ace-fonts.css" />

		<!-- ace styles -->
		<link rel="stylesheet" href="../assets/css/ace.css" class="ace-main-stylesheet" id="main-ace-style" />

		<!--[if lte IE 9]>
			<link rel="stylesheet" href="../assets/css/ace-part2.css" class="ace-main-stylesheet" />
		<![endif]-->

		<!--[if lte IE 9]>
		  <link rel="stylesheet" href="../assets/css/ace-ie.css" />
		<![endif]-->

		<!-- inline styles related to this page -->

		<!-- ace settings handler -->
		<script src="../assets/js/ace-extra.js"></script>
		
		

		<!--[if lt IE 9]>
		<script src="/<?=SHARE?>/assets/js/html5shiv.js"></script>
		<script src="/<?=SHARE?>/assets/js/respond.min.js"></script>
		<![endif]-->
		<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" type="text/javascript"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.dataTables.min.js" type="text/javascript"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.dataTables.bootstrap.js" type="text/javascript"></script>
	
		<script src="/<?=SHARE?>/assets/js/date-time/bootstrap-datepicker.min.js" type="text/javascript"></script>
		<script src="/<?=SHARE?>/assets/js/date-time/bootstrap-timepicker.min.js" type="text/javascript"></script>
		<script src="/<?=SHARE?>/assets/js/date-time/moment.min.js" type="text/javascript"></script>
		
		<script src="/<?=SHARE?>/js/functions.js" type="text/javascript"></script>
		
		
		
	</head>
	<style>
	.nav-list li.active > a:after{
		border-width:0px;
	}
	.breadcrumbs{
		padding-top: 6px;
	}
	dt{
		margin: 10px;
	}
	#subcategoryId-label{
		display: none;
	}
	#subcategoryId-element{
		margin-top: 10px;
	}
	label{
		font-weight: bold;
	}
	</style>
<body>
		<div class="navbar navbar-default" id="navbar">
			<script type="text/javascript">
				try{ace.settings.check('navbar' , 'fixed')}catch(e){}
			</script>

			<div class="navbar-container" id="navbar-container">
				<div class="navbar-header pull-left">
					<a href="#" class="navbar-brand">
						<small>
							<i class="icon-leaf"></i>
							LOUIS INTELLI CMS
						</small>
					</a><!-- /.brand -->
				</div><!-- /.navbar-header -->

				<div class="navbar-header pull-right" role="navigation">
					<ul class="nav ace-nav">
						<li class="grey">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<i class="icon-tasks"></i>
								<span class="badge badge-grey">4</span>
							</a>

							<ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
								<li class="dropdown-header">
									<i class="icon-ok"></i>
									4 Tasks to complete
								</li>

							</ul>
						</li>

						<li class="purple">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<i class="icon-bell-alt icon-animated-bell"></i>
								<span class="badge badge-important">8</span>
							</a>

							<ul class="pull-right dropdown-navbar navbar-pink dropdown-menu dropdown-caret dropdown-close">
								<li class="dropdown-header">
									<i class="icon-warning-sign"></i>
									8 Notifications
								</li>

								
							</ul>
						</li>

						<li class="green">
							<a data-toggle="dropdown" class="dropdown-toggle" href="#">
								<i class="icon-envelope icon-animated-vertical"></i>
								<span class="badge badge-success">5</span>
							</a>

							<ul class="pull-right dropdown-navbar dropdown-menu dropdown-caret dropdown-close">
								<li class="dropdown-header">
									<i class="icon-envelope-alt"></i>
									5 Messages
								</li>

							</ul>
						</li>

						<li class="light-blue">
	<?php     try {
		 echo $this->layout()->userForm = $this->action('showinfouser', 'admin-user','user');
				       
				    } catch (Zend_Exception $e) {
				        echo "Caught exception: " . get_class($e) . "\n";
				        echo "Message: " . $e->getMessage() . "\n";
				      
				    }
				      ?>
						</li>
					</ul><!-- /.ace-nav -->
				</div><!-- /.navbar-header -->
			</div><!-- /.container -->
		</div>

		<div class="main-container" id="main-container">
			<script type="text/javascript">
				try{ace.settings.check('main-container' , 'fixed')}catch(e){}
			</script>

			<div class="main-container-inner">
				<a class="menu-toggler" id="menu-toggler" href="#">
					<span class="menu-text"></span>
				</a>

				<div class="sidebar" id="sidebar">
					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'fixed')}catch(e){}
					</script>

					<div class="sidebar-shortcuts" id="sidebar-shortcuts">
						<div class="sidebar-shortcuts-large" id="sidebar-shortcuts-large">
							<button class="btn btn-success">
								<i class="icon-signal"></i>
							</button>

							<button class="btn btn-info">
								<i class="icon-pencil"></i>
							</button>

							<button class="btn btn-warning">
								<i class="icon-group"></i>
							</button>

							<button class="btn btn-danger">
								<i class="icon-cogs"></i>
							</button>
						</div>

						<div class="sidebar-shortcuts-mini" id="sidebar-shortcuts-mini">
							<span class="btn btn-success"></span>

							<span class="btn btn-info"></span>

							<span class="btn btn-warning"></span>

							<span class="btn btn-danger"></span>
						</div>
					</div><!-- #sidebar-shortcuts -->

					
						

<?php
	try {      
            
     //  echo dirname(__FILE__); 
   //  echo Zend_Version::getLatest();
 echo $this->layout()->adminMenu = $this->action('render', 'menu', 'admin', array('menu' => 3));  
//echo $this->adminMenuId;
// echo $this->layout()->adminMenu = $this->loo; 
 //  throw new Exception('');
            
         } catch (Zend_Exception $e) {
       echo "Caught exception: " . get_class($e) . "\n";   
    die ('Error: ' . $e->getMessage(). $e->getLine());
		} 
 ?>
     
												
					<!-- /.nav-list -->

					<div class="sidebar-collapse" id="sidebar-collapse">
						<i class="icon-double-angle-left" data-icon1="icon-double-angle-left" data-icon2="icon-double-angle-right"></i>
					</div>

					<script type="text/javascript">
						try{ace.settings.check('sidebar' , 'collapsed')}catch(e){}
					</script>
				</div>

				<div class="main-content">
					<div class="breadcrumbs" id="breadcrumbs">
						<script type="text/javascript">
							try{ace.settings.check('breadcrumbs' , 'fixed')}catch(e){}
						</script>

						<ul class="breadcrumb">
						
							<?php echo $this->AdminBreadcrumbs(); ?>
				
						</ul><!-- .breadcrumb -->

						<div class="nav-search" id="nav-search">
							<form class="form-search">
								<span class="input-icon">
									<input type="text" placeholder="Search ..." class="nav-search-input" id="nav-search-input" autocomplete="off" />
									<i class="icon-search nav-search-icon"></i>
								</span>
							</form>
						</div><!-- #nav-search -->
					</div>

					<div class="page-content">
						
   
						 <?php echo $this->layout()->content; ?>
						
					</div><!-- /.page-content -->
				</div><!-- /.main-content -->

				
			</div><!-- /.main-container-inner -->

			<a href="#" id="btn-scroll-up" class="btn-scroll-up btn btn-sm btn-inverse">
				<i class="icon-double-angle-up icon-only bigger-110"></i>
			</a>
		</div><!-- /.main-container -->

		<!-- basic scripts -->

		<!--[if !IE]> -->

		<script type="text/javascript">
			window.jQuery || document.write("<script src='/<?=SHARE?>/assets/js/jquery-2.0.3.min.js'>"+"<"+"/script>");
		</script>

		<!-- <![endif]-->

		<!--[if IE]>
<script type="text/javascript">
 window.jQuery || document.write("<script src='/<?=SHARE?>/assets/js/jquery-1.10.2.min.js'>"+"<"+"/script>");
</script>
<![endif]-->

		<script type="text/javascript">
			if("ontouchend" in document) document.write("<script src='/<?=SHARE?>/assets/js/jquery.mobile.custom.min.js'>"+"<"+"/script>");
		</script>
		<script type="text/javascript" src="/<?=SHARE?>/assets/js/bootstrap.min.js"></script>
		<script type="text/javascript" src="/<?=SHARE?>/assets/js/typeahead-bs2.min.js"></script>

		<!-- page specific plugin scripts -->

		<!--[if lte IE 8]>
		  <script src="/<?=SHARE?>/assets/js/excanvas.min.js"></script>
		<![endif]-->

		<!--<script src="/<?=SHARE?>/assets/js/jquery-ui-1.10.3.custom.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.ui.touch-punch.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.slimscroll.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.easy-pie-chart.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.sparkline.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/flot/jquery.flot.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/flot/jquery.flot.pie.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/flot/jquery.flot.resize.min.js"></script>-->

		<!-- ace scripts -->

		<!--<script src="/<?=SHARE?>/assets/js/ace-elements.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/ace.min.js"></script>-->

		<!-- inline scripts related to this page -->


		
	</body>

</html>

<script type="text/javascript">
$(document).ready(function() { 
 //alert(322);
var url = window.location.pathname.split('/');

var page = url[2];
 // alert(page);
   $('.nav-list li').find('ul').addClass('submenu').css('display','none');
   $('.nav li a').each(function(){
   var href = $(this).attr('href').split('/');
   var pageh = href[2];
     if(pageh == page){
      
     // $('.nav li').append('<b class="arrow icon-angle-down"></b>');
      //$(this).attr('class','dropdown-toggle');
	   // $('.submenu li a').removeClass('dropdown-toggle'); 
	     $(this).parent().find('.submenu').css('display','block');
	     $(this).parent().addClass('active');
	   // $('.submenu li a').parent().addClass('active');
	   
     }
   });
   
  
}); 
</script>