<div class="row">
<div class="col-sm-6">
<div class="widget-box transparent">
    <div class="widget-header widget-header-flat">
    	<h4 class="lighter">
    		<i class="icon-star orange"></i>
    		Danh mục Users
    	</h4>

    	
    </div>


<?php if($this->users != null) { ?>
<div class="widget-body">
	<div class="widget-main no-padding">
	    <table class="table table-bordered table-striped">
	    	<thead class="thin-border-bottom">
	    		<tr>
	    			<th>
	    				<i class="icon-caret-right blue"></i>
	    				Thao tác
	    			</th>

			<th class="hidden-480">
			    	<i class="icon-caret-right blue"></i>
			    				Last Name
			    			</th>
			<th class="hidden-480">
			    	<i class="icon-caret-right blue"></i>
			    				First Name
			    			</th>    
			 <th class="hidden-480">
			    	<i class="icon-caret-right blue"></i>
			    				Username
			    			</th>
			  <th class="hidden-480">
			    	<i class="icon-caret-right blue"></i>
			    				Quyền hạn
			    			</th>    			    						
			    </tr>
		  </thead>
		  <tbody>
    <?php echo $this->partialLoop('_user-row.phtml', $this->users); ?>
		  </tbody>
	    			</table>
	    		</div><!-- /widget-main -->
	    	</div><!-- /widget-body -->
	    </div><!-- /widget-box -->
	</div>
</div>

<?php }else{?>
<p>Chưa có user nào.</p>
<?php }?>

<a class="btn btn-info btn-sm" href='/<?=ADMIN?>/user/create'>Thêm User</a>
    
<?php //ECHO $_SERVER['DOCUMENT_ROOT'] ?>