		   			   			   			   			   			   			   			   			   			   			   			   			   			   			   	 <ul class="nav navbar-nav nav-first">
     <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="#">Intro <span class="caret"></span></a>
     	<ul class="dropdown-menu">
	     <li><a href="/about-us">About</a></li>
		 <li><a href="/financial-capacity">Financial Capacity</a></li>
		 <li><a href="/core-values">Core Values</a></li>
		 <li><a href="/the-mark-of-development">The mark of development</a></li>
		 <li><a href="/leadership-team">Leadership Team</a></li>
	 	</ul>
	 </li>
     <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/about-us/index">Activities Fields <span class="caret"></span></a>
     	<ul class="dropdown-menu">
	     <li><a href="/field/organizing-conference-seminars">0rganizing conference seminars</a></li>
		 <li><a href="/field/organizing-events">Organizing events</a></li>
		 <li><a href="/field/media-advertising-solution"> Media advertising solution</a></li>
		 <li><a href="/field/organizing-tour-and-teambuilding">Organizing tour and teambuilding</a></li>
		 <li><a href="/field/event-equipment-supply">Event equipment supply</a></li>
	 	</ul>
	 </li>
	 <li class="dropdown">
	 <a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/news">News <span class="caret"></span></a>
	   <ul class="dropdown-menu">
		   <li><a href="/news/promotion-news">Promotion News</a></li>
		   <li><a href="/news/news-press">News press</a></li>
		   <li><a href="/news/internal">Internal</a></li>
		   <li><a href="/news/typical-conference-events">Typical conference events</a></li>
		   <li><a href="/news/mice-news">MICE News</a></li>
           <li><a href="/news/handbook">Handbook</a></li>
		</ul>
		</li>
		<li><a href="/ban-tin">Internal</a></li>
   </ul>
   <div class="logo hidden-xs">
		   <a class="navbar-brand" href="/">
	       <img width="220" src="/public/images/logo en-01.png" />
		   </a>

   </div>
	<ul class="nav navbar-nav nav-after">
		<li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false" href="/gallery-index">Library <span class="caret"></span></a>
			<ul class="dropdown-menu">
				<li><a href="/gallery">Gallery</a></li>
				<li><a href="/video">Video</a></li>
			</ul>
		</li>
		
		<li><a target="_blank" rel="nofollow" href="http://membershipcard.hoabinh-group.com">Membership Card</a></li>  
        <li><a href="/contact">Contact</a></li>
		<li><a href="/recruitment">Recruitment</a></li> 
		   </ul>			 			 			 			 			 			 			 			 			 			 			 			 			 			 			 