 <div class="bg-header-page" style="background-image: url('<?=TEMPLATE_URL?>/default/img/banner-layout-visa-purchase-alerts-background.jpg'); background-position: 0px 0px;">
		   <div class="container"> <div class="row">
			   
		  
		 <h1 style="color: #272f67">Contact Us</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a style="color: #272f67" href="#">Home</a></li>
  <li class="breadcrumb-item active" style="color: #272f67 !important;">Contact</li>
</ol>

 </div> </div>
	    </div>
	    
	    <div class="row" id = "news-content">
	    <div class="review-content">
		     <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script><div style="overflow:hidden;height:1400px;width:2000px;"><div id="gmap_canvas" style="height:100%;width:100%;"></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style><a class="google-map-code" href="http://www.map-embed.com" id="get-map-data">http://www.map-embed.com/</a></div><script type="text/javascript"> function init_map(){var myOptions = {zoom:6,center:new google.maps.LatLng(11.02608197684531,120.83278650898433),mapTypeId: google.maps.MapTypeId.ROADMAP};map = new google.maps.Map(document.getElementById("gmap_canvas"), myOptions);
  marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(21.02608197684531, 105.83278650898433)});
  
    marker2 = new google.maps.Marker({map: map,position: new google.maps.LatLng(16.064459, 108.223498)});
    
     marker3 = new google.maps.Marker({map: map,position: new google.maps.LatLng(10.799412, 106.688177)});
  
  infowindow = new google.maps.InfoWindow({
		content:"<div style='float:left'><img width='200' src='http://hoabinh-group.com/public/templates/news/default/images/logo_hbgroupvn.png'/></div><div style='font-weight:bold; font-size:16px;'><b>Hoa Binh Group</b><br/>29 Doan Thi Diem Street, Quoc Tu Giam Ward, Dong Da Dist, Hanoi City</div>" 
		});
	  infowindow2 = new google.maps.InfoWindow({
		content:"<div style='float:left'><img width='200' src='http://hoabinh-group.com/public/templates/news/default/images/logo_hbgroupvn.png'/></div><div style='font-weight:bold; font-size:16px;'><b>Da nang Office</b><br/> 217 Tran Phu, Hai Chau Dist, Da Nang City.</div>" 
		});	
		
		 infowindow3 = new google.maps.InfoWindow({
		content:"<div style='float:left'><img width='200' src='http://hoabinh-group.com/public/templates/news/default/images/logo_hbgroupvn.png'/></div><div style='font-weight:bold; font-size:16px;'><b>Văn phòng miền Nam</b><br/>05 Hoa Cau, Phu Nhuan dist, TP.HCM City</div>" 
		});	
		
	//	google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});
	//	google.maps.event.addListener(marker2, "click", function(){infowindow2.open(map,marker2);});
	//	google.maps.event.addListener(marker3, "click", function(){infowindow3.open(map,marker3);});
		infowindow.open(map,marker);
		infowindow2.open(map,marker2);
		infowindow3.open(map,marker3);
		//infowindow.open(map,marker);
		}
		google.maps.event.addDomListener(window, 'load', init_map);</script>
	  	
	   <div class="col-md-7"></div>
	    	<div id="louis-panel-contact" class="col-md-5 col-xs-12">
	     <div class="panel">
    <div class="panel-heading">CONTACT US</div>
    <div class="panel-body">
	    
	    <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="firstname" placeholder="Your name" type="text" required autofocus />
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="lastname" placeholder="Your Email" type="text" required />
                                </div>
                            </div>
                          
         <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="firstname" placeholder="Your Mobile phone" type="text" required autofocus />
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="lastname" placeholder="Your address" type="text" />
                                </div>
                            </div>              
                           
            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12" style="padding-bottom: 10px;">
             <div class="form-group">
  <select class="form-control" id="sel1">
	  <option>Select request</option>
    <option value="Other request">Other</option>
    <option value="Complaint service">Complaint service</option>
    <option value="Ask for advice">Ask for advice</option>
    <option value="Request for cooperation">Request for cooperation</option>
  </select>
</div>
                                </div>
                            </div>
            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <textarea style="resize:vertical;" class="form-control" placeholder="Message..." rows="6" name="comment" required></textarea>
                                </div>
                            </div>
                            
             <div class="row">
	           <input type="submit" value="SEND REQUEST" class="submit-contact">
             </div>
             
            <div class="row" style="padding: 20px;">
	           <p>  <h5>CONTACT WITH HOA BINH GROUP</h5></p>
	            
	          <p><i class="fa fa-map-marker" aria-hidden="true"></i> <b> HANOI OFFICE:</b> <br/>
	            Hotline: +84.913.311.911
	          </p>
	          <p>
	           <i class="fa fa-map-marker" aria-hidden="true"></i><b> DANANG OFFICE:</b> <br/>
	            Hotline: +84.913.186.829
	          </p>
	          <p>
	          <i class="fa fa-map-marker" aria-hidden="true"></i> <b>  TP.HCM OFFICE:</b> <br/>
	            Hotline: +84.98.98.98.198
	          </p>
            </div>
          
    </div>
    
   		 </div><!--.panel-->
	    	  
	    	
	    	</div>
	    </div>	
	      </div>	