 <div class="bg-header-page" style="background-image: url('<?=TEMPLATE_URL?>/default/img/banner-layout-visa-purchase-alerts-background.jpg'); background-position: 0px 0px;background-attachment: fixed;">
		   <div class="container"> <div class="row">

		 <h1 style="color: #272f67">Liên hệ với chúng tôi</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a style="color: #272f67" href="#">Trang chủ</a></li>
  <li class="breadcrumb-item active" style="color: #272f67 !important;">Liên hệ</li>
</ol>

 </div> </div>
	    </div>
	    
	    <div class="row" id = "news-content">
	    <div class="review-content">
		     <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script><div style="position: relative; overflow: hidden;height: 800px;"><div id="gmap_canvas" style="height:100%;width:100%;position: absolute;top: 0px;left: 0px;background-color: rgb(229, 227, 223);"></div><style>#gmap_canvas img{max-width:none!important;background:none!important}</style><a class="google-map-code" href="http://www.map-embed.com" id="get-map-data">http://www.map-embed.com/</a></div><script type="text/javascript"> function init_map(){
			     var myOptions = {
			     zoom:6,
			    
			     scaleControl: false,
			     scrollwheel: false,
			     
			     center:new google.maps.LatLng(15.02608197684531,110.83278650898433),
			     mapTypeId: google.maps.MapTypeId.ROADMAP};
			     map = new google.maps.Map(document.getElementById("gmap_canvas"), 
			     myOptions
			     );
  marker = new google.maps.Marker({map: map,position: new google.maps.LatLng(21.02608197684531, 105.83278650898433)});
  
    marker2 = new google.maps.Marker({map: map,position: new google.maps.LatLng(16.064459, 108.223498)});
    
     marker3 = new google.maps.Marker({map: map,position: new google.maps.LatLng(10.799412, 106.688177)});
  
  infowindow = new google.maps.InfoWindow({
		content:"<div style='float:left'><img width='200' src='http://hoabinh-group.com/public/templates/news/default/images/logo_hbgroupvn.png'/></div><div style='font-weight:bold; font-size:16px;'><b>Hòa Bình Group</b><br/>29 Doan Thi Diem Street, Quoc Tu Giam Ward, Dong Da Dist, Hanoi City</div>" 
		});
	  infowindow2 = new google.maps.InfoWindow({
		content:"<div style='float:left'><div style='font-weight:bold; font-size:16px;'><b>Văn phòng miền Trung</b><br/> 217 Trần Phú, quận Hải Châu, TP. Đà Nẵng</div>" 
		});	
		
		 infowindow3 = new google.maps.InfoWindow({
		content:"<div style='float:left'><div style='font-weight:bold; font-size:16px;'><b>Văn phòng miền Nam</b><br/>5 Hoa Cau, Phường 7, Quận Phú Nhuận, TP.HCM</div>" 
		});	
		
	//	google.maps.event.addListener(marker, "click", function(){infowindow.open(map,marker);});
	//	google.maps.event.addListener(marker2, "click", function(){infowindow2.open(map,marker2);});
	//	google.maps.event.addListener(marker3, "click", function(){infowindow3.open(map,marker3);});
		infowindow.open(map,marker);
		infowindow2.open(map,marker2);
		infowindow3.open(map,marker3);
		}
		google.maps.event.addDomListener(window, 'load', init_map);</script>
	  	
	   <div class="col-md-7"></div>
	    	<div id="louis-panel-contact" class="col-md-5 col-xs-12">
	     <div class="panel">
    <div class="panel-heading">LIÊN HỆ VỚI CHÚNG TÔI</div>
    <div class="panel-body">
	    <div id="loadding">
	    	
	    </div>
	    <form name="contactForm" id="contactForm" method="post" action="/default/contact/submit">
	    <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="name" id="name" placeholder="Tên khách hàng" type="text" required autofocus />
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="email" id="email" placeholder="Địa chỉ Email" type="text" required />
                                </div>
                            </div>
                          
         <div class="row">
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="phone" id="phone" placeholder="Số điện thoại" type="text" required autofocus />
                                </div>
                                <div class="col-lg-6 col-md-6 col-sm-6" style="padding-bottom: 10px;">
                                    <input class="form-control" name="company" id="company" placeholder="Địa chỉ" type="text" />
                                </div>
                            </div>              
                           
            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12" style="padding-bottom: 10px;">
             <div class="form-group">
  <select name="request" class="form-control" id="request">
	  <option>Chọn loại yêu cầu</option>
    <option value="Yêu cầu khác">Khác</option>
    <option value="Khiếu nại dịch vụ">Khiếu nại dịch vụ</option>
    <option value="Yêu cầu tư vấn">Yêu cầu tư vấn</option>
    <option value="Yêu cầu hợp tác">Yêu cầu hợp tác</option>
  </select>
</div>
                                </div>
                            </div>
            <div class="row">
                                <div class="col-lg-12 col-md-12 col-sm-12">
                                    <textarea name="message" id="message" style="resize:vertical;" class="form-control" placeholder="Nội dung liên hệ..." rows="6" name="comment" required></textarea>
                                </div>
                            </div>
                            
             <div class="row">
	           <input type="submit" value="GỬI YÊU CẦU" class="submit-contact">
             </div>
	    </form>
            <div class="row" style="padding: 20px;">
	           <p>  <h5>LIÊN HỆ TRỰC TIẾP VỚI HÒA BÌNH GROUP</h5></p>
	            
	          <p><i class="fa fa-map-marker" aria-hidden="true"></i> <b> Trụ sở tại Hà Nội:</b> <br/>
	            Hotline: +84.913.311.911
	          </p>
	          <p>
	           <i class="fa fa-map-marker" aria-hidden="true"></i><b> Văn phòng miền Trung:</b> <br/>
	            Hotline: +84.913.186.829
	          </p>
	          <p>
	          <i class="fa fa-map-marker" aria-hidden="true"></i> <b>  Văn phòng miền Nam:</b> <br/>
	            Hotline: +84.98.98.98.198
	          </p>
            </div>
          
    </div>
    
   		 </div><!--.panel-->
	    	  
	    	
	    	</div>
	    </div>	
	      </div>
<script type="text/javascript">
	
	
/*	 var frmContact = $('#contactForm');
    frmContact.submit(function (ev) {
	    ev.preventDefault();	   
	    var  nameContact = $('#name').val();
	 var  emailContact = $('#email').val();
	 var  phone = $('#phone').val();
	    if ((nameContact == '') || (nameContact == null)){
		    alert('Please enter Your Name!');
		    return false;
	    }else if(emailContact == ''){
		    alert('Please enter Your Email!');
		     return false;
		 }}else if(phone == ''){
		    alert('Please enter Your Phone!');
		     return false;
		 }
    			
 
        $.ajax({
            type: frmContact.attr('method'),
            url: frmContact.attr('action'),
            data: frmContact.serialize(),
            success: function (data) {
               // console.log(data);
				   alert('Cám ơn quý khách!');
				  // $(this).fadeOut('fast');
		
                
              
            }
        });
*/
       
</script>
	