	<div class="row">

									<div class="col-xs-12">
										<h3 class="header smaller lighter blue">Quản lý Đơn đặt Tour</h3>
									
<?php
if($this->result != null) {
?>
										<div class="table-responsive">
											<table id="sample-table-3" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														<th class="center">
															<label>
																<input type="checkbox" class="ace" />
																<span class="lbl"></span>
															</label>
														</th>
														
														<th>Tên khách hàng</th>
														<th>Email</th>
														<th>Mobile</th>
														<th>Địa chỉ</th>
														<th class="center sorting_disabled">Link</th>
													</tr>
												</thead>

												<tbody>
				<?php echo $this->partialLoop('_product-booking-row.phtml', $this->result); ?>																						

												</tbody>
											</table>
										</div>
	<?php }else{?>
<p>Bạn chưa có sản phẩm nào!</p>
<?php }?>									
										
									</div>
								</div>
	<br/>
							
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" type="text/javascript"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.dataTables.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.dataTables.bootstrap.js"></script>						
<script type="text/javascript">
			jQuery(function($) {
				var oTable1 = $('#sample-table-2').dataTable( {
				"aoColumns": [
			      { "bSortable": false },
			      null, null, null,
				  { "bSortable": false }
				] } );
				
				
				$('table th input:checkbox').on('click' , function(){
					var that = this;
					$(this).closest('table').find('tr > td:first-child input:checkbox')
					.each(function(){
						this.checked = that.checked;
						$(this).closest('tr').toggleClass('selected');
					});
						
				});
			
			
			})
		</script>									
