<link rel="stylesheet" href="/public/assets/css/jquery-ui-1.10.3.custom.min.css" />
<script src="/public/scripts/ckeditor/ckeditor.js" type="text/javascript"></script>

	
<style>
.zend_form p{
	 padding-left: 20px;
}
#location-element{
	margin-left: 20px;
	width: 500px;
	}
#location___chosen{
	width: 500px;
	
}
#cke_description{
	margin-left: 20px;
}
#cke_others{
	margin-left: 20px;
}
.tags{
	margin-left: 20px;
	width: 550px;
}
</style>
<?php
	/*
$list = new Zend_Tag_ItemList();	
$list[] = new Zend_Tag_Item(array('title' => 'Code', 'weight' => 50));
$list[] = new Zend_Tag_Item(array('title' => 'Zend Framework', 'weight' => 1));


    $cloud = new Zend_Tag_Cloud(array(
           'tags' => array(
                     array('title' => 'Code', 'weight' => 50,
                           'params' => array('url' => '/tag/code')),
                     array('title' => 'Zend Framework', 'weight' => 1,
                           'params' => array('url' => '/tag/zend-framework')),
                     array('title' => 'PHP', 'weight' => 5000,
                           'params' => array('url' => '/tag/php')),
        )));
    echo $cloud;

	*/

?>
  <h2><a href="/admin/product/list_video">Danh mục Video</a> | Thêm bài mới</h2>
<br/>
<?php echo $this->form; ?> 	
<?php //echo $this->Ckeditor('shortDescription',150,600); ?> 
 <?php echo $this->Ckeditor('description',250,550); ?> 
  <?php echo $this->Ckeditor('others',250,550); ?> 
 

<script src="/public/assets/js/ace.min.js"></script>
	<script src="/public/assets/js/bootstrap-tag.min.js"></script>	
		
	<script src="/public/assets/js/chosen.jquery.min.js"></script>
												

<script>
	$.validator.addMethod("valueNotEquals", function(value, element, arg){
  return arg != value;
 }, "Value must not equal arg.");

 // configure your validation
 $("form").validate({
  rules: {
   SelectName: { valueNotEquals: "default" }
  },
  messages: {
   SelectName: { valueNotEquals: "Please select an item!" }
  }  
 });
</script>