<div class="row">
									<div class="col-xs-12">
										<h3 class="header smaller lighter blue">Quản lý Blog</h3>
										<div class="table-header">
											Danh sách các bài viết
										</div>
<?php
if($this->pages != null) {
?>
										<div class="table-responsive">
											<table id="sample-table-2" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														<th class="center">
															<label>
																<input type="checkbox" class="ace" />
																<span class="lbl"></span>
															</label>
														</th>
														<th class="center sorting_disabled">Links</th>
														<th>Name</th>
														<th>Description</th>
														
													</tr>
												</thead>

												<tbody>
				<?php echo $this->partialLoop('partials/_blog-row.phtml', $this->pages); ?>																						

												</tbody>
											</table>
										</div>
	<?php }else{?>
<p>You do not have any pages yet.</p>
<?php }?>									
										
									</div>
								</div>
							<br/>	
<a class="btn btn-info btn-sm" href='/<?=ADMIN?>/blog/create'>Viết bài mới</a>							
								<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js" type="text/javascript"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.dataTables.min.js"></script>
		<script src="/<?=SHARE?>/assets/js/jquery.dataTables.bootstrap.js"></script>						
<script type="text/javascript">
			jQuery(function($) {
				var oTable1 = $('#sample-table-2').dataTable( {
				"aoColumns": [
			      { "bSortable": false },
			      null, null,
				  { "bSortable": false }
				] } );
				
				
				$('table th input:checkbox').on('click' , function(){
					var that = this;
					$(this).closest('table').find('tr > td:first-child input:checkbox')
					.each(function(){
						this.checked = that.checked;
						$(this).closest('tr').toggleClass('selected');
					});
						
				});
			
			
			})
		</script>									