 <div class="bg-header-page" style="background-image: url('/hbg/img/v-mezhdunarodnyiy-fond-selskohozyaystvennogo-razvitiya-vstupaet-rossiya.jpg'); background-position: 0px -101px;background-attachment: fixed;">
		    <div class="container"> 
			    <div class="row">
		 <h1>Tin tức</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="#">Home</a></li>
  <li class="breadcrumb-item"><a href="#">Tin tức</a></li>
  <li class="breadcrumb-item active">Tin khuyến mại</li>
</ol>
	</div> 
			</div>
	    </div>
	    <div class="container">
	    <div class="row" id = "news-content">
		   <div class="news-description col-md-8"> 
			   
		     <div class="item-new" data-aos="fade-up" data-aos-duration="2500">
			 		<div class="col-md-1">&nbsp;</div>
		       	    <div class="col-md-11 border-timline">
			       	 <div class="row">
			    <div class="panel-body">
					<a href="#"><img class="img-responsive" src="http://hoabinh-group.com/public/images/news/460/resize_690x290/vinpearl%20650x-01.png" /></a>
					<div class="time-event">
						<span class="time">04 th.06 </span>
						<span class="circle"></span>
					</div>
					<h3><a href="#">Vinpearl Hạ Long tung khuyến mãi siêu hot dịp hè 2017</a></h3>
					<p>Phú Quốc được mệnh danh là hòn đảo thiên đường của Việt Nam và ngày càng thu hút nhiều du khách tới đây tham quan, nghỉ dưỡng. Hiện tại Vinpeal- hệ thống khách sạn 5 sao đẳng...</p>
					
					<p>
						<span class="col-md-12 panel-extra">
						<span class="col-md-8">
							Do you like it? <i class="fa fa-heart" aria-hidden="true"></i> 139   &nbsp;&nbsp;|&nbsp;&nbsp;  <i class="fa fa-eye" aria-hidden="true"></i> 1678 lượt xem
						</span>
						
						<span class="more col-md-4"><a>XEM CHI TIẾT</a>
						</span>
					</p>
				
					</div>
					
				     
				<div class="panel-footer">&nbsp;</div>
					</div>
			 
		       	    </div>
		      </div><!--.item-new--> 
		    
		      <div class="item-new" data-aos="fade-up" data-aos-duration="2500">
			 		<div class="col-md-1">&nbsp;</div>
		       	    <div class="col-md-11 border-timline">
			       	 <div class="row">
			    <div class="panel-body">
					<a href="#"><img class="img-responsive" src="http://hoabinh-group.com/public/images/news/471/resize_690x290/11giant.jpg" /></a>
					<div class="time-event">
						<span class="time">03 th.06 </span>
						<span class="circle"></span>
					</div>
					<h3><a href="#">Vinpearl Hạ Long tung khuyến mãi siêu hot dịp hè 2017</a></h3>
					<p>Phú Quốc được mệnh danh là hòn đảo thiên đường của Việt Nam và ngày càng thu hút nhiều du khách tới đây tham quan, nghỉ dưỡng. Hiện tại Vinpeal- hệ thống khách sạn 5 sao đẳng...</p>
					
					<p>
						<span class="col-md-12 panel-extra">
						<span class="col-md-8">
							Do you like it? <i class="fa fa-heart" aria-hidden="true"></i> 139   &nbsp;&nbsp;|&nbsp;&nbsp;  <i class="fa fa-eye" aria-hidden="true"></i> 1678 lượt xem
						</span>
						
						<span class="more col-md-4"><a>XEM CHI TIẾT</a>
						</span>
					</p>
					</div>
					
				     
				<div class="panel-footer">
					
					</div>
					</div>
			       	 </div>
			  </div><!--.item-new-->
			  
			  <div class="item-new" data-aos="fade-up" data-aos-duration="2500">
			 		<div class="col-md-1">&nbsp;</div>
		       	    <div class="col-md-11 border-timline">
			       	 <div class="row">
			    <div class="panel-body">
					<a href="#"><img class="img-responsive" src="http://hoabinh-group.com/public/images/news/458/resize_690x290/KDC_6560.JPG" /></a>
					<div class="time-event">
						<span class="time">02 th.06 </span>
						<span class="circle"></span>
					</div>
					<h3><a href="#">Cuộc họp nhóm công tác ASEAN lần thứ 27 về Y học cổ truyền và thực phẩm chức năng</a></h3>
					<p>Công ty Việt Thắng hiện là nhà phân phối độc quyền các sản phẩm xe đạp, xe điện của hãng Giant tại Việt Nam. Tối ngày 8/6 vừa qua, hội nghị tri ân khách hàng của công ty đã...</p>
					
					<p>
						<span class="col-md-12 panel-extra">
						<span class="col-md-8">
							Do you like it? <i class="fa fa-heart" aria-hidden="true"></i> 139   &nbsp;&nbsp;|&nbsp;&nbsp;  <i class="fa fa-eye" aria-hidden="true"></i> 1678 lượt xem
						</span>
						
						<span class="more col-md-4"><a>XEM CHI TIẾT</a>
						</span>
					</p>
					</div>
					
				     
				<div class="panel-footer">
					
					</div>
					</div>
			       	 </div>
			  </div><!--.item-new-->
		     
		     <div class="item-new" data-aos="fade-up" data-aos-duration="2500">
			 		<div class="col-md-1">&nbsp;</div>
		       	    <div class="col-md-11 border-timline">
			       	 <div class="row">
			    <div class="panel-body">
					<a href="#"><img class="img-responsive" src="http://hoabinh-group.com/public/images/news/442/resize_690x290/TOTO7.jpg" /></a>
					<div class="time-event">
						<span class="time">01 th.06 </span>
						<span class="circle"></span>
					</div>
					<h3><a href="#">TOTO long trọng tổ chức đại tiệc mừng lễ kỷ niệm</a></h3>
					<p>Công ty Việt Thắng hiện là nhà phân phối độc quyền các sản phẩm xe đạp, xe điện của hãng Giant tại Việt Nam. Tối ngày 8/6 vừa qua, hội nghị tri ân khách hàng của công ty đã...</p>
					
					<p>
						<span class="col-md-12 panel-extra">
						<span class="col-md-8">
							Do you like it? <i class="fa fa-heart" aria-hidden="true"></i> 139   &nbsp;&nbsp;|&nbsp;&nbsp;  <i class="fa fa-eye" aria-hidden="true"></i> 1678 lượt xem
						</span>
						
						<span class="more col-md-4"><a>XEM CHI TIẾT</a>
						</span>
					</p>
					</div>
					
				     
				<div class="panel-footer">
					
					</div>
					</div>
			       	 </div>
			  </div><!--.item-new-->
		    
		    
		    <nav aria-label="Page navigation" class="pull-right">
  <ul class="pagination">
   <!-- <li class="page-item"><a class="page-link" href="#">Previous</a></li>-->
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Trang sau</a></li>
  </ul>
</nav>
		     <div style="clear:both;"></div>
		    </div>
		   
		    <div class="news-col-right col-md-4">
			    
			    <div class="row">
			     <div class="col-sm-12 col-md-12">
        <form class="form-louis" role="search">
        <div class="input-group">
            <input type="text" class="form-control form-text-louis" placeholder="Search" name="q">
            <div class="input-group-btn">
                <button id="search" class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search big"></i></button>
            </div>
        </div>
        </form>
				</div>
			     </div>
			    <div class="row">
			      <div class="col-sm-12 col-md-12">
			     <div class="panel panel-default">
    <div class="panel-heading">Bài viết có thể bạn quan tâm</div>
    <div class="panel-body">
	    <ul class="list-group">
  <li class="list-group-item louis-list-item">
      <a href="#"><img class="img-responsive" src="http://hoabinhtourist.com/uploads/news/42629-dai-ly-vp.jpg" /></a>
      <p><a href="#">Vinpearl Hạ Long tưng bừng khuyến mãi siêu hot dịp hè 2017</a>
	      <span class="time">03 tháng 06, 2017</span>
      </p>
      
  </li>
 <li class="list-group-item louis-list-item">
      <a href="#"><img class="img-responsive" src="http://hoabinhtourist.com/uploads/news/55247-IMG_5761.JPG" /></a>
      <p><a href="#">Vinpearl Hạ Long tưng bừng khuyến mãi siêu hot dịp hè 2017</a>
	      <span class="time">03 tháng 06, 2017</span>
      </p>
      
  </li>
<li class="list-group-item louis-list-item">
      <a href="#"><img class="img-responsive" src="http://hoabinhtourist.com/uploads/news/60077-29B04166_3.JPG" /></a>
      <p><a href="#">Vinpearl Hạ Long tưng bừng khuyến mãi siêu hot dịp hè 2017</a>
	      <span class="time">03 tháng 06, 2017</span>
      </p>
      
  </li>
  <li class="list-group-item louis-list-item">
      <a href="#"><img class="img-responsive" src="http://hoabinhtourist.com/uploads/news/66568-hoi-nghi-do-luong-chau-a-thai-binh-duong-apmp-lan-thu-32%20(45).JPG" /></a>
      <p><a href="#">Vinpearl Hạ Long tưng bừng khuyến mãi siêu hot dịp hè 2017</a>
	      <span class="time">03 tháng 06, 2017</span>
      </p>
      
  </li>
  <li class="list-group-item louis-list-item">
      <a href="#"><img class="img-responsive" src="http://hoabinhtourist.com/uploads/news/15829-DSC00668.JPG" /></a>
      <p><a href="#">Vinpearl Hạ Long tưng bừng khuyến mãi siêu hot dịp hè 2017</a>
	      <span class="time">03 tháng 06, 2017</span>
      </p>
      
  </li>
  		</ul>
    </div>
   <!-- <div class="panel-footer">Panel Footer</div>-->
				</div>
			      </div>
			     </div>
			     <div class="row">
			       <div class="col-sm-12 col-md-12">
			     <div id="category-news" class="panel panel-default">
    <div class="panel-heading">danh mục bài viết</div>
    <div class="panel-body">
	    <ul class="list-group">
  <li class="list-group-item louis-list-category active">
    <a href="#"> TIN KHUYẾN MÃI</a> 
  </li>
   <li class="list-group-item louis-list-category">
    <a href="#"> GÓC BÁO CHÍ</a> 
   </li>
    <li class="list-group-item louis-list-category">
    <a href="#"> BẢN TIN NỘI BỘ</a> 
    </li>
     <li class="list-group-item louis-list-category">
    <a href="#"> HỘI NGHỊ SỰ KIỆN TIÊU BIỂU</a> 
     </li>
      <li class="list-group-item louis-list-category">
    <a href="#"> TIN TỨC MICE</a> 
      </li>


  		</ul>
    </div>
   <!-- <div class="panel-footer">Panel Footer</div>-->
				</div>
			      </div>
			     </div>
			     <div class="row">
			       <div class="col-sm-12 col-md-12">
			     <div id="category-news" class="panel panel-default">
    <div class="panel-heading">video nổi bật</div>
    <div class="panel-body">
	     <ul class="list-group">
	    <div id="owl-video" class="owl-carousel owl-theme">	
	<div class="item">   
  <li class="list-group-item louis-list-video">
   <span id="playtube" href="#"></span>
	   <img style="width: 100%;" src= "http://timnhanh360.com/hbg/img/demo%20web-11.png"/>
   <p>Hội nghị quốc tế về khoa học vật liêu tiên tiến và công nghệ Nano</p>
      </li>
	</div>

<div class="item">   
  <li class="list-group-item louis-list-video">
   <span id="playtube" href="#"></span>
	   <img style="width: 100%;" src= "http://timnhanh360.com/hbg/img/demo%20web-11.png"/>
   <p>Hội nghị quốc tế về khoa học vật liêu tiên tiến và công nghệ Nano</p>
      </li>
	</div>

  		
	    </div>
	    </ul>
    </div>
   <!-- <div class="panel-footer">Panel Footer</div>-->
				</div>
			      </div>
			     </div>
			     <div class="row">
			       <div class="col-sm-12 col-md-12">
			     <div id="category-tags" class="panel panel-default">
    <div class="panel-heading">Từ khóa</div>
    <div class="panel-body">
	    <ul class="list-group">
  <li class="list-group-item louis-list-tags">
    <a href="#"> Event</a> 
  </li>
   <li class="list-group-item louis-list-tags">
    <a href="#"> VinPearl</a> 
   </li>
    <li class="list-group-item louis-list-tags">
    <a href="#"> Khuyến mãi</a> 
    </li>
     <li class="list-group-item louis-list-tags">
    <a href="#"> MICE</a> 
     </li>
      <li class="list-group-item louis-list-tags">
    <a href="#"> Hội nghị</a> 
      </li>
       <li class="list-group-item louis-list-tags">
    <a href="#"> Sự kiện</a> 
      </li>
        <li class="list-group-item louis-list-tags">
    <a href="#"> Du lịch</a> 
      </li>
      
       <li class="list-group-item louis-list-tags">
    <a href="#"> Mùa hè</a> 
      </li>


  		</ul>
    </div>
   <!-- <div class="panel-footer">Panel Footer</div>-->
				</div>
			      </div>
			      </div>
		    </div>
	    	
	    	</div>
	    </div>