<div class="bg-header-page" style="background-image: url('/public/templates/news2017/default/img/Fotolia_73743476_Subscription_Monthly_M.jpg'); background-position: 0px 0px;">
		   <div class="container"> <div class="row">
			  	 <h1>Bản tin Hòa Bình Group</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="/">Trang chủ</a></li>
  <li class="breadcrumb-item active">Bản tin</li>
</ol> 
		   </div> </div>
	
	    </div>
	 <style>
#category-news{
	margin-top: 20px;
}
#content_temp{
	margin-top: 20px;
}

	 </style>
<div class="container">
			<div class="row">
			<div id="col_list_menu" class="">
				<div id="category-news" class="panel panel-default">
				
					<div class="panel-body">
						<ul class="list-inline">
							<?php foreach($this->result as $key=>$value): ?>
							<li class="list-group-item louis-list-category"> <a data="<?php echo strip_tags($value['description']); ?>" style="cursor: pointer" onClick="viewTemplate(this);" > <?php echo $value['name']; ?> </a> </li>
							<?php endforeach; ?>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-md-8">
				<div id="content_temp" class="embed-responsive">
					
				</div>
			</div>
			
				
				
			</div><!-- .row -->					
	</div><!-- end container -->
			
			<script type="text/javascript">
				
				function viewTemplate(o){
					var value = $(o).attr('data');
					console.log(value);
					$('#content_temp').html('<iframe class="embed-responsive-item" src="'+value+'" height="900" width="700"></iframe>');
					$(o).parent().removeClass('list-inline').addClass('list-group');
					$('#category-news').addClass('col-md-4');
					$('#content_temp').css('height','1000px').addClass('embed-responsive-16by9').css('margin-bottom','20px;');
					$('.louis-list-category').css('width','100%').addClass('text-center').css('margin-bottom','3px');
				}
				
				
			</script>