<script src="/<?=TEMPLATE_PATH?>/default/js/tabs.js" type="text/javascript"></script>
<script type="text/javascript" src="/<?=TEMPLATE_PATH?>/default/js/elevatezoom-min.js"></script>
<section id="columns">

	<div id="breadcrumb"><ol class="breadcrumb container">
		<li class="first"><a href="/"><span>Trang chủ</span></a></li>
		<li><a href="/category/<?php echo $this->link; ?>"><span><?php echo $this->label; ?></span></a></li>
		<li class="last"><a class="last" href="/<?php echo $this->ident; ?>"><span><?=$this->name?></span></a></li>
	</ol></div><div class="container">
<div class="row">
 
 

<section class="col-md-12">  
	<div id="content" class="product-detail">
				
		<div class="product-info">
			<div class="row">			
								<div class="col-lg-5 col-md-5 col-sm-12 col-xs-12 image-container">
					
			
															
					<div class="image-additional slide carousel col-lg-2 col-md-12 " id="image-additional">
						<a class="left carousel-control" href="#image-additional" data-slide="next">
							<i class="fa fa-angle-double-left"></i>
					</a>
						<div id="image-additional-carousel" class="carousel-inner">
								<div class="item clearfix active">
					<?php 
					$i = 0;
					foreach($this->imagesProduct as $kimg=>$vimg):  $i++;
					$urlImg = '/public/images/product/'.$this->productId.'/'.$vimg['full'];
					
					$arrImg[] = $urlImg;
					 ?>			
						<a href="/public/images/product/<?=$this->productId?>/<?=$vimg['full']?>" title="<?=$this->name?>" class="" data-zoom-image="<?=$urlImg?>" data-image="<?=$urlImg?>">
										<img src="<?=$urlImg?>" style="max-width:75px" title="<?=$this->name?>" alt="<?=$this->name?>" data-zoom-image="<?=$urlImg?>" class="product-image-zoom img-responsive">
									</a>
				<?php if($i%4 == 0){  ?>
					
					</div>	<div class="item clearfix">
		<?		} ?>					
								
				<?php endforeach; ?>																						
					</div>
							  															
							  									
						</div>

						<!-- Controls -->
						
						<a class="right carousel-control last" href="#image-additional" data-slide="prev">							
							<i class="fa  fa-angle-double-right"></i>
						</a>

					</div>			
					<script type="text/javascript">
						$('#image-additional .item:first').addClass('active');
						$('#image-additional').carousel({interval:false})
					</script>
					
					<div class="image col-lg-10 col-md-12">
							
						        
							<span class="product-label product-label-special"><span>Sale</span></span>
												<a href="<?=$arrImg[0]?>" class="colorbox cboxElement">
							<img src="<?=$arrImg[0]?>" title="<?=$this->name?>" alt="<?=$this->name?>" id="image" data-zoom-image="<?=$arrImg[0]?>" class="product-image-zoom img-responsive">
							
							
						</a>
						
					
					</div>
							
			
					    
				</div>		
						
	
				<div class="col-lg-7 col-md-7 col-sm-12 col-xs-12 product-view">				
					<h1><?=$this->name?></h1>	

									<!--	<div class="review">
						<div><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-4.png" alt="1 reviews">&nbsp;&nbsp;<a onclick="$('a[href=\'#tab-review\']').trigger('click');">1 reviews</a>&nbsp;&nbsp;|&nbsp;&nbsp;<a onclick="$('a[href=\'#tab-review\']').trigger('click');">Write a review</a></div>
					</div>-->
										<div class="description">
												<p>
							<i class="fa fa-chevron-down"></i>
							<b>Product Code:</b>
							Product <?=$this->id?>						</p>
												<p>
							<i class="fa fa-chevron-down"></i>
							<b>Availability:</b>
							<span>In Stock</span>							
						</p>	
					</div>
							
		 		
										<div class="price">
						<div class="price-gruop">
							<span class="text-price">Price:</span>
														<span class="price-old">$96.00</span> 
							<span class="price-new"><?php echo $this->string()->product_price('VND',$this->price); ?></span>
													</div>	
						<div class="other-price">
															<span class="price-tax">Ex Tax: $9,000.00</span><br>
																				</div>						
											</div>
										


					


					<div class="product-extra">
						<div class="quantity-adder pull-left">
							<div class="quantity-number pull-left">
								<span>Qty:</span>
								<input name="quantity" size="2" value="1" type="text">
							</div>
							<div class="quantity-wrapper pull-left">
								<span class="add-up add-action fa fa-plus"></span> 
								<span class="add-down add-action fa fa-minus"></span>
							</div>					
							<input name="product_id" value="31" type="hidden">	
						</div>											
						<div class="cart pull-left">					
							<!-- <input type="button" value="" id="button-cart" class="button btn btn-theme-default" /> -->
							<button id="button-cart" class="btn btn-shopping-cart">	
								<i class="fa fa-shopping-cart"></i>					
								<span>Add to Cart</span>
							</button> 
						</div>
						<div class="action pull-left">
							<div class="pull-left">
								<a class="product-icon fa fa-heart product-icon" onclick="addToWishList('31');">
								</a>				
							</div>
							<div class="pull-left">
								<a class="product-icon fa fa-refresh" onclick="addToCompare('31');">							
								</a>
							</div>
						</div>
					</div>
					<div class="share clearfix"><!-- AddThis Button BEGIN -->
			         
	
					
		
			  
		</div>
	</div>
</div>

  
<div class="tabs-group box">
	<div id="tabs" class="htabs heighlight">
		<ul class="nav clearfix">
			<li class="first"><a class="selected" href="#tab-description">Description</a></li>			
        			<li><a href="#tab-review">Reviews (1)</a></li>
        			<li class="last"><a href="#tab-customtab">Custom Tab</a></li>
    
		</ul>			
  </div>
  <div style="display: block;" id="tab-description" class="tab-content"><div class="cpt_product_description ">
<div><?php echo $this->description; ?></div>
</div>
<!-- cpt_container_end --></div>
     <!-- <div style="display: none;" id="tab-review" class="tab-content">
    <div id="review"><div class="review-list">
	<div class="author"><b>ThemeLexus</b>  on  19/12/2013</div>
	<div class="rating"><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-4.png" alt="1 reviews"></div>
	<div class="text">Animi, iusto, similique, possimus, optio dolorum 
eligendi laudantium mollitia sit fugiat quia quae adipisci atque placeat
 totam natus soluta ab quos eius sed quaerat delectus voluptatum eveniet
 voluptates quo a debitis</div>
</div>
<div class="pagination paging clearfix"><div class="results">Showing 1 to 1 of 1 (1 Pages)</div></div>
</div>
    <h2 id="review-title">Write a review</h2>
    <div class="form-review">
    <div class="option"><label>Your Name:</label>
    <input class="form-control" name="name" type="text">
    </div>
    <div class="option">
    <label>Your Review:</label>
    <textarea class="form-control" name="text" cols="40" rows="8"></textarea>
    <span style="font-size: 11px;"><span style="color: #FF0000;">Note:</span> HTML is not translated!</span><br>
    </div>

    <div class="option">
    <label>Rating:</label> <span>Bad</span>&nbsp;
    <input name="rating" value="1" type="radio">
    &nbsp;
    <input name="rating" value="2" type="radio">
    &nbsp;
    <input name="rating" value="3" type="radio">
    &nbsp;
    <input name="rating" value="4" type="radio">
    &nbsp;
    <input name="rating" value="5" type="radio">
    &nbsp;<span>Good</span><br>
    </div>
    <div class=" option form-inline">
    <label>Enter the code in the box below:</label> 
	  <span class="form-group"><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/index.jpg" alt="" id="captcha"></span>
    <span class="form-group"><input class="form-control" name="captcha" type="text"></span>
    </div>
      <div><a id="button-review" class="btn btn-theme-default">Continue</a></div>
  </div>
    </div>-->
         <div style="display: none;" id="tab-customtab" class="tab-content custom-tab">
      <div class="inner">
        <p>Sapiente rerum magni voluptates accusantium sequi molestias 
deleniti aliquid facilis commodi aut. Ea ab facere voluptatem cum beatae
 vero dolorem doloribus itaque culpa. Molestiae, optio, libero inventore
 ducimus natus incidunt qui dolor adipisci tempore tempora quo minima 
distinctio eligendi laborum ex quaerat eos! Unde suscipit porro est amet
 quis nostrum enim. Asperiores, ad, hic, culpa, rerum delectus similique
 minus facilis reprehenderit quisquam debitis dolores suscipit!</p>

<p>Qui laboriosam maiores ad. Enim, autem, beatae, sapiente minima non 
atque maiores maxime natus corporis possimus reprehenderit id blanditiis
 sequi repudiandae saepe reiciendis consequatur mollitia aspernatur cum!</p>
      </div></div>
    
  </div>
		
<div class="box product-related clearfix">	
	<div class="box-heading heighlight"><span>Related Products (8)</span></div>
	<div id="related" class="slide row-fuild" data-interval="0">
		 
	    <div class="carousel-controls">
	      <a class="carousel-control left fa fa-angle-left" href="#related" data-slide="prev"></a>
	      <a class="carousel-control right fa fa-angle-right" href="#related" data-slide="next"></a>
	    </div>
	    	<div class="box-content carousel-inner">
			
						  								<div class="item active">
																													  <div class=" box-product">
																					  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 product-cols first">
											  	<div class="product-block">	
																									<div class="image">
																				<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=33"><img class="img-responsive" src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/product_06-500x554.jpg" alt="Canon EOS 40D 10.1MP SLR Camera"></a>
														<!-- zoom image-->
																					<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_06.jpg" id="colorbox_33" class="product-zoom related-colorbox cboxElement" title="Canon EOS 40D 10.1MP SLR Camera"><i class="fa fa-search-plus"></i></a>
														

														<!-- Show Swap -->
																												<!-- Show Swap -->


																																													<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=33"><em class="fa fa-eye"></em><span>Quick View</span></a>
																													
					</div>
										<div class="product-meta">
						<div class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=33">Canon EOS 40D 10.1MP SLR Camera</a></div>
																		<div class="price">
						  						  $237.00						  						</div>
																	    <div class="rating"><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-5.png" alt="5"></div>
					    						<div class="action">
							<div class="cart">
								        						
																<button onclick="addToCart('33');" class="btn btn-shopping-cart">
																	<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
																</button>
								      						</div>
															
															<div class="button-group">
																<div class="wishlist">
																	<a onclick="addToWishList('33');" title="Add to Wish List" class="fa fa-heart product-icon">
																		<span>Add to Wish List</span>
																	</a>	
																</div>
																<div class="compare">			
																	<a onclick="addToCompare('33');" title="Add to Compare" class="fa fa-refresh product-icon">
																		<span>Add to Compare</span>
																	</a>	
																</div>
															</div>							
														</div>		 
													</div>	 
												</div>		 
											</div>
										
									  
									  																														  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 product-cols">
											  	<div class="product-block">	
																									<div class="image">
																												<span class="product-label product-label-special"><span>Sale</span></span>
																				<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=36"><img class="img-responsive" src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/product_09-500x554.jpg" alt="Body lotions Nineties revival"></a>
														<!-- zoom image-->
																					<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_09.jpg" id="colorbox_36" class="product-zoom related-colorbox cboxElement" title="Body lotions Nineties revival"><i class="fa fa-search-plus"></i></a>
														

														<!-- Show Swap -->
																												<!-- Show Swap -->


																																													<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=36"><em class="fa fa-eye"></em><span>Quick View</span></a>
																													
					</div>
										<div class="product-meta">
						<div class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=36">Body lotions Nineties revival</a></div>
																		<div class="price">
						  						  <span class="price-old">$119.50</span> 
						  <span class="price-new">$107.75</span>
						  						</div>
																	    <div class="rating"><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-4.png" alt="4"></div>
					    						<div class="action">
							<div class="cart">
								        						
																<button onclick="addToCart('36');" class="btn btn-shopping-cart">
																	<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
																</button>
								      						</div>
															
															<div class="button-group">
																<div class="wishlist">
																	<a onclick="addToWishList('36');" title="Add to Wish List" class="fa fa-heart product-icon">
																		<span>Add to Wish List</span>
																	</a>	
																</div>
																<div class="compare">			
																	<a onclick="addToCompare('36');" title="Add to Compare" class="fa fa-refresh product-icon">
																		<span>Add to Compare</span>
																	</a>	
																</div>
															</div>							
														</div>		 
													</div>	 
												</div>		 
											</div>
										
									  
									  																														  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 product-cols">
											  	<div class="product-block">	
																									<div class="image">
																												<span class="product-label product-label-special"><span>Sale</span></span>
																				<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=42"><img class="img-responsive" src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/product_15-500x554.jpg" alt="Vans Authentic Shoes"></a>
														<!-- zoom image-->
																					<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_15.jpg" id="colorbox_42" class="product-zoom related-colorbox cboxElement" title="Vans Authentic Shoes"><i class="fa fa-search-plus"></i></a>
														

														<!-- Show Swap -->
																												<!-- Show Swap -->


																																													<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=42"><em class="fa fa-eye"></em><span>Quick View</span></a>
																													
					</div>
										<div class="product-meta">
						<div class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=42">Vans Authentic Shoes</a></div>
																		<div class="price">
						  						  <span class="price-old">$119.50</span> 
						  <span class="price-new">$107.75</span>
						  						</div>
																	    <div class="rating"><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-5.png" alt="5"></div>
					    						<div class="action">
							<div class="cart">
								        						
																<button onclick="addToCart('42');" class="btn btn-shopping-cart">
																	<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
																</button>
								      						</div>
															
															<div class="button-group">
																<div class="wishlist">
																	<a onclick="addToWishList('42');" title="Add to Wish List" class="fa fa-heart product-icon">
																		<span>Add to Wish List</span>
																	</a>	
																</div>
																<div class="compare">			
																	<a onclick="addToCompare('42');" title="Add to Compare" class="fa fa-refresh product-icon">
																		<span>Add to Compare</span>
																	</a>	
																</div>
															</div>							
														</div>		 
													</div>	 
												</div>		 
											</div>
										
									  
									  																														  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 product-cols last">
											  	<div class="product-block">	
																									<div class="image">
																				<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=43"><img class="img-responsive" src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/product_16-500x554.jpg" alt="Red shoes"></a>
														<!-- zoom image-->
																					<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_16.jpg" id="colorbox_43" class="product-zoom related-colorbox cboxElement" title="Red shoes"><i class="fa fa-search-plus"></i></a>
														

														<!-- Show Swap -->
																												<!-- Show Swap -->


																																													<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=43"><em class="fa fa-eye"></em><span>Quick View</span></a>
																													
					</div>
										<div class="product-meta">
						<div class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=43">Red shoes</a></div>
																		<div class="price">
						  						  $589.50						  						</div>
																	    <div class="rating"><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-3.png" alt="3"></div>
					    						<div class="action">
							<div class="cart">
								        						
																<button onclick="addToCart('43');" class="btn btn-shopping-cart">
																	<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
																</button>
								      						</div>
															
															<div class="button-group">
																<div class="wishlist">
																	<a onclick="addToWishList('43');" title="Add to Wish List" class="fa fa-heart product-icon">
																		<span>Add to Wish List</span>
																	</a>	
																</div>
																<div class="compare">			
																	<a onclick="addToCompare('43');" title="Add to Compare" class="fa fa-refresh product-icon">
																		<span>Add to Compare</span>
																	</a>	
																</div>
															</div>							
														</div>		 
													</div>	 
												</div>		 
											</div>
										
									  
									  										 </div>
																											</div>
						  								<div class="item ">
																													  <div class=" box-product">
																					  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 product-cols first">
											  	<div class="product-block">	
																									<div class="image">
																												<span class="product-label product-label-special"><span>Sale</span></span>
																				<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=48"><img class="img-responsive" src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/product_20-500x554.jpg" alt="Duffle Bag  revival reigns supreme"></a>
														<!-- zoom image-->
																					<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_20.jpg" id="colorbox_48" class="product-zoom related-colorbox cboxElement" title="Duffle Bag  revival reigns supreme"><i class="fa fa-search-plus"></i></a>
														

														<!-- Show Swap -->
																												<!-- Show Swap -->


																																													<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=48"><em class="fa fa-eye"></em><span>Quick View</span></a>
																													
					</div>
										<div class="product-meta">
						<div class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=48">Duffle Bag  revival reigns supreme</a></div>
																		<div class="price">
						  						  <span class="price-old">$589.50</span> 
						  <span class="price-new">$107.75</span>
						  						</div>
																	    <div class="rating"><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-4.png" alt="4"></div>
					    						<div class="action">
							<div class="cart">
								        						
																<button onclick="addToCart('48');" class="btn btn-shopping-cart">
																	<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
																</button>
								      						</div>
															
															<div class="button-group">
																<div class="wishlist">
																	<a onclick="addToWishList('48');" title="Add to Wish List" class="fa fa-heart product-icon">
																		<span>Add to Wish List</span>
																	</a>	
																</div>
																<div class="compare">			
																	<a onclick="addToCompare('48');" title="Add to Compare" class="fa fa-refresh product-icon">
																		<span>Add to Compare</span>
																	</a>	
																</div>
															</div>							
														</div>		 
													</div>	 
												</div>		 
											</div>
										
									  
									  																														  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 product-cols">
											  	<div class="product-block">	
																									<div class="image">
																				<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=51"><img class="img-responsive" src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/product_21-500x554.jpg" alt="aculis suscipit sollicitudin dignissim nunc "></a>
														<!-- zoom image-->
																					<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_21.jpg" id="colorbox_51" class="product-zoom related-colorbox cboxElement" title="aculis suscipit sollicitudin dignissim nunc "><i class="fa fa-search-plus"></i></a>
														

														<!-- Show Swap -->
																												<!-- Show Swap -->


																																													<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=51"><em class="fa fa-eye"></em><span>Quick View</span></a>
																													
					</div>
										<div class="product-meta">
						<div class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=51">aculis suscipit sollicitudin dignissim nunc </a></div>
																		<div class="price">
						  						  $67.00						  						</div>
																	    <div class="rating"><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-5.png" alt="5"></div>
					    						<div class="action">
							<div class="cart">
								        						
																<button onclick="addToCart('51');" class="btn btn-shopping-cart">
																	<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
																</button>
								      						</div>
															
															<div class="button-group">
																<div class="wishlist">
																	<a onclick="addToWishList('51');" title="Add to Wish List" class="fa fa-heart product-icon">
																		<span>Add to Wish List</span>
																	</a>	
																</div>
																<div class="compare">			
																	<a onclick="addToCompare('51');" title="Add to Compare" class="fa fa-refresh product-icon">
																		<span>Add to Compare</span>
																	</a>	
																</div>
															</div>							
														</div>		 
													</div>	 
												</div>		 
											</div>
										
									  
									  																														  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 product-cols">
											  	<div class="product-block">	
																									<div class="image">
																												<span class="product-label product-label-special"><span>Sale</span></span>
																				<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=56"><img class="img-responsive" src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/product_22-500x554.jpg" alt="Raymond Weil Women's"></a>
														<!-- zoom image-->
																					<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_22.jpg" id="colorbox_56" class="product-zoom related-colorbox cboxElement" title="Raymond Weil Women's"><i class="fa fa-search-plus"></i></a>
														

														<!-- Show Swap -->
																												<!-- Show Swap -->


																																													<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=56"><em class="fa fa-eye"></em><span>Quick View</span></a>
																													
					</div>
										<div class="product-meta">
						<div class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=56">Raymond Weil Women's</a></div>
																		<div class="price">
						  						  <span class="price-old">$119.50</span> 
						  <span class="price-new">$107.75</span>
						  						</div>
																        <div class="norating"><img alt="0" src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-0.png"></div>
				        						<div class="action">
							<div class="cart">
								        						
																<button onclick="addToCart('56');" class="btn btn-shopping-cart">
																	<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
																</button>
								      						</div>
															
															<div class="button-group">
																<div class="wishlist">
																	<a onclick="addToWishList('56');" title="Add to Wish List" class="fa fa-heart product-icon">
																		<span>Add to Wish List</span>
																	</a>	
																</div>
																<div class="compare">			
																	<a onclick="addToCompare('56');" title="Add to Compare" class="fa fa-refresh product-icon">
																		<span>Add to Compare</span>
																	</a>	
																</div>
															</div>							
														</div>		 
													</div>	 
												</div>		 
											</div>
										
									  
									  																														  <div class="col-lg-3 col-md-3 col-sm-3 col-xs-12 product-cols last">
											  	<div class="product-block">	
																									<div class="image">
																												<span class="product-label product-label-special"><span>Sale</span></span>
																				<a class="img" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=59"><img class="img-responsive" src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/product_25-500x554.jpg" alt="Citizen Women's EW and Men's EW"></a>
														<!-- zoom image-->
																					<a href="http://demopavothemes.com/pav_styleshop/d/image/data/demo/product_25.jpg" id="colorbox_59" class="product-zoom related-colorbox cboxElement" title="Citizen Women's EW and Men's EW"><i class="fa fa-search-plus"></i></a>
														

														<!-- Show Swap -->
																												<!-- Show Swap -->


																																													<a class="pav-colorbox btn btn-theme-default cboxElement" href="http://demopavothemes.com/pav_styleshop/d/index.php?route=themecontrol/product&amp;product_id=59"><em class="fa fa-eye"></em><span>Quick View</span></a>
																													
					</div>
										<div class="product-meta">
						<div class="name"><a href="http://demopavothemes.com/pav_styleshop/d/index.php?route=product/product&amp;product_id=59">Citizen Women's EW and Men's EW</a></div>
																		<div class="price">
						  						  <span class="price-old">$119.50</span> 
						  <span class="price-new">$107.75</span>
						  						</div>
																	    <div class="rating"><img src="Canon%20EOS%2040D%2010.1MP%20SLR%20Camera_files/stars-5.png" alt="5"></div>
					    						<div class="action">
							<div class="cart">
								        						
																<button onclick="addToCart('59');" class="btn btn-shopping-cart">
																	<i class="fa fa-shopping-cart"></i><span>Add to Cart</span>
																</button>
								      						</div>
															
															<div class="button-group">
																<div class="wishlist">
																	<a onclick="addToWishList('59');" title="Add to Wish List" class="fa fa-heart product-icon">
																		<span>Add to Wish List</span>
																	</a>	
																</div>
																<div class="compare">			
																	<a onclick="addToCompare('59');" title="Add to Compare" class="fa fa-refresh product-icon">
																		<span>Add to Compare</span>
																	</a>	
																</div>
															</div>							
														</div>		 
													</div>	 
												</div>		 
											</div>
										
									  
									  										 </div>
																											</div>
						  		  
	</div>
</div>
</div>	
	
	</div>

<script type="text/javascript">
			
		$("#image").elevateZoom( {  gallery:'image-additional-carousel', 
									cursor: 'pointer', 
								 										galleryActiveClass: 'active' } ); 
		 
</script>

<script type="text/javascript">
<!--
$(document).ready(function() {
  $('.colorbox').colorbox({
    overlayClose: true,
    opacity: 0.5,
    rel: "colorbox"
  });
});
//-->
</script> 

 <script type="text/javascript">
 <!--
$('select[name="profile_id"], input[name="quantity"]').change(function(){
    $.ajax({
    url: 'index.php?route=product/product/getRecurringDescription',
    type: 'post',
    data: $('input[name="product_id"], input[name="quantity"], select[name="profile_id"]'),
    dataType: 'json',
        beforeSend: function() {
            $('#profile-description').html('');
        },
    success: function(json) {
      $('.success, .warning, .attention, information, .error').remove();
            
      if (json['success']) {
                $('#profile-description').html(json['success']);
      } 
    }
  });
});
    
$('#button-cart').bind('click', function() {
  $.ajax({
    url: 'index.php?route=checkout/cart/add',
    type: 'post',
    data: $('.product-info input[type=\'text\'], .product-info input[type=\'hidden\'], .product-info input[type=\'radio\']:checked, .product-info input[type=\'checkbox\']:checked, .product-info select, .product-info textarea'),
    dataType: 'json',
    success: function(json) {
      $('.success, .warning, .attention, information, .error').remove();
      
      if (json['error']) {
        if (json['error']['option']) {
          for (i in json['error']['option']) {
            $('#option-' + i).after('<span class="error">' + json['error']['option'][i] + '</span>');
          }
        }
                
                if (json['error']['profile']) {
                    $('select[name="profile_id"]').after('<span class="error">' + json['error']['profile'] + '</span>');
                }
      } 
     
      if (json['success']) {
        $('#notification').html('<div class="success" style="display: none;">' + json['success'] + '<img src="catalog/view/theme/pav_styleshop/image/close.png" alt="" class="close" /></div>');
          
        $('.success').fadeIn('slow');
        
        $('#cart-total').html(json['total']);

        $('#cart #cart-total').html(json['total']);
        
        $('html, body').animate({ scrollTop: 0 }, 'slow'); 
      } 
    }
  });
});
//-->
</script>


<script type="text/javascript">
<!--
$('#review .pagination a').live('click', function() {
  $('#review').fadeOut('slow');
    
  $('#review').load(this.href);
  
  $('#review').fadeIn('slow');
  
  return false;
});     

$('#review').load('index.php?route=product/product/review&product_id=31');

$('#button-review').bind('click', function() {
  $.ajax({
    url: 'index.php?route=product/product/write&product_id=31',
    type: 'post',
    dataType: 'json',
    data: 'name=' + encodeURIComponent($('input[name=\'name\']').val()) + '&text=' + encodeURIComponent($('textarea[name=\'text\']').val()) + '&rating=' + encodeURIComponent($('input[name=\'rating\']:checked').val() ? $('input[name=\'rating\']:checked').val() : '') + '&captcha=' + encodeURIComponent($('input[name=\'captcha\']').val()),
    beforeSend: function() {
      $('.success, .warning').remove();
      $('#button-review').attr('disabled', true);
      $('#review-title').after('<div class="attention"><img src="catalog/view/theme/pav_styleshop/image/loading.gif" alt="" /> Please Wait!</div>');
    },
    complete: function() {
      $('#button-review').attr('disabled', false);
      $('.attention').remove();
    },
    success: function(data) {
      if (data['error']) {
        $('#review-title').after('<div class="warning">' + data['error'] + '</div>');
      }
      
      if (data['success']) {
        $('#review-title').after('<div class="success">' + data['success'] + '</div>');
                
        $('input[name=\'name\']').val('');
        $('textarea[name=\'text\']').val('');
        $('input[name=\'rating\']:checked').attr('checked', '');
        $('input[name=\'captcha\']').val('');
      }
    }
  });
});
//-->
</script> 

<script type="text/javascript">
<!--
$('#tabs a').tabs();
//-->
</script> 
 
</section>
 

</div></div>

</section>