	<div class="row">
		

									<div class="col-xs-12">
                                        <h3 class="header smaller lighter blue"><a href="javascript:void(0);">Quản lý sự kiện</a> » <a href="/admin/emailtemplate/">Thiết lập mẫu thư mời sự kiện</a></h3>

										<div class="table-responsive">
											<table id="table_events" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														
														<th style="text-align: center;vertical-align: middle;width: 3%;">STT</th>
														<th style="text-align: center;vertical-align: middle;">Tiêu đề</th>
                                                        <th style="text-align: center;vertical-align: middle;width: 5%;">Ngày tạo</th>
														<th style="text-align: center;vertical-align: middle;width: 5%;">Thao tác</th>
													</tr>
												</thead>

												<tbody>
				<?php echo $this->partialLoop('_emailtemp-row.phtml', $this->products); ?>

												</tbody>
											</table>
											
										</div>
                                        <div style="margin-top: 10px;" class="row">
                                            <div class="col-md-8 col-sm-8 col-xs-12">
                                            </div>
                                            <div style="text-align: right;" class="col-md-4 col-sm-4 col-xs-12">
                                                <a class="btn btn-info btn-sm" href="/admin/emailtemplate/create">Thêm mới</a>
                                            </div>
                                        </div>

										
									</div>
								</div>
	<br/>
	
	
						
<script type="text/javascript">
			jQuery(function($) {
				var oTable1 = $('#table_events').dataTable( {
				"aoColumns": [
			      { "bSortable": false },
			      null, null
				] } );
				
				
			})
		</script>									
