<div class="tabbable">
	<ul class="nav nav-tabs" id="myTab">
				<li class="active">
					<a data-toggle="tab" href="#home">
						<i class="green ace-icon fa fa-home bigger-120"></i>
							Cập nhật timeline
					</a>
				</li>

				<li>
					<a data-toggle="tab" href="#seo">
						<i class="blue ace-icon fa fa-search bigger-120"></i>
						SEO
						<span class="badge badge-danger"></span>
					</a>
				</li>
				
				<li>
					<a data-toggle="tab" href="#history">
						<i class="orange ace-icon fa fa-history bigger-120"></i>
						Lịch sử
						<span class="badge badge-danger"></span>
					</a>
				</li>
	</ul>

	<div class="tab-content">
				<div id="home" class="tab-pane fade in active">
			<?php echo $this->form; ?>
			<!--
			<div class="col-xs-3">
													<label>Hiển thị</label>
														<input name="switch-field-1" class="ace ace-switch" type="checkbox" />
														<span class="lbl"></span>
													
												</div>
												-->
 <?php echo $this->Ckeditor('description',350,600); ?>
 				<div style="clear:both"></div>
				</div>
			

				<div id="seo" class="tab-pane fade">
		<form id="seo-form" method="post" action="/admin/recruitment/seo">		 									
		<dl class="zend_form">
			<input id="id" type="hidden" value="<?=$this->id?>" name="id">
<dt id="seo_title-label">
         
	<label class="required" for="title">Title:</label>
</dt>

<dd id="seo_title-element">
<input id="seo_title" type="text" size="40" value="<?=$this->title?>" name="seo_title">
<p>Giới hạn <span id= "counter_seo_title"></span> kí tự</p>
</dd>


<dt id="seo_keyword-label">
	<label class="required" for="title">Keyword:</label>
</dt>

<dd id="seo_keyword-element">
<input id="seo_keyword" type="text" size="74" value="<?=$this->keyword?>" name="seo_keyword">
</dd>

<dt id="seo_description-label">
	<label class="required" for="title">Description:</label>
</dt>

<dd id="seo_description-element">
<textarea id="seo_description" name="seo_description" rows="5" cols="40"><?=$this->description?></textarea>
<p>Giới hạn <span id= "counter_seo_description"></span> kí tự</p>
</dd>


<dt id="submit-label"> </dt>
<dd id="submit-element">
<input id="submit-seo" class="btn btn-info" type="submit" value="Save" name="submit-seo">
</dd>
		</dl>
		</form>
				</div>

				<div id="history" class="tab-pane fade">
					<div class="table-responsive">
											<table id="table_history" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														<th class="center">
															<label>
																<input type="checkbox" class="ace" />
																<span class="lbl"></span>
															</label>
														</th>
														
														<th>Thời gian</th>
														<th>Người sửa</th>
														<th>Nội dung từ</th>
														<th>Chuyển thành</th>
													
													</tr>
												</thead>

												<tbody>
				<?php echo $this->partialLoop('_history-row.phtml', $this->activities); ?>																						

												</tbody>
											</table>
										</div>
				</div>
											
	</div>
</div>

		
	