  <div class="bg-header-page"  style="background-image: url('<?=TEMPLATE_URL?>/default/img/south-head-sydney.jpg'); background-position: 0px -271px; background-attachment: fixed;">
		    <div class="container">
			     <div class="row">
			   	 <h1>Đội ngũ lãnh đạo</h1>
<ol class="breadcrumb">
  <li class="breadcrumb-item"><a href="#">Home</a></li>
  <li class="breadcrumb-item"><a href="#">Giới thiệu</a></li>
  <li class="breadcrumb-item active">Đội ngũ lãnh đạo</li>
</ol> 
			    
		    </div>
		    	 </div>
	
	    </div>
	    <div class="container">
	    <div id = "news-content">
	    <div class="review-content">
		    <div class="title-louis center">ĐỘI NGŨ LÃNH ĐẠO</div>
		    <div class="underline"></div>
		   <div class="des-louis center">Những "hoa tiêu" tiên phong làm nên thương hiệu Hòa Bình Group</div> 
		  <div class="container"> <div class="row">
		   
		   <div class="big-ava-bg col-md-4 openSlickModal-1 manualLabel">  <a href="#"> <img class="big-ld img-responsive" src="http://timnhanh360.com/hbg/img/leadership-avatar-m.jpg" /></a>
			 <span class="name"> Lê Đại Tâm</span>
			 <div class="title-job">Tổng Giám đốc</div></div>
		   <div class="big-ava-bg col-md-4">
			  <a href="#"> <img class="big-ld img-responsive" src="http://hoabinh-group.com/public/images/backgrounds/103A0546-1.jpg" /></a>
			 <span class="name"> Phạm Hoàng Lan</span>
			 <div class="title-job"> Giám đốc</div>
		   </div>
		   <div class="big-ava-bg col-md-4">
			    <a href="#"> <img class="big-ld img-responsive" src="http://hoabinh-group.com/public/images/backgrounds/103A0540.jpg" /></a>
			 <span class="name"> Jackie Hân</span>
			 <div class="title-job"> Phó Giám đốc</div>
		   </div>
		   
		   
		   </div> 
		   </div>
			
		
		
		   
		   <div class="container" style="margin-top: 20px;">
			   <div class="row">
			   <div class="medium-ava-bg col-md-3">
				     <a href="#"> <img class="med-ld img-responsive" src="http://hoabinhtourist.com/uploads/86451-103A0341.jpg" /></a>
			 <span class="name"> Ms. Hậu</span>
			 <div class="title-job"> Sales</div>
			   </div>
			   <div class="medium-ava-bg col-md-3">
				    <a href="#"> <img class="med-ld img-responsive" src="http://hoabinhtourist.com/uploads/gallery/89310-103A0644.jpg" /></a>
			 <span class="name"> Ms. Thu</span>
			 <div class="title-job"> Trưởng phòng Tour</div>
			   </div>
			   <div class="medium-ava-bg col-md-3">
				    <a href="#"> <img class="med-ld img-responsive" src="http://hoabinhtourist.com/uploads/30291-103A0672.jpg" /></a>
			 <span class="name"> Ms. Trầm</span>
			 <div class="title-job"> Trưởng phòng Xe</div>
			   </div>
			   <div class="medium-ava-bg col-md-3">
				    <a href="#"> <img class="med-ld img-responsive" src="http://hoabinhtourist.com/uploads/58898-103A0641.jpg" /></a>
			 <span class="name"> Mr. Tuấn</span>
			 <div class="title-job"> Phó phòng truyền thông</div>
			   </div>
		   	</div>
		  </div>
		    <div class="container" style="margin-top: 20px;">
			    <div class="row">
			   <div class="medium-ava-bg col-md-3">
				     <a href="#"> <img class="med-ld img-responsive" src="http://hoabinhtourist.com/uploads/gallery/9315-103A0314.jpg" /></a>
			 <span class="name"> Mr. Bắc</span>
			 <div class="title-job"> Phó phòng Take Care</div>
			   </div>
			   <div class="medium-ava-bg col-md-3">
				    <a href="#"> <img class="med-ld img-responsive" src="http://hoabinhtourist.com/uploads/gallery/7709-103A0318.jpg" /></a>
			 <span class="name"> Ms. Hương</span>
			 <div class="title-job"> Phó phòng Take Care</div>
			   </div>
			   <div class="medium-ava-bg col-md-3">
				    <a href="#"> <img class="med-ld img-responsive" src="http://hoabinh-group.com/public/images/backgrounds/103A0663.jpg" /></a>
			 <span class="name"> Ms. Dung</span>
			 <div class="title-job"> Trưởng phòng vé</div>
			   </div>
			   <div class="medium-ava-bg col-md-3"></div>
			   </div>
		   </div>
	    </div>	
	    
	     
	    <div class="col-md-10 col-md-offset-1 hidden-xs" style="margin-top: 20px;">
		    <div class="col-md-10 col-md-offset-1">
	    	  <ul id='review_tab' class="nav nav-tabs" role="tablist">
                                        <li role="presentation"><a href="/ve-chung-toi">Về chúng tôi</a></li>
                                        <li role="presentation"><a href="/tam-nhin-su-menh">Giá trị cốt lõi</a></li>
                                        <li role="presentation"><a href="/nang-luc-tai-chinh" >Năng lực tài chính</a></li>
                                        <li role="presentation"><a href="/dau-an-phat-trien">Những dấu ấn của sự phát triển</a></li>
                                          <li role="presentation" class="active"><a href="/doi-ngu-lanh-dao">Đội ngũ lãnh đạo</a></li>
                                    </ul>
                                    
                                    </div>
	    	</div>
	      
	    	
	    	</div>
	    </div>	
	    
	    
	    