<h3>Chỉnh sửa giao diện</h3>
<p>
	<ul>
		<li><a href="app=mangaview=themes_editor&file=customJsCSS">Custom js & css</a></li>
	</ul>
</p>
<p><blockquote></p>


<div class="bs-docs-grid row show-grid col-lg-6 col-md-6">
<h3>Trang chủ</h3>
<hr>
      <div class="row show-grid col-lg-12 col-md-12">
        <a href="app=mangaview=themes_editor&file=navbar">
        	<div class="col-xs-12 col-md-12 well" style="text-align: center">Nav bar</div>
        </a>
        <a href="app=mangaview=themes_editor&file=cover">
        	<div class="col-xs-12 col-md-12 well" style="text-align: center">Cover/Banner<br /><br /></div>
        </a>
      </div>
      <div class="row show-grid col-lg-12 col-md-12">
        <a href="/admin/editor/layout/?template=homecontent">
        	<div class="col-xs-8 col-md-8 well">Main Content<br /><br /><br /><br /><br /></div>
        <a/>
        <a href="app=mangaview=themes_editor&file=home-sidebar">
        	<div class="col-xs-3 col-md-3 col-xs-offset-1 col-md-offset-1 well">Sidebar<br /><br /><br /><br /><br /></div>
      	</a>
      </div>
      <div class="row show-grid col-lg-12 col-md-12">
        <a href="app=mangaview=themes_editor&file=footer">
        	<div class="col-xs-12 col-md-12 well" style="text-align: center">Footer</div>
    	</a>
      </div>
    </div>


<div class="bs-docs-grid row show-grid col-lg-6 col-md-6">
<h3>Trang hội nghị, sự kiện</h3>
<hr>
      <div class="row show-grid col-lg-12 col-md-12">
        <a href="app=mangaview=themes_editor&file=navbar">
        	<div class="col-xs-12 col-md-12 well" style="text-align: center">Header</div>
        </a>
      </div>
      <div class="row show-grid col-lg-12 col-md-12">
	     <a href="/admin/editor/layout/sidebar">
        	<div class="col-xs-3 col-md-3 well">Sidebar<br /><br /><br /><br /><br /></div>
      	</a>
        <a href="app=mangaview=themes_editor&file=manga-content">
        	<div class="col-xs-8 col-md-8 col-xs-offset-1 col-md-offset-1 well">Main Content<br /><br /><br /><br /><br /></div>
        <a/>
      
      </div>
      <div class="row show-grid col-lg-12 col-md-12">
        <a href="app=mangaview=themes_editor&file=footer">
        	<div class="col-xs-12 col-md-12 well" style="text-align: center">Footer</div>
    	</a>
      </div>
    </div>




<div class="bs-docs-grid row show-grid col-lg-6 col-md-6">
<h3>Chỉnh sửa widgets</h3>
<hr>
<ul>
	<li><a href="/admin/editor/layout/?template=topmenu">Chỉnh sửa Top menu</a></li>
</ul>
	<?php
		/*
		$widgets = scandir(ROOT_DIR.'/app/manga/themes/default/widgets');
		foreach($widgets as $widget){ // iterate files
			if($widget != '.' && $widget != '..'){
				echo "<a href='app=mangaview=themes_editor&file=all&thisFile=$widget'>$widget<a/><br />";
			}
		}
		*/
	?>
</div>