<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8" />
		<title>404 Error Page</title>

		<meta name="description" content="404 Error Page" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />

		<!-- basic styles -->

		<link href="/<?=SHARE?>/assets/css/bootstrap.min.css" rel="stylesheet" />
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/font-awesome.min.css" />

		<!--[if IE 7]>
		  <link rel="stylesheet" href="assets/css/font-awesome-ie7.min.css" />
		<![endif]-->


		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace-fonts.css" />


		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace.min.css" />
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace-rtl.min.css" />
		<link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace-skins.min.css" />

		<!--[if lte IE 8]>
		  <link rel="stylesheet" href="/<?=SHARE?>/assets/css/ace-ie.min.css" />
		<![endif]-->

		<script src="/<?=SHARE?>/assets/js/ace-extra.min.js"></script>

		<!--[if lt IE 9]>
		<script src="/<?=SHARE?>/assets/js/html5shiv.js"></script>
		<script src="/<?=SHARE?>/assets/js/respond.min.js"></script>
		<![endif]-->
	</head>

	<body>
	

		<div class="main-container" id="main-container">
			<?= $this->layout()->content ?>
		</div><!-- /.main-container -->

	
	</body>
</html>
