<!DOCTYPE html>
<html lang="vi" dir="ltr">
<head>
<title></title>
</head>
<body>
	<h3>Liên hệ từ Tập đoàn Hòa Bình Group</h3>

<p>Tên khách hàng: <?=$this->name?></p> 
<p>Email: <?=$this->email?></p> 
<p>Điện thoại: <?=$this->phone?></p> 
<p>Công ty: <?=$this->company?></p> 
<p>Loại yêu cầu: <?=$this->request?></p> 
<p> Nội dung: <?=$this->message?>  </p>

Liên hệ từ website: http://hoabinh-group.com

</body>
</html>