<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<title></title>
</head>
<body>
<p>Hello Friend,</p>

<p>You recently requested an email subscription to Global Mice Travel. We can't wait to send the updates you want via email, so please click the following link to activate your subscription immediately:</p>

<p>http://tour.louis-intelli.com/newsletter/activation/id/<?=$this->lastid?></p>

<p>Admin,</p>

<p>Tuan</p>
<p>http://globalmicetravel.com</p>

</body>
</html>