<div class="tabbable">
	<ul class="nav nav-tabs" id="myTab">
				<li class="active">
					<a data-toggle="tab" href="#home">
						<i class="green ace-icon fa fa-home bigger-120"></i>
							Cập nhật timeline
					</a>
				</li>
				<li>
					<a data-toggle="tab" href="#gallery">
						<i class="orange ace-icon fa fa-picture-o bigger-120"></i>
							Quản lý ảnh
					</a>
				</li>

				<li>
					<a data-toggle="tab" href="#seo">
						<i class="blue ace-icon fa fa-search bigger-120"></i>
						SEO
						<span class="badge badge-danger"></span>
					</a>
				</li>
				
				<li>
					<a data-toggle="tab" href="#history">
						<i class="orange ace-icon fa fa-history bigger-120"></i>
						Lịch sử
						<span class="badge badge-danger"></span>
					</a>
				</li>
	</ul>

	<div class="tab-content">
				<div id="home" class="tab-pane fade in active">
			<?php echo $this->form; ?>
			<!--
			<div class="col-xs-3">
													<label>Hiển thị</label>
														<input name="switch-field-1" class="ace ace-switch" type="checkbox" />
														<span class="lbl"></span>
													
												</div>
												-->
 <?php echo $this->Ckeditor('description',350,600); ?>
 				<div style="clear:both"></div>
				</div>
				
				<div id="gallery" class="tab-pane fade">
					<?php echo $_SERVER['SERVER_NAME']; ?>
					
				</div>

				<div id="seo" class="tab-pane fade">
		<form id="seo-form" method="post" action="/admin/timeline/seo">		 									
		<dl class="zend_form">
			<input id="id" type="hidden" value="<?=$this->id?>" name="id">
<dt id="seo_title-label">
         
	<label class="required" for="title">Title:</label>
</dt>

<dd id="seo_title-element">
<input id="seo_title" type="text" size="40" value="<?=$this->title?>" name="seo_title">
<p>Giới hạn <span id= "counter_seo_title"></span> kí tự</p>
</dd>


<dt id="seo_keyword-label">
	<label class="required" for="title">Keyword:</label>
</dt>

<dd id="seo_keyword-element">
<input id="seo_keyword" type="text" size="74" value="<?=$this->keyword?>" name="seo_keyword">
</dd>

<dt id="seo_description-label">
	<label class="required" for="title">Description:</label>
</dt>

<dd id="seo_description-element">
<textarea id="seo_description" name="seo_description" rows="5" cols="40"><?=$this->description?></textarea>
<p>Giới hạn <span id= "counter_seo_description"></span> kí tự</p>
</dd>


<dt id="submit-label"> </dt>
<dd id="submit-element">
<input id="submit-seo" class="btn btn-info" type="submit" value="Save" name="submit-seo">
</dd>
		</dl>
		</form>
				</div>

				<div id="history" class="tab-pane fade">
					<div class="table-responsive">
											<table id="table_history" class="table table-striped table-bordered table-hover">
												<thead>
													<tr>
														<th class="center">
															<label>
																<input type="checkbox" class="ace" />
																<span class="lbl"></span>
															</label>
														</th>
														
														<th>Thời gian</th>
														<th>Người sửa</th>
														<th>Nội dung từ</th>
														<th>Chuyển thành</th>
													
													</tr>
												</thead>

												<tbody>
				<?php echo $this->partialLoop('_history-row.phtml', $this->activities); ?>																						

												</tbody>
											</table>
										</div>
				</div>
											
	</div>
</div>

 <script type="text/javascript">
	 <?php $timestamp = time();?>
	 <?php $photo_url = $this->full_photo;?>
	 
	 $("#gallery").load("<?php echo $photo_url; ?> #gallery_box", function(){
		
var pid = '<?=$this->id?>';

$(document).ready(function() { 
	
 //alert(pid);
 $('#file_upload').uploadifive({
			    'fileType'     : 'image',
			    'queueSizeLimit' : 8,
				'multi'			   : true,
				'auto'             : true,
				'fileSizeLimit' : 7500,
				'formData'         : {
				'timestamp' : '<?php echo $timestamp;?>',
				'token'     : '<?php echo md5('unique_salt' . $timestamp);?>',
				'productID' : pid,
				                     },
				 'buttonText'  : 'Chọn ảnh', 
				'queueID'          : 'queue',
				'uploadScript'     : '/admin/timeline/upload/',
				'onError'      : function(errorType) {
				switch(errorType) {
				case '404_FILE_NOT_FOUND':
					alert('Không tìm thấy tệp tin!');
					break;
				case 'FORBIDDEN_FILE_TYPE':
					alert('Chỉ hỗ trợ định dạng ảnh');
					break;
				case 'FILE_SIZE_LIMIT_EXCEEDED':
				alert('Vượt quá dung lượng cho phép');
				break;
				case 'QUEUE_LIMIT_EXCEEDED':
				alert('Xin vui lòng xóa file ảnh hiện tại trước khi chọn lại file khác!');
				//j('.stdelete').trigger('click');
				//j('#file_upload').uploadifive('clearQueue').trigger('click');
				break;
				default:
				alert(errorType);
				alert('Có lỗi, xin thử lại');
				break;
				   }
                } ,
                'onSelect' : function(queue) {
             
     
				} ,
                 'onCancel'     : function() {
           // alert('The file ' + file.name + ' was cancelled!');
                 } ,
             'onProgress': function(file, e) {
				 //  console.log(e);
            
			
				 },
      
        
                'onUpload'     : function(filesToUpload) {
          
					} ,
			'onUploadComplete' : function(file, data, response) {
				
				//console.log(data);
				var obj = jQuery.parseJSON(data);
		var image = '';
		image += '<li id="item_'+ obj.idfile +'">';
		image += '<a href="/public/images/timeline/'+ pid +'/'+ obj.tenfile +'" data-rel="colorbox">';			
		image += '<img id="image_'+ obj.idfile +'" width="150" height="150" alt="150x150" src="/public/images/timeline/'+ pid +'/'+ obj.tenfile +'" />';
		image += '<div class="text"><div class="inner">Caption</div></div>';
		image += '</a>';
		image += '<div class="tools tools-bottom">';
		image += '<a href="#"><i class="ace-icon fa fa-link"></i></a>';
		image += '<a href="#"><i class="ace-icon fa fa-paperclip"></i></a>';
		image += '<a href="#"><i class="ace-icon fa fa-pencil"></i></a>';
		image += '<a style="cursor: pointer" onclick="deleteItem(this)" data="del_'+ obj.idfile +'">';
		image += '<i class="ace-icon fa fa-times red"></i>';
		image += '</a>';
		image += '</div>';
		image += '</li>';

		$('.ace-thumbnails').append(image);
var img = $('#image_'+ obj.idfile);
	console.log(img);
	var options = {
			debug: true, 
			width: 277, 
			height: 156
			};
	
			$('#image_'+ obj.idfile).each(function(){
    $(this).load(function(){
        window.setTimeout(function(){
		var img = this;
            SmartCrop.crop(img, options, function(result){
             
                console.log(img.src, result);
                var crop = result.topCrop,
                    canvas = $('<canvas>')[0],
                    ctx = canvas.getContext('2d');
                canvas.width = options.width;
                canvas.height = options.height;
                ctx.drawImage(img, crop.x, crop.y, crop.width, crop.height, 0, 0, canvas.width, canvas.height);
             
            // console.log(canvas);
            var dataUrl = canvas.toDataURL(); 
            // console.log(dataUrl);
             
             $.ajax({
  type: "POST",
  url: "/admin/timeline/uploadthumb",
  data: { 
     imgBase64: dataUrl,
     pid: pid,
     pname: obj.tenfile
  }
}).done(function(o) {
  console.log('saved'); 

});		
				
				
	  });
	
			 }.bind(this), 100);
    });
    if(this.complete){
        $(this).load();
        }
});
	
		
		function deleteItem(o){
		//alert($(o).attr('data'));
		var data =  $(o).attr('data');
		var item = data.split('_')[1];
		//alert(item);
		var productID = pid;
		$('#item_'+item).fadeOut();
		var dataString = 'itemDel=' + item + '&pID=' + productID;
		 $.ajax({
            type: "POST",
            url: "/admin/timeline/delitem",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
	}
	
	//$('#radio_')
	
	//var input = $('input:radio[name="default"]');
	$(".CheckBoxClass").change(function(){
	var var_name = $(this).val(); 
	var itemId = $(this).attr('id');
	var new_itemID = itemId.split('_')[1];
	var productID = pid;
	//alert(new_itemID);
  dataString = 'itemDef=' + new_itemID + '&pID=' + productID;
	$.ajax({
            type: "POST",
            url: "/admin/timeline/default",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
  
  	});
  	
  	var $overflow = '';
	var colorbox_params = {
		rel: 'colorbox',
		reposition:true,
		scalePhotos:true,
		scrolling:false,
		previous:'<i class="ace-icon fa fa-arrow-left"></i>',
		next:'<i class="ace-icon fa fa-arrow-right"></i>',
		close:'&times;',
		current:'{current} of {total}',
		maxWidth:'100%',
		maxHeight:'100%',
		onOpen:function(){
			$overflow = document.body.style.overflow;
			document.body.style.overflow = 'hidden';
		},
		onClosed:function(){
			document.body.style.overflow = $overflow;
		},
		onComplete:function(){
			$.colorbox.resize();
		}
	};

	$('.ace-thumbnails [data-rel="colorbox"]').colorbox(colorbox_params);
	$("#cboxLoadingGraphic").html("<i class='ace-icon fa fa-spinner orange fa-spin'></i>");//let's add a custom loading icon
	
	
	$(document).one('ajaxloadstart.page', function(e) {
		$('#colorbox, #cboxOverlay').remove();
   });
  			
			}
	
	}); 
	
}); 
function deleteItem(o){
		//alert($(o).attr('data'));
		var data =  $(o).attr('data');
		var item = data.split('_')[1];
		//alert(item);
		var productID = pid;
		$('#item_'+item).fadeOut();
		var dataString = 'itemDel=' + item + '&pID=' + productID;
		 $.ajax({
            type: "POST",
            url: "/admin/timeline/delitem",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
	}
	
	//$('#radio_')
	
	//var input = $('input:radio[name="default"]');
	$(".CheckBoxClass").change(function(){
	var var_name = $(this).val(); 
	var itemId = $(this).attr('id');
	var new_itemID = itemId.split('_')[1];
	var productID = pid;
	//alert(new_itemID);
  dataString = 'itemDef=' + new_itemID + '&pID=' + productID;
	$.ajax({
            type: "POST",
            url: "/admin/timeline/default",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
  
  	});

			jQuery(function($) {
	var $overflow = '';
	var colorbox_params = {
		rel: 'colorbox',
		reposition:true,
		scalePhotos:true,
		scrolling:false,
		previous:'<i class="ace-icon fa fa-arrow-left"></i>',
		next:'<i class="ace-icon fa fa-arrow-right"></i>',
		close:'&times;',
		current:'{current} of {total}',
		maxWidth:'100%',
		maxHeight:'100%',
		onOpen:function(){
			$overflow = document.body.style.overflow;
			document.body.style.overflow = 'hidden';
		},
		onClosed:function(){
			document.body.style.overflow = $overflow;
		},
		onComplete:function(){
			$.colorbox.resize();
		}
	};

	$('.ace-thumbnails [data-rel="colorbox"]').colorbox(colorbox_params);
	$("#cboxLoadingGraphic").html("<i class='ace-icon fa fa-spinner orange fa-spin'></i>");//let's add a custom loading icon
	
	
	$(document).one('ajaxloadstart.page', function(e) {
		$('#colorbox, #cboxOverlay').remove();
   });
})
	

	
	//$('#radio_')
	
	//var input = $('input:radio[name="default"]');


	 });
	 
 var frm = $('#seo-form');
    frm.submit(function (ev) {
	     ev.preventDefault();
	     console.log(frm.serialize());
        $.ajax({
            type: frm.attr('method'),
            url: frm.attr('action'),
            data: frm.serialize(),
            success: function (data) {
                alert('Cập nhật seo thành công!');

            }
        });

       
    });	
    
      $('#seo_title').simplyCountable({
    counter: '#counter_seo_title',
    countable: 'characters',
    maxCount: 60,
    strictMax: true,
    countDirection: 'down',
    safeClass: 'safe',
    overClass: 'over',
    thousandSeparator: ','
});
    
    $('#seo_description').simplyCountable({
    counter: '#counter_seo_description',
    countable: 'characters',
    maxCount: 156,
    strictMax: true,
    countDirection: 'down',
    safeClass: 'safe',
    overClass: 'over',
    thousandSeparator: ','
});
</script>



<script type="text/javascript">
	
		$(".CheckBoxClass").change(function(){
	var var_name = $(this).val(); 
	var itemId = $(this).attr('id');
	var new_itemID = itemId.split('_')[1];
	var productID = '<?=$this->id?>';
	//alert(new_itemID);
  dataString = 'itemDef=' + new_itemID + '&pID=' + productID;
	$.ajax({
            type: "POST",
            url: "/admin/timeline/default",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
  
  	});
	
	function deleteItem(o){
		//alert($(o).attr('data'));
		var data =  $(o).attr('data');
		var item = data.split('_')[1];
		//alert(item);
		var productID = '<?=$this->id?>';
		$('#item_'+item).fadeOut();
		var dataString = 'itemDel=' + item + '&pID=' + productID;
		 $.ajax({
            type: "POST",
            url: "/admin/timeline/delitem",
            data: dataString,
            dataType: 'json',
            success: function(data){
              console.log(data);
			 
 
            }
        });
		
	 return false;
	}
	//var listTags = '';
			jQuery(function($) {
				
				
				
				var tag_input = $('#tags');
				try{
					tag_input.tag(
					  {
						placeholder:tag_input.attr('placeholder'),
						//enable typeahead by specifying the source array
					
						source: <?=$this->resulttags?>
		
						
					  }
					)
			
					//programmatically add a new
					var $tag_obj = $('#tags').data('tag');
					//$tag_obj.add('Programmatically Added');
				}
				catch(e) {
					//display a textarea for old IE, because it doesn't support this plugin or another one I tried!
					tag_input.after('<textarea id="'+tag_input.attr('id')+'" name="'+tag_input.attr('name')+'" rows="3">'+tag_input.val()+'</textarea>').remove();
					//$('#form-field-tags').autosize({append: "\n"});
				}
				
					$('.chosen-select').chosen({allow_single_deselect:true,search_contains:true,placeholder_text_multiple:'Chọn địa điểm'}); 
					//resize the chosen on window resize
			
					$(window)
					.off('resize.chosen')
					.on('resize.chosen', function() {
						$('.chosen-select').each(function() {
							 var $this = $(this);
							 $this.next().css({'width': $this.parent().width()});
						})
					}).trigger('resize.chosen');
					//resize chosen on sidebar collapse/expand
					$(document).on('settings.ace.chosen', function(e, event_name, event_val) {
						if(event_name != 'sidebar_collapsed') return;
						$('.chosen-select').each(function() {
							 var $this = $(this);
							 $this.next().css({'width': $this.parent().width()});
						})
					});
			
			
					$('#chosen-multiple-style .btn').on('click', function(e){
						var target = $(this).find('input[type=radio]');
						var which = parseInt(target.val());
						if(which == 2) $('#form-field-select-4').addClass('tag-input-style');
						 else $('#form-field-select-4').removeClass('tag-input-style');
					});
						
			});
			
	/*	$(".slim-btn-remove").on('click', function(){
			alert();
		});*/
			
		</script>
		
		
	